### PR TITLE
fix toonily and add madara websites (#2435)

### LINKED ISSUE #2426: [Site Request] Manga Şehri
Name of the website:
Manga Şehri

•	Site:  https://mangasehri.com
•	Manga List: https://mangasehri.com/manga/
•	Manga example:  https://mangasehri.com/manga/the-sacred-ruins/
•	Chapter online viewer example:  https://mangasehri.com/manga/the-sacred-ruins/bolum-1/

Language: Turkish

### LINKED ISSUE #2435: [Toonily] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
None of the chapters show up for any of the titles.

**To Reproduce**
1. Toonily
2. All titles
3. All chapters

**Screenshots**
SS

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Robonau**
content = content.replace(/<\/?noscript>/g, '');
was replacing something it shouldn't have
removing it fixed the no chapters issue 

note: i don't actually know what it does, so don't ask me to explain why it fixes it
(ik its part of the code that changes the plain text DOM in to a usable structure but that's it)

### CODE REVIEW

**Comment by 27136773** [comment]
Toonily should not overwrite this method, instead i would suggest to revert `Connector.mjs` by removing the line that replaces `noscript` tags.
These tags [were removed because of an issue with Kiryuu](https://github.com/manga-download/hakuneko/pull/2359#discussion_r494393541), but this is no longer required due to upcoming changes for Kiryuu.

**Comment by Robonau** [comment]
done, i reverted and changed Connector.mjs to not have the noscript line

**Comment by Robonau** [comment]
i wasn't aware of what it was actually for (as i said in the og post) was just doing what i thought was safe

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/MangaSehri.mjs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import WordPressMadara from './templates/WordPressMadara.mjs';
+
+export default class mangasehri extends WordPressMadara {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaSehri.mjs]: May use same class name as the file is named (PascalCase is preferred)

**Comment by ghost** [comment]
Hi,
I'm trying to download from toonily but I can't. I see that you have fixed the issue I am having. How do I get the latest version that has the issue fixed? 
Sorry if this is not how things are done.

**Comment by 27136773** [comment]
Download nightly build from release section
