### PR TITLE
some sites fix

### LINKED ISSUE #2886: Aloalivn, Manhuaus,
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm a Mac userTitles and chapters show but the pages are blank on preview and downloads as .bin file

**To Reproduce**
1. Aloalivn, Manhua Us, Manhuas
2. all titles and chapter have this issue (except Manhuas has a couple of titles still work while the rest do not.)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
    no error messages.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

Screen Shot 2021-01-08 at 3 20 01 PM

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2925: [Aloalivn] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download any manga or read them 

**To Reproduce**
1. Name of connector Aloalivn
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
index.html:46 Loading Engine: HakuNeko
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
loadClassicPolymer @ index.html:76
VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (VRV.mjs:303)
    at EventTarget.load (Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
(anonymous) @ VRV.mjs:305
Settings.mjs:371 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
(anonymous) @ Settings.mjs:371
BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
(anonymous) @ BookmarkManager.mjs:137
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-solid-900.woff2?v=5.8.2
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-regular-400.woff2?v=5.8.2
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-brands-400.woff2?v=5.8.2
**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2971: [Manhua us] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes, tried deleting cache and restarting, problem persists.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes (please see attached screenshot of chapter 263 from manhuaus below)

Image 3

**Describe the bug**
Previously, working. Manga list updates successfully but only empty pages in several manga. Downloaded tiny empty 001.bin files. Other connectors/sites used do not have this problem.

**To Reproduce**
1. Name of connector: Manhua us
2. Name of manga (connector update is working): Against the Gods
3. Name of chapter (manga update is working): 262-267, different number of empty pages for each chapter in preview
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): no messages

**Screenshots**
Image 1
Image 2

**HakuNeko (please complete the following information):**
 - Version 6.1.7@17a6fb

### LINKED ISSUE #2985: [ManhuaPlus] Issue on 1 title
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
2 problems: 
1. for some reason in order to successfully download a chapter first you must hit the preview on the chapter before        downloading or you get .bin blanks.
2. Soul Land IV is producing and error. 
Screen Shot 2021-01-23 at 3 12 00 PM

It's a new title added to connector site and the only title having this issue. The site is working perfectly fine and I've tried a few tricks including rebooting, but no luck. BTW there is no logins or anything of the sort.

Thanks.

**To Reproduce**
1. Name of connector-  ManhuaPlus
2. Name of manga (if connector update is working)- Soul Land IV
3. Name of chapter (if manga update is working)- All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)- See above

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Robonau**
resolves #2886
resolves #2925
resolves #2971
resolves #2985

### CODE REVIEW

**Comment by Robonau** [comment]
perhaps the [mangaku fix](https://github.com/manga-download/hakuneko/commit/2df11c8b6ea933b7ebfa121d8e82e524bf6bcf24#diff-88c2c925a0d5fa6b8d9b267fe6225ce1298cd58b416f70ca439203934bf6e630L38) broke this as well as imgur, the timing ads up (the first time this issue was made was a day after the mangaku fix)

**Comment by Robonau** [comment]
it was the mangaku fix that broke these sites

File: src/web/mjs/connectors/Manga347.mjs [hunk 1]
```diff
@@ -6,9 +6,9 @@ export default class Manga347 extends WordPressMadara {
         super();
         super.id = 'manga347';
         super.label = 'Manga 347';
-        this.tags = [ 'webtoon', 'english' ];
+        this.tags = ['webtoon', 'english'];
         this.url = 'https://manga347.com';
 
-        this.queryPages = 'ul.blocks-gallery-grid li.blocks-gallery-item figure source';
+        this.queryPages = ['figure source', 'div.page-break source'];
```
Comment (27136773) [inline src/web/mjs/connectors/Manga347.mjs]: Use a string instead of an array
`'figure source, div.page-break source'`

File: src/web/mjs/connectors/ManhuaPlus.mjs [hunk 2]
```diff
@@ -8,11 +8,6 @@ export default class ManhuaPlus extends WordPressMadara {
         super.label = 'ManhuaPlus';
         this.tags = [ 'webtoon', 'vietnamese' ];
         this.url = 'https://manhuaplus.com';
-    }
-
-    async _getPages(chapter) {
-        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
-        let data = await this.fetchDOM(request, 'li.blocks-gallery-item source');
-        return data.map(element => this.getAbsolutePath(element, this.url));
+        this.queryPages = ['figure source', 'div.page-break source'];
```
Comment (27136773) [inline src/web/mjs/connectors/ManhuaPlus.mjs]: Use a string instead of an array
`'figure source, div.page-break source'`

File: src/web/mjs/connectors/templates/MojoPortalComic.mjs [hunk 3]
```diff
@@ -95,6 +95,7 @@ export default class MojoPortalComic extends Connector {
     async _handleConnectorURI(payload) {
         let request = new Request(payload.url, this.requestOptions);
         request.headers.set('x-referer', payload.referer);
+        request.headers.set('accept', 'image/webp,image/apng,image/*,*/*');
```
Comment (27136773) [inline src/web/mjs/connectors/templates/MojoPortalComic.mjs:98]: Maybe it would be more appropriate placing this hack somewhere in [Request.mjs](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/engine/Request.mjs#L440) with a condition to check for `uri.hostname.includes('imgur.com')` so it will apply to all imgur image links.

File: src/web/mjs/connectors/templates/WordPressMadara.mjs [hunk 4]
```diff
@@ -88,23 +88,37 @@ export default class WordPressMadara extends Connector {
         // TODO: setting this parameter seems to be problematic for various website (e.g. ChibiManga, AniMangaES server will crash)
         uri.searchParams.set('style', 'list');
         let request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, this.queryPages);
+        let data;
+        if (this.queryPages instanceof Array) {
```
Comment (27136773) [inline src/web/mjs/connectors/templates/WordPressMadara.mjs]: CSS queries have support for or operator (`,`), so there is no need to iterate through multiple queries (this implementation would also break the page order in case the queries are alternating)

File: src/web/mjs/connectors/templates/WordPressMadara.mjs [hunk 5]
```diff
@@ -88,23 +88,37 @@ export default class WordPressMadara extends Connector {
...
          * TODO: only perform requests when from download manager
          * or when from browser for preview and selected chapter matches
          */
-        this.requestOptions.headers.set('x-referer', payload.referer);
-        let promise = super._handleConnectorURI(payload.url);
-        this.requestOptions.headers.delete('x-referer');
-        return promise;
+        let request = new Request(payload.url, this.requestOptions);
+        request.headers.set('x-referer', payload.referer);
+        request.headers.set('accept', 'image/webp,image/apng,image/*,*/*');
```
Comment (27136773) [inline src/web/mjs/connectors/templates/WordPressMadara.mjs:106]: Could be removed in case this is checked for each request globally...

Comment (Robonau) [reply src/web/mjs/connectors/templates/WordPressMadara.mjs:106]: this is the whole reason this PR exists 
if this isn't here the sites respond with some html rather than the image

(edit) : see https://github.com/manga-download/hakuneko/issues/2925#issuecomment-760201931
hn gets the html one

File: src/web/mjs/connectors/templates/MojoPortalComic.mjs (hunk 3 above)
Comment (Robonau) [reply src/web/mjs/connectors/templates/MojoPortalComic.mjs:98]: its not just imgur though

Comment (Robonau) [reply src/web/mjs/connectors/templates/MojoPortalComic.mjs:98]: its literally every image on all of the resolved issue sites

File: src/web/mjs/connectors/templates/WordPressMadara.mjs (hunk 5 above)
Comment (Robonau) [reply src/web/mjs/connectors/templates/WordPressMadara.mjs:106]: note: this doesn't seem to happen for everyone

File: src/web/mjs/connectors/templates/MojoPortalComic.mjs (hunk 3 above)
Comment (Robonau) [reply src/web/mjs/connectors/templates/MojoPortalComic.mjs:98]: see https://github.com/manga-download/hakuneko/issues/2925#issuecomment-760201931
hn gets the html one

**Review by 27136773 — APPROVED** [review]
Would prefer to add the header condition globally into a single place (e.g. `Request.mjs`) instead of setting the header in each connector that may use images from imgur.
Since we have our hands full right now and this will do the trick i'll approve it for now.
