### PR TITLE
Manganato : change Regex for clipboard

### LINKED ISSUE #5072: [Manganato] Connector not working/ Url changed for some titles
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
to be precise mangakakalot redirected me to manganato.
some manga still have the original working urls others changed to chapmanganato.com

**To Reproduce**
1. [Manganato](https://manganato.com/)
2. https://chapmanganato.com/manga-ba979135

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #5178: [manganato.com] Connector not working
website changed, older bookmarks displayed. some remain blank 
here is a example of a "working" bookmark,
https://manganato.com/manga-nt990654

This is a non working one. 
https://chapmanganato.com/manga-de980539

### PR DESCRIPTION
**Pull request by MikeZeDev**
* m subdomain doesnt work anymore
* no more chap and read subdomains they are full domains (readmanganato redirect to chapmanganato anyway)
* Support manganato.com, readmanganato.com and chapmanganato.com
* Fixes https://github.com/manga-download/hakuneko/issues/5072 fixes https://github.com/manga-download/hakuneko/issues/5178

### CODE REVIEW

File: src/web/mjs/connectors/MangaNel.mjs [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default class MangaNel extends Connector {
 
     canHandleURI(uri) {
         // Test: https://regex101.com/r/aPR3zy/3/tests
-        return /^(m\.|chap\.)?(read)?manganato\.com$/.test(uri.hostname);
+        return /^(chap)?(read)?manganato\.com$/.test(uri.hostname);
```
Comment (Sheepux) [inline src/web/mjs/connectors/MangaNel.mjs]: `^(chap|read)?manganato\.com$`
https://regex101.com/r/l22XIL/1

**Review by Sheepux — APPROVED** [review]
LGTM
small regexp improvement possible
