### PR TITLE
Fix getting pictures in Mangatown

### LINKED ISSUE #4726: [Bug] Can't Enjoy the Downloaded File
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I cannot seem to download the picture.. well, I can download it, but the file is just broken. When I downloaded a certain chapter (i.e.: Black Clover 331), the output only showed files with **_.bin_** extension instead of **_.jpg_**, **_.jpeg_**, or **_.png_**; the issue occurs on MangaTown & MangaHere, I dunno if the same case exists elsewhere.

**To Reproduce**
1. Select a website (MangaTown or MangaHere)
2. Select any manga & any chapter to download
3. Open your folder of downloaded chapter
4. Witness the majestic bugs 👀

**Expected behavior**
an outcome of solid pictures just like what the usual HakuNeko offers ):

**Screenshots**
HaquNeqo

**Context (please complete the following information):**
 - OS: Windows 11 Pro
 - 6.17

**Additional context**
I'm from **Indonesia** & I can access the site just fine, even without a VPN.
I tried downloading 1 random chapter from **Kissmanga & it works just fine**.

### PR DESCRIPTION
**Pull request by MikeZeDev**
Add mangahere referer to picture requests. Fixes https://github.com/manga-download/hakuneko/issues/4726

### CODE REVIEW

**Comment by 27136773** [comment]
Check and fix `lint` errors.

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/MangaTown.mjs [hunk 1]
```diff
@@ -66,6 +66,7 @@ export default class MangaTown extends Connector {
     }
 
     _handleConnectorURI( payload ) {
+        this.requestOptions.headers.set("x-referer", "mangahere.com");
```
Comment (27136773) [inline src/web/mjs/connectors/MangaTown.mjs]: This will add `MangaHere` as referer to all requests for this connector (manga lists, chapter lists, ...), is this intentional?
If not create a clone of request options and add the header to the clone.

Comment (Sheepux) [reply src/web/mjs/connectors/MangaTown.mjs]: personally i'd rather reject the request and alert("use mangahere directly")

Comment (MikeZeDev) [reply src/web/mjs/connectors/MangaTown.mjs]: Hum, you are right, better not meddle with the entire request options.

Comment (MikeZeDev) [reply src/web/mjs/connectors/MangaTown.mjs]: In fact setting the referer to mangahere is only needed for downloading pictures, which is in fine handled by  Connector.handleconnectorURI. And it uses "this.requestoptions" without referer. No matter what i do in mangatown own handleconnectorURI, its useless .

Is there any reason we are using handleconnectorURI in this connector? How could i set a referer but only for picture requests? I can only think about dirty workarounds.

Comment (27136773) [reply src/web/mjs/connectors/MangaTown.mjs]: Just set the header on the cloned request...
```javascript
let request = new Request(payload, this.requestOptions);
request.headers.set('x-referer', 'https://mangahere.com');
```

Comment (MikeZeDev) [reply src/web/mjs/connectors/MangaTown.mjs:69]: This request get the page with the pics, and we dont need mangahere ref for that. :)

Downloading pictures need mangahere ref.

Which is done not in Mangatown.mjs but in parent class, where i cant pass a custom referrer .
Wait, can we pass a custom referer in payloads?

Comment (MikeZeDev) [reply src/web/mjs/connectors/MangaTown.mjs]: I managed to fix the code so only picture requests get to use mangahere referer.

File: src/web/mjs/connectors/MangaTown.mjs [hunk 2]
```diff
@@ -56,23 +51,32 @@ export default class MangaTown extends Connector {
...
+        let imgpages = data
             .filter(option => !option.value.endsWith('featured.html'))
-            .map(element => this.createConnectorURI(this.getAbsolutePath(element.value, request.url)));
+            .map(element => this.getAbsolutePath(element.value, request.url));
+        //NOW we have all the pages, get the picture url from each page
+        //and create the payloads with mangahere referer
+        let imglist = [];
+        for (let i = 0; i<imgpages.length; i++ ) {
+            let request = new Request(imgpages[i], this.requestOptions);
+            data = await this.fetchDOM( request, 'source#image' );
```
Comment (27136773) [inline src/web/mjs/connectors/MangaTown.mjs]: I strongly recommend to move the content of this loop as part into `_handleConnectorURI`.
The `_getPages` method is supposed to be fast and should not make too many requests if possible.
e.g.,

```javascript
async _handleConnectorURI(payload) {
    const pageData = await this.fetchDOM(new Request(payload, this.requestOptions), 'source#image');
    const imageURL = this.getAbsolutePath(pageData[0].src, request.url).replace('hakuneko://', 'https://');
    const request = new Request(imageURL, this.requestOptions);
    request.headers.set('x-referer', 'mangahere.com');
    const response = await fetch(request);
    const imageData = await response.blob();
    return this._blobToBuffer(imageData);
}
```

Comment (MikeZeDev) [reply src/web/mjs/connectors/MangaTown.mjs]: Done
