### PR TITLE
[Kanjiku] updated connector for their site.

### LINKED ISSUE #3397: [Kanjiku.net] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Manga List does not show any of the mangas that are listed on the website.
The network tab in the inspector says that it tried loading `https://kanjiku.net/wp-admin/admin-ajax.php` and the page itself says:

> The page you were looking for doesn't exist.

and the console gives a 404 response.

**To Reproduce**
1. Loading manga from https://kanjiku.net/

**HakuNeko (please complete the following information):**
 - Version 6.1.7@845bf9

### PR DESCRIPTION
**Pull request by Shirobaka**

### CODE REVIEW

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 1]
```diff
@@ -1,12 +1,65 @@
...
+        let title = data[0].textContent.trim();
+        return new Manga(this, id, title);
+    }
+
+    async _getMangas() {
+        let request = new Request(new URL('/mangas', this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, 'div.manga_flex-row a.manga_box');
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element, request.url),
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: May prefer `this.url` over `request.url`

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 2]
```diff
@@ -1,12 +1,65 @@
...
+
+    async _getChapters(manga) {
+        let request = new Request(new URL(manga.id, this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, 'div.tab1 div.manga_overview_box a.latest_ch_number');
+        return data.map(element => {
+            let payload = {
+                id: this.getRootRelativeOrAbsoluteLink(element, request.url).substring(0, this.getRootRelativeOrAbsoluteLink(element, request.url).length -1)+'0',
+                title: element.text,
+            };
+			return payload;
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: Too much indentation

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 3]
```diff
@@ -1,12 +1,65 @@
...
+            };
+        });
+    }
+
+    async _getChapters(manga) {
+        let request = new Request(new URL(manga.id, this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, 'div.tab1 div.manga_overview_box a.latest_ch_number');
+        return data.map(element => {
+            let payload = {
+                id: this.getRootRelativeOrAbsoluteLink(element, request.url).substring(0, this.getRootRelativeOrAbsoluteLink(element, request.url).length -1)+'0',
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: Use local variable when used multiple times `const id = getRootRelativeORAbsoluteLink(...);`
May use regex to replace the last character `'abc'.replace(/.$/, '0')`
May use slice to replace last character `'abc'.slice(0, -1) + '0'`
May prefer `this.url` over `request.url`

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 4]
```diff
@@ -1,12 +1,65 @@
...
+			return payload;
+        });
+    }
+
+    async _getPages(chapter) {
+        let request = new Request(this.url + chapter.id, this.requestOptions);
+		let data = await this.fetchDOM(request, 'div.container source');
+        return data.map(element => {
+            let payload = {
+                url: this.getAbsolutePath(element, request.url).substring(0, this.getAbsolutePath(element, request.url).length -24),
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: May use `slice(0, -24)`

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 5]
```diff
@@ -1,12 +1,65 @@
...
+            };
+			return payload;
+        });
+    }
+
+    async _getPages(chapter) {
+        let request = new Request(this.url + chapter.id, this.requestOptions);
+		let data = await this.fetchDOM(request, 'div.container source');
+        return data.map(element => {
+            let payload = {
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: Can't image links be used directly instead of creating a connector URI?
I tested some on the website and none of them required a referer...

**Review by 27136773 — COMMENTED** [review]
Implementation looks good
Minor improvements possible

**Comment by Shirobaka** [comment]
> 
> 
> Implementation looks good
> Minor improvements possible

Did some changes according to your comments, thanks for pointing it out.

File: src/web/mjs/connectors/Kanjiku.mjs [hunk 6]
```diff
@@ -1,12 +1,59 @@
...
+        });
+    }
+
+    async _getPages(chapter) {
+        let request = new Request(this.url + chapter.id, this.requestOptions);
+        let data = await this.fetchDOM(request, 'div.container source');
+        return data.map(image => this.getAbsolutePath(image, this.url).replace(/.{24}$/, ''));
+    }
+
+    async _handleConnectorURI(payload) {
```
Comment (27136773) [inline src/web/mjs/connectors/Kanjiku.mjs]: Method can now be removed, since the `_getPages()` method no longer uses the connector handling system (returns now direct image links)

**Review by 27136773 — APPROVED** [review]
Feel free to resolve the comments that were processed (fixed or wont-fixed), so the maintainers know when ready for merge
I activated the automatic pipeline for you, so from now on your PRs will trigger the quality gate builds

**Comment by Shirobaka** [comment]
> 
> 
> Feel free to resolve the comments that were processed (fixed or wont-fixed), so the maintainers know when ready for merge
> I activated the automatic pipeline for you, so from now on your PRs will trigger the quality gate builds

`_handleConnectorURI` removed, ready for final approve and merge.
