### PR TITLE
Fix  ComicZerosum : no more Speedbind

### LINKED ISSUE #6222: [Comic ZEROSUM] website change
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga series and chapter list isn't refreshing

### Describe the bug

Comic ZEROSUM [has renewal their site](https://twitter.com/comic_zerosum/status/1702168052400603450). Hakuneko can't fetch any manga series and chapter list, also look like they change viewer to something.

### To Reproduce

1. Name of connector: Comic ZEROSUM
2. Name of manga (if connector update is working): All
3. Name of chapter (if manga update is working): All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): get 404 on manga series and chapter list.

### Screenshots

image

### PR DESCRIPTION
**Pull request by MikeZeDev**
Its using custom API + protobuf.
Fixes https://github.com/manga-download/hakuneko/issues/6222

### CODE REVIEW

File: src/web/mjs/connectors/ComicZerosum.mjs [hunk 1]
```diff
@@ -1,37 +1,65 @@
...
             };
         });
     }
 
     async _getChapters(manga) {
-        const request = new Request(`${this.data_url}/works/${manga.id}.json`, this.requestOptions);
-        const data = await this.fetchJSON(request);
-
-        return data.Work.Stories.map(story => {
+        //'https://api.zerosumonline.com/api/v1/title?tag=
```
Comment (27136773) [inline src/web/mjs/connectors/ComicZerosum.mjs]: Comments seems redundant and may be removed

**Review by 27136773 — APPROVED** [review]
