### PR TITLE
[tapas] Fix chapter pagination and pages

### LINKED ISSUE #1796: Tapas.io not working anymore
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Hakuneko finds no chapter regardless of the series

**To Reproduce**
1. Go to https://tapas.io/series/OutoftheBlue/info
2. Search Out of the Blue on Hakuneko

**Expected behavior**
There is no visible chapter for the 3 "Out of the Blue" results.
With a direct link, I get the same result.

**Screenshots**
Sans titre
Sans titre

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 7.1.11

Thanks for your help ! :)

### PR DESCRIPTION
**Pull request by XenonR**
Closes #1796

### CODE REVIEW

File: src/web/mjs/connectors/Tapas.mjs [hunk 1]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
         let chapterList = [];
+
         let request = new Request(new URL(manga.id, this.url), this.requestOptions);
-        let data = await this.fetchDOM(request, 'div.paging a.paging__button--num');
-        let pageCount = data.length === 0 ? 1 : parseInt(data.pop().href.match(/pageNumber=(\d+)/)[1]);
-        for(let page = 1; page <= pageCount; page++) {
-            let chapters = await this._getChaptersFromPage(manga, page);
-            chapterList.push(...chapters);
+        let data = await this.fetchDOM(request, 'meta[name="twitter:app:url:iphone"]');
+        const series_id = data[0].content.match(/((?:\/series\/)\d+)/)[0];
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs]: Regex may be simplified to `match(/\/series\/\d+/)[0]` without the capturing and non-capturing group

Regex101: https://regex101.com/r/rTvNwf/1

File: src/web/mjs/connectors/Tapas.mjs [hunk 2]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
+
+        let has_next = true;
+        const time = Math.round(new Date().getTime());
+        let page = 1;
+        while (has_next) {
+            request = new Request(new URL(series_id+'/episodes?page='+page+'&sort=OLDEST&init_load=0&since='+time+'&large=true&last_access=0&', this.url), this.requestOptions);
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs:59]: May use search params to compose URL
```javascript
let uri = new URL(series_id, this.url);
uri.searchParams.set('page', page);
uri.searchParams.set('sort', 'OLDEST'); // is this required?
uri.searchParams.set('init_load', 0);
uri.searchParams.set('since', time);
uri.searchParams.set('large', true); // is this required?
uri.searchParams.set('last_access', 0); // is this required?

let request = new Request(uri, this.requestOptions);
```

File: src/web/mjs/connectors/Tapas.mjs [hunk 3]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
-        let data = await this.fetchDOM(request, 'div.paging a.paging__button--num');
-        let pageCount = data.length === 0 ? 1 : parseInt(data.pop().href.match(/pageNumber=(\d+)/)[1]);
-        for(let page = 1; page <= pageCount; page++) {
-            let chapters = await this._getChaptersFromPage(manga, page);
-            chapterList.push(...chapters);
+        let data = await this.fetchDOM(request, 'meta[name="twitter:app:url:iphone"]');
+        const series_id = data[0].content.match(/((?:\/series\/)\d+)/)[0];
+
+        let has_next = true;
+        const time = Math.round(new Date().getTime());
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs]: May be simplified to `const time = Date.now();`

File: src/web/mjs/connectors/Tapas.mjs [hunk 4]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
+            page++;
         }
+
         return chapterList;
     }
 
-    async _getChaptersFromPage(manga, page) {
-        let request = new Request(new URL(`${manga.id}?pageNumber=${page}`, this.url), this.requestOptions);
-        let data = await this.fetchDOM(request, 'li.content__item  > a');
+    async _getChaptersFromPage(payload) {
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs]: May clarify method name, since it extracts chapters from HTML content instead of fetching it from a page

File: src/web/mjs/connectors/Tapas.mjs [hunk 5]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
+        let data = this.createDOM(payload).querySelectorAll('li.episode-list__item  > a');
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs]: Spread the node list iterator to an array `let data = [...HtmlNodeList];`

File: src/web/mjs/connectors/Tapas.mjs [hunk 6]
```diff
@@ -47,24 +47,34 @@ export default class Tapas extends Connector {
...
+        data = Array.prototype.slice.call(data);
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs]: This slice call seems redundant when spreading `data` and may be removed

**Review by 27136773 — APPROVED** [review]
Looks good, may add some optimizations

File: src/web/mjs/connectors/Tapas.mjs (hunk 2 above)
Comment (XenonR) [reply src/web/mjs/connectors/Tapas.mjs:59]: Parameters are copied from a real query and I want to leave as little clues the query is not from a normal browser. Since the most stuff is static I opted for 'just a string' here.
