### PR TITLE
[Bato.to] Connector not working #2413

### LINKED ISSUE #2413: [Bato.to] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list
Copy link doesn't work

**To Reproduce**
1. Bato.to

2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
bato

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Robonau**
it took 2 days but i got it
resolves #2413

### CODE REVIEW

File: src/web/mjs/connectors/Batoto.mjs [hunk 1]
```diff
@@ -13,17 +13,18 @@ export default class Batoto extends AnyACG {
...
+        this.queryChapters = 'div.episode-list div.main a.visited';
+        this.queryPages = /images\s*=\s*(\[.*\])\s*;/g;
     }
 
     async _getPages(chapter) {
         let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
         let data = await this.fetchRegex(request, this.queryPages);
-        return Object.values(JSON.parse(data[0]));
+        data = Object.values(JSON.parse(data[0]));
+        return data.map(element => this.getAbsolutePath(`https:${element}`, request.url));
```
Comment (27136773) [inline src/web/mjs/connectors/Batoto.mjs]: Use URL constructor to build valid UVStrings with `request.url` as base (otherwise it will fail if e.g. element already starts with `https`)
`data.map(element => new URL(element, request.url).href)`

**Comment by Robonau** [comment]
i gotta change the regex same as ComicPunch

**Comment by 27136773** [comment]
Can be merged as soon as the reported Lint error has been resolved

**Comment by Robonau** [comment]
damn you semicolon!!!

**Review by 27136773 — APPROVED** [review]
Looks good
