### PR TITLE
FIX FirstKiss : domain change and new template

### LINKED ISSUE #6149: [1st Kiss Manga] Change url to https://likemanga.io
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Announcement in their website
Screenshot_2023-08-15-15-28-47-952_eu kanade tachiyomi

### To Reproduce

1. 1st kiss manga is working but no new chapter update
2. There's announcement in their site that they gonna change to https;//likemanga.io
3. Likemanga.io is already running
Screenshot_2023-08-15-15-28-47-952_eu kanade tachiyomi

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6149

### CODE REVIEW

File: src/web/mjs/connectors/FirstKiss.mjs [hunk 1]
```diff
@@ -1,14 +1,88 @@
...
+    async _getPages(chapter) {
+        const uri = new URL(chapter.id, this.url);
+        const request = new Request(uri, this.requestOptions);
+        const data = await this.fetchDOM(request, 'div.reading-detail div.page-chapter source');
+        return data.map(image => this.createConnectorURI(this.getAbsolutePath(image, request.url)));
+    }
+
+    async _handleConnectorURI(payload) {
+        const request = new Request(payload, this.requestOptions);
+        request.headers.set('x-referer', this.url);
```
Comment (Sheepux) [inline src/web/mjs/connectors/FirstKiss.mjs]: header  x-referer already set in  this.requestOptions

**Review by Sheepux — APPROVED** [review]
/LGTM
minor improvement possible
