### PR TITLE
mangacanblog encryption

### LINKED ISSUE #3065: [MangaCan Blog] Connector not working
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
Refreshing series list returns no Chapter list
mangacan blog
.

Copying link of series gives following message in console:
hakuneko://plugins/:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:61 Loading Frontend: frontend@classic-light
index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
mjs/connectors/templates/VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVCrunchyroll._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVCrunchyroll._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/connectors/templates/VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVHiDive._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVHiDive._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/connectors/templates/VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
    at Promise.then.oauthRequest.method (mjs/connectors/templates/VRV.mjs:407)
    at new Promise (<anonymous>)
    at VRVRoosterteeth._login (mjs/connectors/templates/VRV.mjs:399)
    at VRVRoosterteeth._onSettingsChanged (mjs/connectors/templates/VRV.mjs:303)
    at EventTarget.load (mjs/engine/Settings.mjs:298)
    at async loadEngine (index.html:54)
    at async main (index.html:87)
mjs/engine/Settings.mjs:371 WARNING: Cannot access the directory for "Manga Folder" from " 【Folder Viewer】" settings!

ENOENT: no such file or directory, stat '' Error: ENOENT: no such file or directory, stat ''
mjs/engine/BookmarkManager.mjs:137 Failed to load bookmarks: Invalid bookmark list!
index.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: hakuneko://cache/css/fa-solid-900.woff2?v=5.8.2

### PR DESCRIPTION
**Pull request by Sheepux**
Fixes #3065

### CODE REVIEW

File: src/web/mjs/connectors/MangaCanBlog.mjs [hunk 1]
```diff
@@ -30,20 +30,25 @@ export default class MangaCanBlog extends Connector {
...
-        return data.map(element => this.getAbsolutePath(element, request.url));
+        let script = `
+            new Promise(resolve => {
+                var div = document.createElement('div');
+                div.innerHTML = ffff;
+                return resolve(Array.from(div.querySelectorAll('img')).map(item => item.src));
+            });
+        `;
+        let request = new Request(chapter.id, this.requestOptions);
+        return await Engine.Request.fetchUI(request, script);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaCanBlog.mjs]: May remove `await` since async methods will always wrap non-promise returns into promises, but `fetchUI` already returns a promise

File: src/web/mjs/connectors/MangaCanBlog.mjs [hunk 2]
```diff
@@ -30,20 +30,25 @@ export default class MangaCanBlog extends Connector {
 
     async _getChapters(manga) {
         let request = new Request(this.url + manga.id, this.requestOptions);
-        let data = await this.fetchDOM( request, 'div#latestchapters table tr td a.chaptersrec' );
+        let data = await this.fetchDOM( request, 'div#chapterlist ul li div.eph-num a' );
```
Comment (27136773) [inline src/web/mjs/connectors/MangaCanBlog.mjs]: Looks like `WordPressMangastream`, maybe it is possible to use template?

**Review by 27136773 — APPROVED** [review]
Looks good, minor improvments possible

File: src/web/mjs/connectors/MangaCanBlog.mjs (hunk 2 above)
Comment (Sheepux) [reply src/web/mjs/connectors/MangaCanBlog.mjs]: Damn, you're right ! We need a template detector (i don't create much connector, only fixing and therefore have no idea when i encounter one)
