### PR TITLE
Fix BeeToon: filter fake images

### LINKED ISSUE #6592: [Beetoon] fake images
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
So i have been trying to download Chainsaw man which has been great up until Volume 7. it has been EXTREMELY frustrating. NOBODY has it.
I found it on Beetoon and one other site i cannot recall.
it is able to find the manga and get all the scans, but google feedback pages open between each scan, so when you preview every other image is an error. when the downloader sees this, it freaks out and errors and won't download. The one i'm on is Chainsaw Man chapter 72, beetoon.
Please help, this is really frustrating and overwhelming. let me know if you need more information. this is extremely confusing for me already so i may have missed something.

**To Reproduce**
1. choose beetoon
2. Search or find chainsaw man and click
3. Find chapter 70 (if this chapter doesn't do it, try others, its realy inconsistent.)
4. preview, see missing images
5. download it and have it fail
6. view console, see the URL's that have issues

**Expected behavior**
it should preview without any failed images between the actual manga, should not open google feedback or should skip past it somehow, and fully download the manga chapter

**Screenshots**

**Context (please complete the following information):**
 - OS: Windows 10
HakuNekoErr
HakuNekoErr1

 - HakuNeko Version [e.g. 6.17]

**Additional context**
the other site had a similar problem with getting wrong URLS but gave me bin's instead of JPEGS

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6592

### CODE REVIEW

File: src/web/mjs/connectors/BeeToon.mjs [hunk 1]
```diff
@@ -37,4 +37,15 @@ export default class BeeToon extends WordPressZbulu {
             };
         });
     }
-}
\ No newline at end of file
+
+    async _getPages(chapter) {
+        const pages = await super._getPages(chapter);
+        const result = [];
```
Comment (Sheepux) [inline src/web/mjs/connectors/BeeToon.mjs]: use a `pages.map` instead of a temp array

**Review by Sheepux — APPROVED** [review]
/LGTM
minor changes suggested
