### PR TITLE
FIx YoungChampion & ComicMedu : more strict chapter CSS

### LINKED ISSUE #6352: [COMIC MeDu (こみっくめづ)] Connector not working (website change)
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The chapter list appears empty, as Comic Medu just changed its online viewer

### To Reproduce

1. Connector: COMIC MeDu (こみっくめづ)
2. Manga: https://comic-medu.com/series/c2f3978c40eea
3. Chapter: https://comic-medu.com/episodes/beaa305e9cf32
4. Keep in mind that it now displays the links to the chapters in multiple pages, not just a single one like before

### LINKED ISSUE #6353: [YoungChampion] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The chapter list appears empty (apart from previously downloaded chapters, of course). It used to work, so I can only assume it was due to a website change.

### To Reproduce

1. Connector: YoungChampion
2. Manga: https://youngchampion.jp/series/b9eb1d802fda6
3. Chapter: https://youngchampion.jp/episodes/757dee6fa9a92

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6353
Fixes https://github.com/manga-download/hakuneko/issues/6352

* On YoungChampion, there are some chapters which caused problems while listing chapters.
* ComicMedu website has been revamped, its now a clone of YoungChampion. So connector is emptied :D
* Yanmaga is still working (it extends YoungChampion)

### CODE REVIEW

File: src/web/mjs/connectors/YoungChampion.mjs [hunk 1]
```diff
@@ -24,7 +24,7 @@ export default class YoungChampion extends Connector {
         this.queryMangaTitleURI = 'h1.series-h-title span:not([class])';
         this.queryManga = 'div.series-box-vertical a';
         this.queryMangaTitle = 'h2.title-text';
-        this.queryChapter = 'div.series-ep-list a';
+        this.queryChapter = 'div.series-ep-list a#null-false';
```
Comment (27136773) [inline src/web/mjs/connectors/YoungChampion.mjs:27]: This may affect other websites that are extending `YoungChampion`.
Have these websites been tested and are still working?

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/YoungChampion.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/YoungChampion.mjs:27]: Exactly, like ive said, there is only ComicEDU and Yanmaga, it goes without saying , i tested them.
