### PR TITLE
fix lovehug img extraction

### LINKED ISSUE #3035: [LoveHug] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading the chapter doesn't download any images

**To Reproduce**
1. https://lovehug.net/
2. Soukyuu no Ariande (In this example) (if connector update is working)
3. Chapter 140 (if manga update is working)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Robonau**
resolve #3035

### CODE REVIEW

File: src/web/mjs/connectors/templates/FlatManga.mjs [hunk 1]
```diff
@@ -85,7 +85,10 @@ export default class FlatManga extends Connector {
                 try {
                     element.dataset.pagespeedLazySrc = atob(element.dataset.pagespeedLazySrc);
                 } catch(_) { /* ignore */ }
-                return this.getAbsolutePath(element.dataset.src || element.dataset.original || element.dataset.pagespeedLazySrc || element, request.url);
+                try {
```
Comment (Sheepux) [inline src/web/mjs/connectors/templates/FlatManga.mjs:91]: You can simply fuse both try/catch into a single one

Comment (Sheepux) [reply src/web/mjs/connectors/templates/FlatManga.mjs:91]: Hmmm, could be an issue as it would short-circuit by triggering the ignore error....
Isn't there a way to find out the race condition instead of trying them all ?

Comment (Robonau) [reply src/web/mjs/connectors/templates/FlatManga.mjs:91]: idk i just did more of what it was already doing
i assumed it was like that for a reason

File: src/web/mjs/connectors/templates/FlatManga.mjs [hunk 2]
```diff
@@ -85,7 +85,10 @@ export default class FlatManga extends Connector {
...
+                    element.dataset.aload = atob(element.dataset.aload);
+                } catch(_) { /* ignore */ }
```
Comment (27136773) [inline src/web/mjs/connectors/templates/FlatManga.mjs:93]: May use empty `finally` instead of `catch` if not interested in error handling

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/templates/FlatManga.mjs [hunk 3]
```diff
@@ -85,7 +85,10 @@ export default class FlatManga extends Connector {
...
+                return this.getAbsolutePath(element.dataset.aload || element.dataset.src || element.dataset.original || element.dataset.pagespeedLazySrc || element, request.url);
```
Comment (27136773) [inline src/web/mjs/connectors/templates/FlatManga.mjs]: LoveHug now also uses `dataset.srcset`, e.g. view-source:https://lovehug.net/52/44619/
`data-srcset='https://s2.welovemanga.net/images/20210210/92a936b814fec588293061c4630f913006.jpg'`

**Comment by 27136773** [comment]
References: https://github.com/dazedcat19/FMD2/commit/aaa89205679c65e8fffe68bb828dc7388df6c9bb

File: src/web/mjs/connectors/templates/FlatManga.mjs (hunk 2 above)
Comment (Robonau) [reply src/web/mjs/connectors/templates/FlatManga.mjs:93]: if i use finally it throws an error
https://streamable.com/mto3xk
