### PR TITLE
AstralLibrary fix

### LINKED ISSUE #2741: [AstralLibrary] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Doesn't load manga list.

**Screenshots**
Screenshot (727)
Screenshot (726)
Screenshot (725)

**HakuNeko:**
 - Version 6.17@d0b5e2

### PR DESCRIPTION
**Pull request by Robonau**
dumb fix for dumb problem
resolves #2741

there is no chapter list so i had to guess:
can't deal with decimal chapters 
thinks everything has a 0 chapter (not everything does)

### CODE REVIEW

File: src/web/mjs/connectors/AstralLibrary.mjs [hunk 1]
```diff
@@ -10,5 +10,28 @@ export default class AstralLibrary extends WordPressMadaraNovel {
         this.url = 'https://astrallibrary.net';
```
Comment (27136773) [inline src/web/mjs/connectors/AstralLibrary.mjs]: Add `www` subdomain

File: src/web/mjs/connectors/AstralLibrary.mjs [hunk 2]
```diff
@@ -10,5 +10,28 @@ export default class AstralLibrary extends WordPressMadaraNovel {
...
 
         this.novelObstaclesQuery = 'div.ad';
+        this.queryMangas = 'div.item-summary';
+    }
+
+    async _getMangasFromPage(page) {
+        let request = new Request(new URL('page/'+page+1,'https://www.astrallibrary.net/manga-tag/manga/'));
```
Comment (27136773) [inline src/web/mjs/connectors/AstralLibrary.mjs]: Use `this.url`, in case it changes it can be simply changed in a single place.
I think brackets are required to increment the page number, otherwise the `page` is first appended to the string and the `1` may also be appended, e.g. `'xxx' + 7 + 1` will result in `xxx71` which is probably not the desired outcome.

`new URL('/manga-tag/manga/page/' + (page + 1), this.url)`

File: src/web/mjs/connectors/AstralLibrary.mjs [hunk 3]
```diff
@@ -10,5 +10,28 @@ export default class AstralLibrary extends WordPressMadaraNovel {
...
+        let data = await this.fetchDOM(request, this.queryMangas);
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element.querySelector('.list-chapter a'), request.url),
```
Comment (27136773) [inline src/web/mjs/connectors/AstralLibrary.mjs]: This will get a link to the latest chapter instead of the manga and may interfere with bookmarked mangas (bookmarks are not detected, bookmarks will never find new chapters, ...).

I suggest to keep the manga list as is and not implement a hack just to bypass the bug on the website...

File: src/web/mjs/connectors/AstralLibrary.mjs [hunk 4]
```diff
@@ -10,5 +10,28 @@ export default class AstralLibrary extends WordPressMadaraNovel {
...
+                title: element.querySelector('a').textContent.trim()
+            };
+        });
+    }
+
+    async _getChapters(manga) {
+        let chap = manga.id.match(/(\d+)\/$/)[1]
```
Comment (27136773) [inline src/web/mjs/connectors/AstralLibrary.mjs]: Use the original `manga.id` and get the latest chapter number on the fly instead.
```javascript
const uri = new URL(this.url);
uri.searchParams.set('post_type', 'wp-manga');
uri.searchParams.set('s', manga.title);
const request = new Request(uri, this.requestOption);
const data = await fetchDOM(request, 'div.latest-chap span.chapter a');
// from this point follow the same drill by generating the chapters from the latest chapter number ...
```

**Review by 27136773 — CHANGES_REQUESTED** [review]
I suggest to not overwrite the method to get the manga list.
Instead utilize the website search to find the manga in the `getChapters` method and extract the latest chapter number from there.
Also needs to fix the lint errors.

File: src/web/mjs/connectors/AstralLibrary.mjs (hunk 2 above)
Comment (27136773) [reply src/web/mjs/connectors/AstralLibrary.mjs]: Obsolete since this method should not be overwritten

File: src/web/mjs/connectors/AstralLibrary.mjs (hunk 3 above)
Comment (27136773) [reply src/web/mjs/connectors/AstralLibrary.mjs]: Obsolete since this method should not be overwritten

**Comment by Robonau** [comment]
i can't not overwrite the method to get the manga list.
the madara _getMangas dosnt work as they have removed /wp-admin/admin-ajax.php
if i don't overwrite it it will not give a manga list

and i figure if it needs to be done anyways i might as well do it in the _getMangasFromPage

**Comment by 27136773** [comment]
In that case it would be best to use the link to the manga instead of the link to a chapter

**Comment by Robonau** [comment]
> In that case it would be best to use the link to the manga instead of the link to a chapter
the link to the manga is literally useless, i would just be using the title to search and get the last chapter that way, it's the same thing with more network trafic

**Comment by Robonau** [comment]
nvm i didn't read the bookmark thing

**Review by 27136773 — APPROVED** [review]
Looks good
