### PR TITLE
FIX : Comic boost : handle encrypted Publus version

### LINKED ISSUE #5391: {comicブースト] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I tried refreshing after picking the comicブースト in the connector, but it didn't work.

**To Reproduce**
1. comicブースト
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] 6.1.7@554b0c

### PR DESCRIPTION
**Pull request by MikeZeDev**
* JSON is encrypted.  I use bookloader to do the job itself :D
* filename has to be calculated by the system. 
* "blocks" computing procedure has changed its "b0Q" now

I wasnt able to fully unobfuscate the "blocks computing" reliably, leading to random unscrambling errors.
So this code just let PUBLUS calculate the blocks itself. 

Fixes https://github.com/manga-download/hakuneko/issues/5391

### CODE REVIEW

File: src/web/mjs/connectors/ComicBoost.mjs [hunk 1]
```diff
@@ -13,32 +13,169 @@ export default class ComicBoost extends Publus {
...
-        });
+        }).filter(el => !el.id.includes('?coin=')); //exclude not accessible chapters
+    }
+
+    async _getPages(chapter) {
+
+        const script = `
+            new Promise((resolve, reject) => {
+                setTimeout(async () => {
+
```
Comment (27136773) [inline src/web/mjs/connectors/ComicBoost.mjs:63]: This method looks quite big, recommend to wrap this whole method body into a `try {...} catch(error) {  reject(error); }` block statement to ensure the promise correctly delivers an error (otherwise the error is ignored and the promise never finishes correctly)

**Review by 27136773 — APPROVED** [review]
