### PR TITLE
fixed pagination in manga ay

### LINKED ISSUE #2567: Manga Ay is missing chapters
Hi, 
Manga Ay is working, but we have a problem. 
The series link.
https://manga-ay.com/seriler/0

2020-11-02_224110_manga-ay com

 Please look this picture. There are 100 mangas per page. Program sees only first page. So only sees 100 manga. Can you fix it?

### PR DESCRIPTION
**Pull request by Robonau**
resolves #2567

### CODE REVIEW

File: src/web/mjs/connectors/MangaAy.mjs [hunk 1]
```diff
@@ -20,7 +20,19 @@ export default class MangaAy extends Connector {
     }
 
     async _getMangas() {
-        let request = new Request(new URL('/seriler', this.url), this.requestOptions);
+        let mangaList = [];
+        const request = new Request(new URL('/seriler', this.url), this.requestOptions);
+        const data = await this.fetchDOM(request, 'nav > ul > li:last-child > a');
+        const pageCount = parseInt(data[0].href.match(/(\d+)$/)[1]);
+        for(let page = 0; page <= pageCount; page+=100) {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaAy.mjs:27]: Cannot confirm that there are 100 mangas per page (i only see 47 overall), but i assume this was tested and confirmed

**Review by 27136773 — APPROVED** [review]
Looks good
