### PR TITLE
Piccoma : api change

### LINKED ISSUE #7113: [Piccoma FR] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Hello, 

I can't download or open chapters on Piccoma's connector, i have this message : "the chapter 'x' is neither public, nor purchased!'
I have this message on the free's chapters and on the purchased's chapters

For information, i use the 8.3.4 Nightly build

### To Reproduce

1. Name of connector = Piccoma FR
2. Name of manga (if connector update is working) : ex : "la nouvelle vie du mage blanc"
3. Name of chapter (if manga update is working) : free chapter = 1 or 2
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : 
Capture d'écran 2024-05-29 161411

Capture d'écran 2024-05-29 153730
Capture d'écran 2024-05-29 153753

Capture d'écran 2024-05-29 161516
Capture d'écran 2024-05-29 161555

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/7113

### CODE REVIEW

File: src/web/mjs/connectors/Piccoma.mjs [hunk 1]
```diff
@@ -111,10 +111,7 @@ export default class Piccoma extends Connector {
                 
                 try {
                     const pdata = window.__NEXT_DATA__ ?  __NEXT_DATA__.props.pageProps.initialState.viewer.pData : window._pdata_; //PiccomaFR VS JP
-                    if (!pdata) reject();
-                    if (!pdata.img) reject(); 
-                    
-                    const images = pdata.img
+                    const images = (pdata.img || pdata.contents)
```
Comment (27136773) [inline src/web/mjs/connectors/Piccoma.mjs]: The `??` null coalescing operator would probably be more expressive

**Review by 27136773 — APPROVED** [review]
