### PR TITLE
[Takeshobo] fix mangalist not working

### LINKED ISSUE #3483: [Takeshobo] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No list of the manga available from the frontpage.

**To Reproduce**

1. Storia Dash

No error messages in the console. It just stops.

**Screenshots**

image

Version 6.1.7

On the other hand, copy pasting the url of the manga directly works:

image

### PR DESCRIPTION
**Pull request by dodieboy**
fix #3483

### CODE REVIEW

File: src/web/mjs/connectors/templates/TakeShobo.mjs [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default class TakeShobo extends SpeedBinb {
         super.label = undefined;
         this.tags = [];
         this.url = undefined;
-        this.path = '/';
+        this.path = '/parts_sub_lineup.html';
```
Comment (27136773) [inline src/web/mjs/connectors/templates/TakeShobo.mjs:12]: Are `StoriaDash` and `WebcomicGamma` also working with the changed path?

Comment (dodieboy) [reply src/web/mjs/connectors/templates/TakeShobo.mjs:12]: yup, tested for all 3 connector that use Takeshobo and all work

**Review by 27136773 — APPROVED** [review]
Looks good
