### PR TITLE
FIX TCBScans: workaround for 404 errors

### LINKED ISSUE #6375: [<tcbscans>] Certain chapter downloads are not working.
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

1. Name of connector-https://tcbscans.com/
2. Name of manga My Hero Academia
3. Name of chapters- 264, 277,279,280,281,282,283,284,285
4. Error 404

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
1) Website changed url (unrelated)
2) They deliberately introduce missing junk pictures in popular manga chapters. 

Since they cant be distinguished by name pattern, we use another method ;)

Fixes https://github.com/manga-download/hakuneko/issues/6375

### CODE REVIEW

File: src/web/mjs/connectors/TCBScans.mjs [hunk 1]
```diff
@@ -45,7 +45,17 @@ export default class TCBScans extends Connector {
     async _getPages(chapter) {
         const uri = new URL(chapter.id, this.url);
         const request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, 'picture > source');
-        return data.map(x => x.src);
+        const data = await this.fetchDOM(request, 'picture > source');
+
+        //test if image really exists
+        const promiseArray = data.map(page=> new Promise((resolve, reject) =>{
```
Comment (Sheepux) [inline src/web/mjs/connectors/TCBScans.mjs]: This would flood the website with http requests on images.

Comment (MikeZeDev) [reply src/web/mjs/connectors/TCBScans.mjs]: If you have another way to know if an image exist without trying to download it please tell me. 🤷 

I would add that since they deliberatly add fake additional pictures to thwart Hakuneko downloading, its only a fair game.

Its a HEAD request, not a big deal tho.

Comment (Sheepux) [reply src/web/mjs/connectors/TCBScans.mjs]: I just meant to do it with a for loop so that the requests are sequentials and not done in parallel.

**Review by 27136773 — APPROVED** [review]
