### PR TITLE
ShonenJumpPlus: support pasting volume

### LINKED ISSUE #8160: [shonenjumpplus.com] is not working for comic volumes
### Disclaimer

- [x] I searched and confirm that the same or a similar issue could not be found in the list of [existing tickets](https://github.com/manga-download/hakuneko/issues?q=)
- [x] I read and confirm that the issue could not be addressed by following the topics listed in the [troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
- [x] I tested and confirm that the issue is also reproducible with the latest [Nightly Build](https://github.com/manga-download/hakuneko/releases/tag/nightly-20200705.1)
- [x] I confirm that the placeholder `%WEBSITE-NAME%` in this ticket's title was correctly replaced with the name of the broken website

### What kind of issue are you encountering?

Downloads aren't working

### Description

When trying to use the clipboard method to download the manga volume, it does not list the contents in the chapter panel for download,
Have had the issue each time I get a free volume test period, though the same appears to happen with purchased volumes (haven't bought, just not listed in that case).

The issue seems to be that the comic volumes to not return a list of entries in the feed, as opposed to series, so does not list the results.

Working series example:
Image

Response:
```
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:giga="https://gigaviewer.com">
    <title>少年ジャンプ＋（大人大戦）</title>
    <subtitle>&lt;毎週土曜更新&gt;正しい大人とは？浦島優太郎は父が残した言葉を胸に、自らに課した“大人憲法”を守りながら立派な大人を目指していた。しかし、その“大人憲法”が後に世界を大きく変えることに…。『左ききのエレン』原作者かっぴー先生新連載！評価がすべての監視社会に立ち向かうサバイバルドラマ、開幕――!! [JC2巻発売中]</subtitle>
    <updated>2025-09-05T15:00:00Z</updated>
    <id>jump_plus:series:17106567264648152072</id>
    <link href="https://shonenjumpplus.com/episode/17106567264648207234"/>
        <entry>
            <title>[第21話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17107094910082447693"/>
            <id>jump_plus:episode:17107094910082447693</id>
            <updated>2025-09-05T15:00:00Z</updated>                <giga:freeTermStartDate>2025-09-05T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17107094910082447693-e02a6cc953af16ea8354fc460ff6922f?1756871227" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第20話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17107094909893774215"/>
            <id>jump_plus:episode:17107094909893774215</id>
            <updated>2025-08-29T15:00:00Z</updated>                <giga:freeTermStartDate>2025-08-29T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17107094909893774215-30ab7b8996fb570ef9f92a424a4de0c7?1756276923" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第19話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567268201279772"/>
            <id>jump_plus:episode:17106567268201279772</id>
            <updated>2025-08-22T15:00:00Z</updated>                <giga:freeTermStartDate>2025-08-22T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567268201279772-313a4e71496959e46e70f2927c0a1353?1755668340" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第18話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267988286369"/>
            <id>jump_plus:episode:17106567267988286369</id>
            <updated>2025-08-15T15:00:00Z</updated>                <giga:freeTermStartDate>2025-08-15T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267988286369-6ec8afca5579b11b8f54c09cc21f4ea9?1755057456" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第17話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267987414415"/>
            <id>jump_plus:episode:17106567267987414415</id>
            <updated>2025-08-08T15:00:00Z</updated>                <giga:freeTermStartDate>2025-08-08T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267987414415-1e80a7dd0df51e26bda0cfcb00fac12a?1754472490" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[休載イラスト2]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267815815641"/>
            <id>jump_plus:episode:17106567267815815641</id>
            <updated>2025-08-01T15:00:00Z</updated>                <giga:freeTermStartDate>2025-08-01T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267815815641-5d9e31d5272a8652da23c6a51c1982b1?1753943799" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第16話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267558209272"/>
            <id>jump_plus:episode:17106567267558209272</id>
            <updated>2025-07-25T15:00:00Z</updated>                <giga:freeTermStartDate>2025-07-25T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267558209272-a507f3b5db85d4b2982b81355fa90b06?1753353301" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第15話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267387688692"/>
            <id>jump_plus:episode:17106567267387688692</id>
            <updated>2025-07-18T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267387688692-c5cf368eb249b2112f4ee3f2e9f223c6?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第14話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567267181001498"/>
            <id>jump_plus:episode:17106567267181001498</id>
            <updated>2025-07-11T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567267181001498-8080a91fe7f0e161d52a3dc9a76551f6?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第13話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266985757163"/>
            <id>jump_plus:episode:17106567266985757163</id>
            <updated>2025-07-04T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266985757163-abf5ea89042b1425bdac1ae01e3a4c6e?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[休載イラスト]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266795713573"/>
            <id>jump_plus:episode:17106567266795713573</id>
            <updated>2025-06-27T15:00:00Z</updated>                <giga:freeTermStartDate>2025-06-27T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266795713573-5b78b39c5db3d4240e9ab97a1e9486e9?1750905397" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第12話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266627684231"/>
            <id>jump_plus:episode:17106567266627684231</id>
            <updated>2025-06-20T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266627684231-5f99580b37062d2597aa73be2074f1e0?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第11話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266456453206"/>
            <id>jump_plus:episode:17106567266456453206</id>
            <updated>2025-06-13T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266456453206-d20111a9e1c1e0d47779d035c21ba258?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第10話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266289404201"/>
            <id>jump_plus:episode:17106567266289404201</id>
            <updated>2025-06-06T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266289404201-171150888b5e47b877a89452f56550c9?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第9話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567266123221184"/>
            <id>jump_plus:episode:17106567266123221184</id>
            <updated>2025-05-30T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567266123221184-32550c0b86b28ddfecf4bc7af2c36f94?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第8話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265952706865"/>
            <id>jump_plus:episode:17106567265952706865</id>
            <updated>2025-05-23T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265952706865-3d9f9468b9fb7fcb62d5bffba42e7a77?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第7話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265642186024"/>
            <id>jump_plus:episode:17106567265642186024</id>
            <updated>2025-05-16T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265642186024-98e5a404b6e4eb079d33cedafc3d5944?1756866955" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第6話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265435708925"/>
            <id>jump_plus:episode:17106567265435708925</id>
            <updated>2025-05-09T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265435708925-3512b06f7db4368835589d42de254d5c?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第5話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265435707126"/>
            <id>jump_plus:episode:17106567265435707126</id>
            <updated>2025-05-02T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265435707126-53d86202e336c7eeb0904733304ef8f6?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第4話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265233237146"/>
            <id>jump_plus:episode:17106567265233237146</id>
            <updated>2025-04-25T15:00:00Z</updated>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265233237146-449b182344a9f4f1861704819a0f6e87?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第3話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567265033403569"/>
            <id>jump_plus:episode:17106567265033403569</id>
            <updated>2025-04-18T15:00:00Z</updated>                <giga:freeTermStartDate>2025-04-18T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567265033403569-0a7a549c745aae28160945d6d534ef5e?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第2話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567264824162787"/>
            <id>jump_plus:episode:17106567264824162787</id>
            <updated>2025-04-11T15:00:00Z</updated>                <giga:freeTermStartDate>2025-04-11T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567264824162787-cd7baf1382fe5a65fa3aeae568fdb41d?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
        <entry>
            <title>[第1話]大人大戦</title>
            <link href="https://shonenjumpplus.com/episode/17106567264648207234"/>
            <id>jump_plus:episode:17106567264648207234</id>
            <updated>2025-04-04T15:00:00Z</updated>                <giga:freeTermStartDate>2025-04-04T15:00:00Z</giga:freeTermStartDate>            <content type="html">大人大戦</content>
            <link rel="enclosure" href="https://cdn-ak-img.shonenjumpplus.com/public/episode-thumbnail/17106567264648207234-2970baec8690274369a181f5aeb532e1?1751859898" length="0" type="image/jpeg" />
            <author><name>かっぴー/都築真佐秋</name></author>
        </entry>
</feed>
```
Non working volume example:
Image

Response:
Image

```
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:giga="https://gigaviewer.com">
    <title>少年ジャンプ＋（ギンカとリューナ【期間限定試し読み増量】）</title>
    <subtitle>※2025年9月17日までの期間限定お試し版です。2025年9月18日以降はご利用できなくなります。【『魔都精兵のスレイブ』最新刊発売記念！　ストロングビューティーな女傑マンガ大特集！】雪深い山奥で、一人逞しく生きる子ども・リューナ。ある日、家に帰ると、動いて話す謎の雪だるまが…。彼の名はギンカ。帽子とマフラーをもらった恩返しにリューナが憧れる魔術師になるための修行を請け負う。やがて二人は山を飛び出し、冒険の旅へと出発！　最強の二人が贈るマジカルノマドファンタジー開幕!!</subtitle>
    <updated>2025-09-05T15:00:00Z</updated>
    <id>jump_plus:series:17107094910082556874</id>
    <link href=""/>
</feed>
```
Purchase only:
Image

The comics show a plaintext response that isn't on any that work correctly:
Image

```
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:giga="https://gigaviewer.com">
    <title>少年ジャンプ＋（大人大戦）</title>
    <subtitle></subtitle>
    <updated>2025-09-05T15:00:00Z</updated>
    <id>jump_plus:series:17106567265642992833</id>
    <link href=""/>
</feed>
```

### How can this be reproduced?

1. Start HakuNeko
2. Copy link for desired volume.
3. Click paste clipboard function.
4. Select manga from Manga List window.
5. See there are no chapter listings to download.

### PR DESCRIPTION
**Pull request by yuba64**
Fixes #8160

added volume to conditional for _getChapters

### CODE REVIEW

File: src/web/mjs/connectors/ShonenJumpPlus.mjs [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default class ShonenJumpPlus extends CoreView {
     }
 
     async _getChapters(manga) {
-        if(/^\/magazine\/\d+$/.test(manga.id)) {
+        if(/^\/magazine\/\d+$/.test(manga.id) || /^\/volume\/\d+$/.test(manga.id)) {
```
Comment (MikeZeDev) [inline src/web/mjs/connectors/ShonenJumpPlus.mjs]: No need for 2 Regexp when you can use one.

`/^(one|two|three)\/\d+$/ `

**Review by MikeZeDev — CHANGES_REQUESTED** [review]

File: src/web/mjs/connectors/ShonenJumpPlus.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/ShonenJumpPlus.mjs]: Keep in mind that its just a band-aid patch. RSS feed is kinda inaccurate now. https://github.com/manga-download/haruneko/pull/1181

**Comment by MikeZeDev** [comment]
Please provide an url so we can test pasting.

**Comment by yuba64** [comment]
> Please provide an url so we can test pasting.

This should work as an example:
https://shonenjumpplus.com/volume/17106567265642992994

There is also this one which is free so can be downloaded too:
https://shonenjumpplus.com/volume/17107094910082557397

File: src/web/mjs/connectors/ShonenJumpPlus.mjs (hunk 1 above)
Comment (yuba64) [reply src/web/mjs/connectors/ShonenJumpPlus.mjs]: Thank you, I have made a new commit with the syntax you included here.
Please see my other comment for some links to example volumes.

**Review by MikeZeDev — APPROVED** [review]
