### PR TITLE
Properly remove control codes chars from download path

### LINKED ISSUE #6718: [Bug][cxc] chapter eorror/ [Question] hakuneko function question
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**

chapter information:

  {
    "connectorID": "cxc",
    "mangaID": "/store/31/book/4383",
    "chapterID": "/store/31/book/4383/chapter/14376",
    "chapterTitle": "# 7 - DAY7: to / 去\b、給"
  }

This chapter can be viewed through the Preview Panel,but this chapter cannot be downloaded

**Expected behavior**
 this chapter can be downloaded

**Screenshots**

**Context (please complete the following information):**
Windows11
hakuneko-desktop_8.3.4_windows-portable_amd64

**Additional context**

### LINKED ISSUE #7004: [< Lezhin (English) > ] Unknown character, fail to download
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Unknown character (see screenshot, the "rectangle") appear in episode name in hakuneko web browser and episodes that have that character fail to be downloaded. Checked in chrome, there is no such character appear.

The episode is free for anyone to check.

in Hakuneko
Screenshot 2024-04-23 042020

in Chrome
Screenshot 2024-04-23 044604

### To Reproduce

1. Lezhin English
2. A World Without You
3. Epilogue - Season 1 Creator's Note (Free chapter)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6718
Fixes https://github.com/manga-download/hakuneko/issues/7004

### CODE REVIEW

File: src/web/mjs/engine/Storage.mjs [hunk 1]
```diff
@@ -778,20 +778,25 @@ export default class Storage {
     /**
```
Comment (27136773) [inline src/web/mjs/engine/Storage.mjs:778]: Comment can be removed since this sanitise is now no longer based on HakuNeko Legacy

**Review by 27136773 — APPROVED** [review]
