### PR TITLE
Website maintenance

### LINKED ISSUE #4453: [MangaHost] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I can't download/view the manga, but I can see the list of titles and their chapters. And there are also not all the titles like on the website.

**To Reproduce**
1. Name of connector: Mangá Host (current website: **mangahost4.com**; Registered in the Connectors list: mangahostz.com; Alternate website: mangahosted.com)
2. Name of manga (if connector update is working): Any title
3. Name of chapter (if manga update is working): Any chapter
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12):
I'll use 1 chapter of a title as an example.

`Connector.mjs:505 GET https://mangahost4.comhttps//mangahosted.com/manga/isekai-de-cheat-skill-wo…-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta-mh16822/14 net::ERR_NAME_NOT_RESOLVED`

`TypeError: Failed to fetch 
EventTarget {manga: EventTarget, id: "https://mangahosted.com/manga/isekai-de-cheat-skil…musou-suru-level-up-wa-jinsei-wo-kaeta-mh16822/14", title: "14", file: {…}, language: "pt", …}`

**Screenshots**
If complex to describe, add screenshots to help explain your problem:
Captura de tela 2022-03-03 mangahost4

**HakuNeko (please complete the following information):**
 - Version: 2022 HakuNeko rev. 6.1.7@cf569b

### LINKED ISSUE #4457: [Team X] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The website domain was changed so now we cant view anything

**To Reproduce**
1. Name of connector : Team X 
2. It shows this in the console GET https://www.teamxmanga.com/manga/page/1/ 404

**Website new urls**
- Site: https://teamx.fun/
- Manga List: https://teamx.fun/manga/
- Manga example: https://teamx.fun/manga/solo_max_level_newbie/
- Chapter online viewer example: https://teamx.fun/57bzax/

**HakuNeko (please complete the following information):**
 - Version 6.1.7

### PR DESCRIPTION
**Pull request by Sheepux**

### CODE REVIEW

File: src/web/mjs/connectors/MangaHost.mjs [hunk 1]
```diff
@@ -28,73 +39,50 @@ export default class MangaHost extends Connector {
...
-        this.fetchRegex(request, /<img\s+id='img_\d+'\s+src='(.*?)'/g)
-            .then(data => {
-                callback(null, data);
-            })
-            .catch(error => {
-                console.error(error, chapter);
-                callback(error, undefined);
-            });
+    async _getPages(chapter) {
+        console.log(chapter.id);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaHost.mjs]: Production code should not dump debug information

File: src/web/mjs/connectors/MangaHost.mjs [hunk 2]
```diff
@@ -28,73 +39,50 @@ export default class MangaHost extends Connector {
...
+        const data = await this.fetchDOM(mangaPageLinks[index], 'a.manga-block-title-link', 5);
+
+        let mangaList = data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
+                title: element.text.trim()
+            };
+        });
+        if (index < mangaPageLinks.length - 1) {
+            return this._getMangaListFromPages(mangaPageLinks, index + 1)
```
Comment (27136773) [inline src/web/mjs/connectors/MangaHost.mjs]: To prevent `Maximum call stack size exceeded` error, it is recommend to use a [loop](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/%40Samples.mjs#L50) for too many calls.

File: src/web/mjs/connectors/MangaHost.mjs [hunk 3]
```diff
@@ -9,6 +9,17 @@ export default class MangaHost extends Connector {
         super.label = 'MangaHost';
         this.tags = ['manga', 'portuguese'];
         this.url = 'https://mangahostz.com';
+
+        this.config = {
+            throttle: {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaHost.mjs]: The magic key `throttle` will also be used by the downloader to delay image downloads by the given value. If not intended the property shoild be renamed to something else.

File: src/web/mjs/connectors/MangaHost.mjs (hunk 2 above)
Comment (Sheepux) [reply src/web/mjs/connectors/MangaHost.mjs]: original code :\ didn't rework much. I guess i'll have to clean someone else code :'(

File: src/web/mjs/connectors/MangaHost.mjs (hunk 1 above)
Comment (Sheepux) [reply src/web/mjs/connectors/MangaHost.mjs]: Edit: woops

**Review by 27136773 — APPROVED** [review]
