### PR TITLE
Allanimesite : Change url and fixes

### LINKED ISSUE #5552: [AllAnime] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
AllAnime changed URL from .site to .to

**To Reproduce**
1. Name of connector AllAnime
2. Name of manga (if connector update is working) NA
3. Name of chapter (if manga update is working) NA
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/5552

### CODE REVIEW

File: src/web/mjs/connectors/Allanimesite.mjs [hunk 1]
```diff
@@ -37,40 +35,71 @@ export default class Allanimesite extends Connector {
...
         }
         return mangaList;
     }
     async _getMangasFromPage(page) {
-        const uri = new URL(this.path + this.varQueryMangas.replace('%PAGE%', page), this.url);
+
+        const jsonVariables = {
+            search : {
+                isManga : true,
+                allowAdult : false,
```
Comment (27136773) [inline src/web/mjs/connectors/Allanimesite.mjs]: Why not allow adult, i like adult stuff 😢

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/Allanimesite.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/Allanimesite.mjs]: Like i said in comments, apparently some variables doesnt seems to have consequences on search results.
I tried to increase manga / animes per pages, api doesnt care.

Well, gonna set adult and unknown to true since it doesnt seems to cause errors.
