### PR TITLE
[Mangapark] Fix Mangapark connector

### LINKED ISSUE #3981: Mangapark & Mangadex issues
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The chapter list of both Mangapark and Mangadex are empty, with exception of already downloaded manga.
They both work fine in the actual site, however - and I can find the manga in the list, it simply says "chapters 0/0" in both MangaPark.org and MangaDex

**Screenshots**
If no downloads

If downloaded
**HakuNeko (please complete the following information):**
 - Version 6.1.7

### LINKED ISSUE #4475: [MangaPark] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I'm looking to download the French and English chapters of Tsuredure Children, for example https://mangapark.net/comic/16009/tsuredure-children/c1-fr which is a working URL.

However, the manga doesn't even appear in the list when refreshing the connector.

If I attempt to use part of the URL above such as https://mangapark.net/comic/16009 using the Paste feature in Hakuneko, a manga named "Tsuredure Children" does appear in the list, but when clicking it the chapter list is empty.

Side-note, the MangaPark (mangapark.net) connector should have the Multilingual and French tags, and the two other connectors named "MangaPark" seem dead - one website redirects to another manga site, and the other redirects to something completely unrelated.

**To Reproduce**
1. mangapark-en connector
4. There is no relevant error message in the console.

**HakuNeko:**
 - Version 6.17@cf569b

### PR DESCRIPTION
**Pull request by Druzai**
resolves #3981
resolves #4475

### CODE REVIEW

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 1]
```diff
@@ -21,71 +21,80 @@ export default class MangaParkEN extends Connector {
...
+
+    async _getMangasFromPage(page) {
+        const uri = new URL('/browse?sort=name&page=' + page, this.url);
+        const request = new Request(uri, this.requestOptions);
+        const data = await this.fetchDOM(request, '#subject-list div.item');
+        return data.map( element => {
+            const a = element.querySelector('a.fw-bold');
+            this.cfMailDecrypt(a);
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(a, request.url),
```
Comment (27136773) [inline src/web/mjs/connectors/MangaParkEN.mjs]: May extract the number directly from `a.pathname` since the full link is not really required

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 2]
```diff
@@ -21,71 +21,80 @@ export default class MangaParkEN extends Connector {
...
+                title: a.text.trim()
+            };
+        });
+    }
+
+    async _getChapters(manga) {
+        let chapterList = [];
+        const mangaId = manga.id.match(/\/(\d+)\/?/)[1];
```
Comment (27136773) [inline src/web/mjs/connectors/MangaParkEN.mjs]: Not needed in case `manga.id` already contains the correct ID (see previous comment)

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 3]
```diff
@@ -21,71 +21,80 @@ export default class MangaParkEN extends Connector {
...
+                    prevPos: page
+                }),
+                headers: {
+                    'Content-Type': 'application/json;charset=UTF-8'
+                }
             });
             const data = await this.fetchJSON(request);
-            const mangas = [...this.createDOM(data.html).querySelectorAll('div.item > div > a.fw-bold')].map(element => {
+            const chapters = [...this.createDOM(data.html).querySelectorAll('div.episode-item > div > a.chapt')].map(element => {
+                let lang = this.getRootRelativeOrAbsoluteLink(element, this.url).match(/c[\d.]+-(\w+)-i\d+/)[1];
```
Comment (27136773) [inline src/web/mjs/connectors/MangaParkEN.mjs]: May use `const link = this.getRootRelativeOrAbsoluteLink(element, this.url);` as intermediate variable, to prevent duplicated code

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/MangaParkEN.mjs (hunk 1 above)
Comment (Druzai) [reply src/web/mjs/connectors/MangaParkEN.mjs]: Fixed

File: src/web/mjs/connectors/MangaParkEN.mjs (hunk 2 above)
Comment (Druzai) [reply src/web/mjs/connectors/MangaParkEN.mjs]: Fixed

File: src/web/mjs/connectors/MangaParkEN.mjs (hunk 3 above)
Comment (Druzai) [reply src/web/mjs/connectors/MangaParkEN.mjs]: Fixed
