### PR TITLE
add ReadAllComics and fix ComicExtra domain

### LINKED ISSUE #6048: [Site Request] readallcomics.com
**Name of the website**
readallcomics.com

**Website urls (examples below)**
- Site: https://readallcomics.com/
- Manga List: 
- Manga example: 
- Chapter online viewer example: https://readallcomics.com/frank-frazettas-death-dealer-14-2023/

**Languages**
English

**Website relationship*
[If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").]
(https://readallmanga.com/)

**Additional details**
Add any other context details that you may have found (like template to reuse)

### PR DESCRIPTION
**Pull request by yoanhg421**
Add readallcomics.com connector
Change comicextra.org to comixextra.com

Closes https://github.com/manga-download/hakuneko/issues/6048

### CODE REVIEW

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
Fix lint errors

**Review by yoanhg421 — COMMENTED** [review]
Fixed all lint errors on latest commit

File: src/web/mjs/connectors/ReadAllComics.mjs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+export default class ReadAllComics extends Connector {
+    constructor() {
+        super();
+        super.id = 'readallcomics';
+        super.label = 'Read All Comics';
+        this.tags = ['comics', 'english'];
+        this.url = 'https://readallcomics.com';
+        this.requestOptions.headers.set('x-referer', this.url);
+    }
+
```
Comment (MikeZeDev) [inline src/web/mjs/connectors/ReadAllComics.mjs:13]: One may want to implement clipboard support, since its easy 

```
import Manga from '../engine/Manga.mjs';

    async _getMangaFromURI(uri) {
        const request = new Request(uri, this.requestOptions);
        const id = uri.pathname;
        const [ title ] = await this.fetchDOM(request, 'div.description-archive h1');
        return new Manga(this, id, title.textContent.trim());
    }
```

**Review by MikeZeDev — APPROVED** [review]
Add clipboard support and its ok.

Btw, Thanks for providing me a proper comic list, gonna add this to haruneko

File: src/web/mjs/connectors/ReadAllComics.mjs (hunk 1 above)
Comment (yoanhg421) [reply src/web/mjs/connectors/ReadAllComics.mjs:13]: Added the Copy Paste support and tested it.

Thank you.

**Comment by MikeZeDev** [comment]
Thanks for your contribution. Now, gonna add that to haru
