### PR TITLE
FIX Alphapolis: picture fallback

### LINKED ISSUE #6067: [alphapolis] Cannot download old comic
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Some old comic cannot download.

**To Reproduce**
When download from https://www.alphapolis.co.jp/manga/official/492000109
Except ep 8 and ep9 cannot download

**Expected behavior**
The image url show 403 but the comic can read from chrome.

**Screenshots**
Clipboard02sfdsafds

Clipboard03safdsdfsadf

**Context (please complete the following information):**
OS: Windows 11
HakuNeko Version: 6.17@513508

**Additional context**

### PR DESCRIPTION
**Pull request by MikeZeDev**
old manga doesnt have high res

Fixes https://github.com/manga-download/hakuneko/issues/6067

This fix is simple.

### CODE REVIEW

File: src/web/mjs/connectors/Alphapolis.mjs [hunk 1]
```diff
@@ -63,4 +67,18 @@ export default class Alphapolis extends Connector {
             };
         });
     }
+
+    async _handleConnectorURI(payload) {
+        let request = new Request(payload.hiresPicture, this.requestOptions);
```
Comment (Sheepux) [inline src/web/mjs/connectors/Alphapolis.mjs:72]: Should test if highres url is not null/empty before sending a request

Comment (MikeZeDev) [reply src/web/mjs/connectors/Alphapolis.mjs:72]: Its always filled. Its a replace so in worst case it would be the same than normalPicture.

**Review by Sheepux — APPROVED** [review]
