### PR TITLE
fix sukima

### LINKED ISSUE #3069: [Sukima] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://www.sukima.me/ broken.

### PR DESCRIPTION
**Pull request by Robonau**
resolves #3069
made the list more complete too

### CODE REVIEW

File: src/web/mjs/connectors/Sukima.mjs [hunk 1]
```diff
@@ -14,41 +14,51 @@ export default class Sukima extends Connector {
...
-
-                    for (const manga of pageContent.items) {
-                        mangas.push(
-                            {
-                                id: manga.title_code,
-                                title: manga.title_name
-                            }
-                        );
-                    }
+            uri = new URL(category.more_btn.link, this.url);
```
Comment (27136773) [inline src/web/mjs/connectors/Sukima.mjs:31]: It seems the `tag` is the real variable of interest and not the `uri`.
`let tag = new URL(category.more_btn.link, this.url).searchParams.get('tag');`

File: src/web/mjs/connectors/Sukima.mjs [hunk 2]
```diff
@@ -14,41 +14,51 @@ export default class Sukima extends Connector {
     }
 
     async _getMangas() {
-        let categorys = await this._fetchPOST('/api/book/v1/free/', '{"store":false,"genre":"0"}');
-
         let uri;
-        let pages;
-        let mangas = [];
+        let mangaList = [];
+        const pageContent = await this._fetchPOST('/api/v1/search/', JSON.stringify({
```
Comment (27136773) [inline src/web/mjs/connectors/Sukima.mjs:19]: May simplify the existing `_fetchPOST()` method to do the `JSON.stringify` of the body within the method itself, so it does not have to be done every time the method is called.

**Review by 27136773 — APPROVED** [review]
Looks good, minor improvments possible
