### PR TITLE
fixed Batoto _getPages

### LINKED ISSUE #2493: [Batoto] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Unable to add mangas from bato.to

**To Reproduce**
1. bato.to
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. The only errors are: 
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load bookmarks: Invalid bookmark list!
ClipboardConnector.mjs:66 CLIPBOARD: https://bato.to/series/79241 TypeError: Cannot read property 'querySelector' of undefined
    at Batoto._getMangaFromURI (AnyACG.mjs:35)

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version 6.17

### PR DESCRIPTION
**Pull request by Robonau**
from issues on discord
resolves #2493

### CODE REVIEW

File: src/web/mjs/connectors/Batoto.mjs [hunk 1]
```diff
@@ -18,13 +18,16 @@ export default class Batoto extends AnyACG {
...
         this.queryChapters = 'div.episode-list div.main a.visited';
-        this.queryPages = /images\s*=\s*(\[[^\]]+\])\s*;/g;
     }
 
     async _getPages(chapter) {
-        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
-        let data = await this.fetchRegex(request, this.queryPages);
-        data = Object.values(JSON.parse(data[0]));
+        let script = `
+            new Promise((resolve) => {
```
Comment (27136773) [inline src/web/mjs/connectors/Batoto.mjs]: May remove obsolete brackets `(resolve)`

File: src/web/mjs/connectors/Batoto.mjs [hunk 2]
```diff
@@ -18,13 +18,16 @@ export default class Batoto extends AnyACG {
...
+                resolve(images.map(data => JSON.parse(CryptoJS.AES.decrypt(server, batojs).toString(CryptoJS.enc.Utf8))+data))
```
Comment (27136773) [inline src/web/mjs/connectors/Batoto.mjs]: May improve script instead of doing an additional `.map`after `fetchUI`:
```javascript
new Promise(resolve => {
    const base = JSON.parse(CryptoJS.AES.decrypt(server, batojs).toString(CryptoJS.enc.Utf8));
    resolve(images.map(data => new URL(base + data, window.location.origin).href));
});
// ...
return Engine.Request.fetchUI(...);
```

**Comment by 27136773** [comment]
Should rename pull request, `fixed it proper` can mean nearly anything

**Review by 27136773 — APPROVED** [review]
Code looks good
