### PR TITLE
FIX DoujinDesu: domain change

### LINKED ISSUE #6125: [DouijinDesu] Domain Change
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Chapter list isn't refreshing because domain change to https://doujindesu.tv

### To Reproduce

1. DoujinDesu
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6125

### CODE REVIEW

File: src/web/mjs/connectors/DoujinDesu.mjs [hunk 1]
```diff
@@ -17,10 +17,6 @@ export default class DoujinDesu extends WordPressMangastream {
         this.querMangaTitleFromURI = 'section.metadata h1.title';
     }
 
-    canHandleURI(uri) {
-        return /doujindesu\.xxx|212\.32\.226\.234/.test(uri.hostname);
```
Comment (Sheepux) [inline src/web/mjs/connectors/DoujinDesu.mjs:21]: clipboard doesn't work anymore ?

**Review by Sheepux — APPROVED** [review]

File: src/web/mjs/connectors/DoujinDesu.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/DoujinDesu.mjs:21]: ?? this function was useful when we had more than one domain. Now its handled by default code and i guess it still works 🤷
