### PR TITLE
Maintenance for various new/existing websites

### LINKED ISSUE #2796: [Site Request] wbnovel
**Name of the website**
Wbnovel

**Website urls (examples below)**
- Site: https://wbnovel.com/
- Manga List: https://wbnovel.com/novel/
- Manga example: https://wbnovel.com/novel/chaotic-sword-god/
- Chapter online viewer example: https://wbnovel.com/novel/chaotic-sword-god/chapter-2166/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

### LINKED ISSUE #3246: [Site Request] mangapark v3 / mangapark dev
**Name of the website**
mangapark v3

**Website urls (examples below)**
- Site: https://v3.mangapark.net/
- Manga List: https://v3.mangapark.net/browse
- Manga example: https://v3.mangapark.net/comic/77581/i-got-a-cheat-ability-in-a-different-world-and-became-extraordinary-even-in-the-real-world
- Chapter online viewer example: https://v3.mangapark.net/chapter/2618992

**Languages**
English

**Website relationship*
mangapark.net

**Additional details**
since some manga / uploader sometime only post on this dev site instead mangapark.net

### LINKED ISSUE #3248: [Site Request] kumotran
**Name of the website**
kumotran

**Website urls (examples below)**
- Site: https://www.kumotran.com
- Manga List: https://www.kumotran.com/manga/?genres_collapse=on
- Manga example: https://www.kumotran.com/manga/list-of-villains
- Chapter online viewer example: https://www.kumotran.com/manga/list-of-villains/51

**Languages**
Thai

Template
WordPressMadara

Thanks :)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

### LINKED ISSUE #3258: [Site Request] lianscans
**Name of the website**
lianscans

- Site: https://www.lianscans.my.id/
- Manga List: https://www.lianscans.my.id/manga-list/
- Manga example: https://www.lianscans.my.id/series/watashi-no-tomodachi-ga-sekaiichi-kawaii/
- Chapter online viewer example: https://www.lianscans.my.id/watashi-no-tomodachi-ga-sekaiichi-kawaii-chapter-08-bahasa-indonesia/

**Languages**
Indonesia

### LINKED ISSUE #3263: [Tritinia Scans] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector Tritinia Scans
2. Name of manga (if connector update is working) Doesn't show anything
3. Name of chapter (if manga update is working) Doesn't show anything
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
Untitled111111

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3270: [Site Request] Softkomik
**Name of the website**
Softkomik

**Website urls (examples below)**
- Site: https://softkomik.site/
- Manga List: https://softkomik.site/komik/list
- Manga example: https://softkomik.site/worn-and-torn-newbie-bahasa-indonesia
- Chapter online viewer example: https://softkomik.site/worn-and-torn-newbie-bahasa-indonesia/chapter/037

**Languages**
Indonesia

### PR DESCRIPTION
**Pull request by 27136773**

### CODE REVIEW

File: src/web/mjs/connectors/Genkan.mjs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+export default class Genkan extends Connector {
+
+    constructor() {
+        super();
+        super.id = 'genkan';
+        super.label = 'Genkan';
+        this.tags = [ 'webtoon', 'english' ];
+        this.url = 'https://genkan.io';
+        this.links = {
```
Comment (XenonR) [inline src/web/mjs/connectors/Genkan.mjs:12]: Unused object should be removed.

File: src/web/mjs/connectors/Genkan.mjs [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+        const data = await this.fetchDOM(request, 'a.relative > div.absolute > p.font-bold');
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element.closest('a'), this.url),
+                title: element.textContent.trim()
+            };
+        });
+    }
+
+    async _getChapters(manga) {
```
Comment (XenonR) [inline src/web/mjs/connectors/Genkan.mjs:45]: This implementation does not handle multiple chapter pages. Eg. https://genkan.io/manga/2829584385-the-great-mage-returns-after-4000-years

File: src/web/mjs/connectors/Genkan.mjs [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+        return data.map(element => {
+            const id = this.getRootRelativeOrAbsoluteLink(element.querySelector('td:nth-of-type(6) a'), this.url);
+            const number = element.querySelector('td:nth-of-type(1)').textContent.trim().padStart(4, '0');
+            const title = element.querySelector('td:nth-of-type(2)').textContent.replace(/^\s*-\s*$/, '').trim();
+            const language = element.querySelector('td:nth-of-type(3)').textContent.trim();
+            const scanlator = element.querySelector('td:nth-of-type(4)').textContent.trim();
+            return {
+                id: id,
+                title: `${number}${title ? ' - ' + title : ''} (${language}) [${scanlator}]`,
+                language: language
```
Comment (XenonR) [inline src/web/mjs/connectors/Genkan.mjs:68]: I thought `language` should be ISO 3166-1 alpha 2. If so it would be better to drop it.

File: src/web/mjs/connectors/Genkan.mjs [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+            };
+        });
+    }
+
+    async _getPages(chapter) {
+        const uri = new URL(chapter.id, this.url);
+        const request = new Request(uri, this.requestOptions);
```
Comment (XenonR) [inline src/web/mjs/connectors/Genkan.mjs:75]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/KumoTran.mjs [hunk 5]
```diff
@@ -0,0 +1,14 @@
+import WordPressMadara from './templates/WordPressMadara.mjs';
+
+export default class KumoTran extends WordPressMadara {
+
+    constructor() {
+        super();
+        super.id = 'kumotran';
+        super.label = 'KumoTran';
+        this.tags = [ 'manga', 'webtoon', 'thai' ];
+        this.url = 'https://www.kumotran.com';
```
Comment (XenonR) [inline src/web/mjs/connectors/KumoTran.mjs:10]: Cannot test `Cloudflare  Error 1020`. Geo blocked?

File: src/web/mjs/connectors/LianScans.mjs [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+    constructor() {
+        super();
+        super.id = 'lianscans';
+        super.label = 'LIAN';
+        this.tags = [ 'manga', 'indonesian', 'scanlation' ];
+        this.url = 'https://www.lianscans.my.id';
+        this.path = '/manga-list/';
+
+        this.querMangaTitleFromURI = 'div.series-title h2';
+        this.queryMangas = 'div.mangalist-blc ul li.Manga a.series';
```
Comment (XenonR) [inline src/web/mjs/connectors/LianScans.mjs]: CSS selector should be `div.mangalist-blc ul li a.series`, otherwise doesn't capture all mangas.

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+    constructor() {
+        super();
+        super.id = 'softkomik';
+        super.label = 'Softkomik';
+        this.tags = [ 'manga', 'indonesian' ];
+        this.url = 'https://softkomik.site';
+        this.api = 'https://img.softkomik.online/api/';
+        this.cdn = 'https://cdn.statically.io/img/softkomik.online/';
+        this.links = {
```
Comment (XenonR) [inline src/web/mjs/connectors/SoftKomik.mjs:14]: Unused object should be removed.

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 8]
```diff
@@ -1,130 +1,76 @@
...
-            } )
-            .then( data => {
-                callback( null, data );
-            } )
-            .catch( error => {
-                console.error( error, this );
-                callback( error, undefined );
-            } );
+    async _getChapters(manga) {
+        const uri = new URL(manga.id, this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/MangaParkEN.mjs:46]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 9]
```diff
@@ -1,130 +1,76 @@
...
+                setTimeout(() => {
+                    try {
+                        resolve(app.items.map(item => item.isrc));
+                    } catch(error) {
+                        reject(error);
+                    }
+                }, 2500);
+            });
+        `;
+        const uri = new URL(chapter.id, this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/MangaParkEN.mjs:72]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+        let mangaList = [];
+        for (let page = 1, run = true; run; page++) {
+            const mangas = await this._getMangasFromPage(page);
+            mangas.length > 0 ? mangaList.push(...mangas) : run = false;
+        }
+        return mangaList;
+    }
+
+    async _getMangasFromPage(page) {
+        const uri = new URL('komik-list?page=' + page, this.api);
```
Comment (XenonR) [inline src/web/mjs/connectors/SoftKomik.mjs:36]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+        return data.DaftarKomik.data.map(entry => {
+            return {
+                id: entry.title_slug,
+                title: entry.title.trim()
+            };
+        });
+    }
+
+    async _getChapters(manga) {
+        const uri = new URL('lihat-komik/' + manga.id, this.api);
```
Comment (XenonR) [inline src/web/mjs/connectors/SoftKomik.mjs:48]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+        return data.DataChapter.map(entry => {
+            return {
+                id: entry.chapter,
+                title: entry.chapter
+            };
+        });
+    }
+
+    async _getPages(chapter) {
+        const uri = new URL(`baca-chapter/${chapter.manga.id}&${chapter.id}`, this.api);
```
Comment (XenonR) [inline src/web/mjs/connectors/SoftKomik.mjs:60]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 13]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-     * e.g. Bypass CloudFlare protection
-     * _initializeConnector() {
-     * let uri = new URL( this.url );
-     * let request = new Request( uri.href, this.requestOptions );
-     * return Engine.Request.fetchUI( request, '' );
-     * }
-     */
+    // May overwrite the default initiaslization in case some custom stuff needs to be done ...
+    async _initializeConnector() {
+        const uri = new URL(this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:16]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 14]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-     * } )
-     * .catch( error => {
-     * console.error( error, this );
-     * callback( error, undefined );
-     * } );
-     * }
-     */
+    // Must overwrite the method to extract the manga list from the website
+    async _getMangas() {
+        const uri = new URL('/manga-list', this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:35]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 15]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-                        language: ''
-                    };
-                } );
-                callback( null, chapterList );
-            } )
-            .catch( error => {
-                console.error( error, manga );
-                callback( error, undefined );
-            } );
+    // A variation that will iterate through a multi-page manga list (with abort condition)
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:46]: May remove commented section, but i guess you want to keep it as "documentation".

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 16]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-     * .then( data => {
-     * callback( null, data );
-     * } )
-     * .catch( error => {
-     * console.error( error, manga );
-     * callback( error, undefined );
-     * } );
-     * }
-     */
+    // A variation that will iterate through a multi-page manga list (with page number limit)
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:58]: May remove commented section, but i guess you want to keep it as "documentation".

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 17]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-                let pageList = data.map( element => this.getAbsolutePath( element, request.url ) );
-                callback( null, pageList );
-            } )
-            .catch( error => {
-                console.error( error, chapter );
-                callback( error, undefined );
-            } );
+    // Must overwrite the method to extract the chapter list from the website
+    async _getChapters(manga) {
+        const uri = new URL(manga.id, this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:91]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/templates/@Samples.mjs [hunk 18]
```diff
@@ -7,202 +8,105 @@ export default class Samples extends Connector {
...
-     * return this.fetchDOM( request, 'div#image source' )
-     * .then( data => super._handleConnectorURI( this.getAbsolutePath( data[0], request.url ) ) );
-     * }
-     */
+    // The chapter list may also be multi-paged and therefore the same variations as for the manga list scraping may be used as well
+
+    // Must overwrite the method to extract the page list from the website (image links)
+    // NOTE: All <img> tags are replaced with <source> tags when using fetchDOM, consider this in the CSS query
+    async _getPages(chapter) {
+        const uri = new URL(chapter.id, this.url);
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/@Samples.mjs:107]: `uri` may be build directly in Request.

File: src/web/mjs/connectors/LezhinEN.mjs [hunk 19]
```diff
@@ -1,19 +1,16 @@
 import Lezhin from './templates/Lezhin.mjs';
```
Comment (XenonR) [inline src/web/mjs/connectors/LezhinEN.mjs:1]: Error after selecting preview on an manga:
```
ReferenceError: __LZ_PRODUCT__ is not defined
    at <anonymous>:6:40 EventTarget {connector: LezhinEN, id: "bjalex_en", title: "BJ Alex", status: "available", chapterCache: Array(0), …}```

File: src/web/mjs/connectors/LezhinJA.mjs [hunk 20]
```diff
@@ -1,19 +1,16 @@
 import Lezhin from './templates/Lezhin.mjs';
```
Comment (XenonR) [inline src/web/mjs/connectors/LezhinJA.mjs:1]: Error after selecting preview on an manga:
```
TypeError: Cannot read property 'scrollsInfo' of undefined
 at <anonymous>:10:60 EventTarget {manga: EventTarget, id: "1", title: "01 - １話", file: {…}, language: "ja-JP", …}```

File: src/web/mjs/connectors/LezhinKO.mjs [hunk 21]
```diff
@@ -1,19 +1,16 @@
 import Lezhin from './templates/Lezhin.mjs';
```
Comment (XenonR) [inline src/web/mjs/connectors/LezhinKO.mjs:1]: Error after selecting preview on an manga:
```
ReferenceError: __LZ_PRODUCT__ is not defined
  at <anonymous>:6:40 EventTarget {connector: LezhinKO, id: "10carats", title: "10Carats", status: "available", chapterCache: Array(0), …}```

**Review by XenonR — CHANGES_REQUESTED** [review]
Please review the Lezhin comments/erros. Also lianscans needs a small change.

File: src/web/mjs/connectors/Genkan.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/connectors/Genkan.mjs:12]: Its public and used in the link list of the website
image

File: src/web/mjs/connectors/Genkan.mjs (hunk 3 above)
Comment (27136773) [reply src/web/mjs/connectors/Genkan.mjs:68]: Language is website specific and just used to fill the combobox for the chapter list.
It would be way too much work to convert each website specific language terminology to ISO codes.
image

File: src/web/mjs/connectors/KumoTran.mjs (hunk 5 above)
Comment (27136773) [reply src/web/mjs/connectors/KumoTran.mjs:10]: Not that i'm aware of, works from different countries for me
Germany, United States, Singapore, Australia, ...

File: src/web/mjs/connectors/LianScans.mjs (hunk 6 above)
Comment (27136773) [reply src/web/mjs/connectors/LianScans.mjs]: Cjhanhged in 5beda62a

File: src/web/mjs/connectors/SoftKomik.mjs (hunk 7 above)
Comment (27136773) [reply src/web/mjs/connectors/SoftKomik.mjs:14]: Used as public in website list

File: src/web/mjs/connectors/MangaParkEN.mjs (hunk 9 above)
Comment (27136773) [reply src/web/mjs/connectors/MangaParkEN.mjs:72]: I prefer leaving it separate for readability (nested composition) and debugging (variable watch).
Why nesting seems no problem for such short URLs, it might be unclear for the composition of longer URLs.
To be consistent i keep all URLs outside the `Request` constructor.
```javascript
// separate composition
const uri = new URL('/manga/list?page=' + page, this.url);
const request = new Request(uri, this.RequestOptions);
const data = await this.fetchDOM(request, 'div.mangas > a');

// nested composition
const data = await this.fetchDOM(new Request(new URL('/manga/list?page=' + page, this.url), this.RequestOptions), 'div.mangas > a');
```

File: src/web/mjs/connectors/SoftKomik.mjs (hunk 12 above)
Comment (27136773) [reply src/web/mjs/connectors/SoftKomik.mjs:60]: Prefer separation over nesting for readability and debugging.

File: src/web/mjs/connectors/templates/@Samples.mjs (hunk 13 above)
Comment (27136773) [reply src/web/mjs/connectors/templates/@Samples.mjs:16]: Prefer separation over nesting for readability and debugging.

File: src/web/mjs/connectors/templates/@Samples.mjs (hunk 14 above)
Comment (27136773) [reply src/web/mjs/connectors/templates/@Samples.mjs:35]: Prefer separation over nesting for readability and debugging.

File: src/web/mjs/connectors/templates/@Samples.mjs (hunk 16 above)
Comment (27136773) [reply src/web/mjs/connectors/templates/@Samples.mjs:58]: Yes, this file is supposed to be a (copy & paste) code snippet provider for creating new connectors from scratch.

File: src/web/mjs/connectors/templates/@Samples.mjs (hunk 18 above)
Comment (27136773) [reply src/web/mjs/connectors/templates/@Samples.mjs:107]: Prefer separation over nesting for readability and debugging.

File: src/web/mjs/connectors/LezhinEN.mjs (hunk 19 above)
Comment (27136773) [reply src/web/mjs/connectors/LezhinEN.mjs:1]: Improved error message in 26f14ce4
`Chapter requires Login`

File: src/web/mjs/connectors/Genkan.mjs (hunk 2 above)
Comment (27136773) [reply src/web/mjs/connectors/Genkan.mjs:45]: Add multi-page chapter support in 011a889e

File: src/web/mjs/connectors/LezhinJA.mjs (hunk 20 above)
Comment (27136773) [reply src/web/mjs/connectors/LezhinJA.mjs:1]: Cannot be reproduced and therefore nothing can be done from my end right now.
Maybe the timeout for the injected JavaScript is to short and it is evaluated before the website is initialized, but this is just a wild guess...

Comment (XenonR) [reply src/web/mjs/connectors/LezhinJA.mjs:1]: Yeah, seems to be a loading issue on my end.

**Review by XenonR — APPROVED** [review]
All good.
