### PR TITLE
[netease] add origin header, evaluating authorization

### LINKED ISSUE #389: Add support for Bilibili Comics
https://manga.bilibili.com

Separated from #388

### LINKED ISSUE #2043: [bilibili / NetEase Comic] Connector not working
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
unable to update manga list

**To Reproduce**
1. NetEase Comic
2. update not working

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [master (yesterday)]
the issue was first noted by SiliuS#4699 on the discord but he didn't open a ticket
also given as the comment says on #389 shouldn't the name be changed to "Bilibili Manga" from "NetEase Comic" as "NetEase Comic" no longe exists

### PR DESCRIPTION
**Pull request by 27136773**
Resolves #2043

### CODE REVIEW

File: src/web/mjs/connectors/NetEaseComic.mjs [hunk 1]
```diff
@@ -6,6 +6,7 @@ export default class NetEaseComic extends Connector {
     constructor() {
         super();
         super.id = 'neteasecomic';
+        // TODO: rename website?
```
Comment (XenonR) [inline src/web/mjs/connectors/NetEaseComic.mjs]: I would say yes if existing bookmarks don't break.

**Review by XenonR — APPROVED** [review]
Also looking good.

File: src/web/mjs/connectors/NetEaseComic.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/connectors/NetEaseComic.mjs]: Has been renamed. Only ID is critical because it will break all existing bookmarks, so it should not be changed.

**Comment by 27136773** [comment]
I cannot purchase a chapter due to Alipay only accept payments from China.
Therefore it cannot be verified if the chapter filtering correctly includes purchased chapters or not (after manual user login).
