### PR TITLE
FIX ReaperScans: domain change & fix get chapters

### LINKED ISSUE #6526: [<Reaper Scans>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Chapters not showing after URL change! you can see manhwa but you can't see chapters... idk why!
Capture

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6526

Reproduce code from Haruneko, way simpler.

### CODE REVIEW

File: src/web/mjs/connectors/ReaperScans.mjs [hunk 1]
```diff
@@ -27,80 +28,71 @@ export default class ReaperScans extends Connector {
...
         return mangaList;
     }
+
     async _getMangasFromPage(page) {
-        let uri = new URL(this.path + '?page='+page, this.url);
-        let request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, this.queryMangas);
+        const uri = new URL(this.path + '?page='+page, this.url);
+        const request = new Request(uri, this.requestOptions);
+        await this.wait(this.config.throttle.value);
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScans.mjs:45]: this double the throttling as it's also called from getMangas.
I suggest to remove it

File: src/web/mjs/connectors/ReaperScans.mjs [hunk 2]
```diff
@@ -27,80 +28,71 @@ export default class ReaperScans extends Connector {
...
-            chapters.length > 0 ? chapterList.push(...chapters) : run = false;
-            //update payload data using response data, for next fetch
-            requestdata.payload.serverMemo.checksum = data.serverMemo.checksum;
-            requestdata.payload.serverMemo.htmlHash = data.serverMemo.htmlHash;
-            requestdata.referrer = new URL(manga.id+"?page="+page, this.url).href;
-            requestdata.payload.serverMemo.data.page = page;
-            requestdata.payload.serverMemo.data.paginators.page = page;
-            requestdata.payload.updates[0].payload.params[0] = page+1;
+        const uri = new URL(manga.id, this.url);
+        const [ data ] = await this.fetchDOM(new Request(uri, this.requestOptions), 'main div[wire\\:id][wire\\:initial-data]');
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScans.mjs:57]: Use `data` instead of `[ data ]` ?

**Review by Sheepux — APPROVED** [review]

File: src/web/mjs/connectors/ReaperScans.mjs (hunk 2 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/ReaperScans.mjs:57]: Since fetchDOM returns an array, but we know there is only one element its more elegant than data[0] .
Nice interpolation trick i took for Ronny's code in Haruneko :)
