### PR TITLE
Changed MangaCeng to MangaXin

### LINKED ISSUE #2062: [Mangaceng] Connector not working
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site changed from : "https://mangaceng.com/"
to : "https://mangaxin.com/"

**To Reproduce**
1. Name of connector : Mangaceng
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by newaccforhc**
fixes #2062 
One issue: Pages are downloaded as .bin files..

### CODE REVIEW

File: src/web/mjs/connectors/Mangaxin.mjs [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import WordPressEManga from './templates/WordPressEManga.mjs';
+
+/**
+ *
```
Comment (27136773) [inline src/web/mjs/connectors/Mangaxin.mjs:4]: May remove empty comments

File: src/web/mjs/connectors/Mangaxin.mjs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+ */
+export default class MangaXin extends WordPressEManga {
+
+    /**
+     *
```
Comment (27136773) [inline src/web/mjs/connectors/Mangaxin.mjs:9]: May remove empty comments

File: src/web/mjs/connectors/Mangaxin.mjs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+     */
+    constructor() {
+        super();
+        super.id = 'mangaxin';
```
Comment (27136773) [inline src/web/mjs/connectors/Mangaxin.mjs]: The id changed, so users will loose all their bookmarks they made for `mangaceng` is this intended?

Comment (newaccforhc) [reply src/web/mjs/connectors/Mangaxin.mjs]: Yeah... The website itself changed everything (Including their logo).. So, it's as if the MangaCeng was shut down and then, a new website called MangaXin was started. I dealt it as if it was a new site.

Comment (27136773) [reply src/web/mjs/connectors/Mangaxin.mjs]: Bookmarks are probably still working and should be kept, therefore the ID should be `mangaceng`.

The ID is just a unique identifier with no relation to the website name, in fact it could be a random string as well. So there is no harm when it differs from the class or view name.

**Comment by newaccforhc** [comment]
@ronny1982 I forgot to tell... But, I have reverted the id back to `mangaceng`

**Review by 27136773 — APPROVED** [review]
Ready for merge
