### PR TITLE
Website Maintenance

### LINKED ISSUE #4042: [Manga-TR] Connector not working
The manga list is not coming.

### LINKED ISSUE #4044: [KissMangaWebsite] Connector not working
As title shows the KissMangaWebsite connector isnt working. No chapters of anything is being shown however names of mangas are. Keep getting the error "cannot read property href or undefined" when trying to synchronize.

### LINKED ISSUE #4066: [toptoon] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update and failed to fetch

**To Reproduce**
toptoon

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [v6.17]

### LINKED ISSUE #4071: [YugenMangas] Connector not working
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
The site changed its layout so it changed the manga orders, so it's not working in the program.

Updated Directory list URL:  https://yugenmangas.com/series/
Olded Directory list URL:         https://yugenmangas.com/manga/

Example of new manga info URL: https://yugenmangas.com/series/heroe-basura-de-clase-fff/
Example of old manga info URL : https://yugenmangas.com/manga/fff-class-trashero/

**To Reproduce**
1. YugenMangas
2. Name of manga (mangas doesn't appear)
3. Name of chapter (chapters doesn't appear)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
GET https://yugenmangas.com/manga/list-mode/ 404

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #4077: [manga18fx.com] can't view/download any chapter of any manga
**Did you read the troubleshooting guide**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Desktop client@rev. number**
Hakuneko 617@a8e80e

**Describe the bug**
Can't view/download any chapter of any manga. A prompt appears saying "There was no content found for 'Chapter X' make sure it is accessible (login, puchase, ...)!" Error log says "Uncaught (in promise) Error: Object has been destroyed"
Chapter list is updated. In web browser all chapters are accessible for free and without signing up requirement.

**Screenshots**
Screenshot_353.

### LINKED ISSUE #4078: [manga18.us] Connector changed website to manhuascan.us
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Redirected to manhuascan.us

**Describe the bug**
Chapter list doesn't show because of website change

**HakuNeko (please complete the following information):**
 - Version 617@a8e80e

### LINKED ISSUE #4091: [Manga-TR] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When I click the update button, icon spin. When icon stop spinning, nothing happen, Manga List is still empety.
Note: Clipboard is working.

**To Reproduce**
1. Manga-TR
2. Bypass CloudFlare-like DDOS-protection
3. Click update button
4. Connector update isn't working

**HakuNeko (please complete the following information):**
 - Version 6.17@a8e80e and master@2653c

### LINKED ISSUE #4115: [Reset] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Titles shows no chapters. Oddly, update works and title show, but no chapters. No CloudFlare issues.

**To Reproduce**
1. Name of connector - reset
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - None.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

Screen Shot 2021-11-02 at 11 40 57 AM

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #4126: [.asurascans.com] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
allows you to download, but the files are "corrupted" they add an image that says that I stole the manga from their site, and they put webp files that the cbz reader does not read, if you want to use it you have to unzip file by file and delete the image , and change the ones that were converted to webp, and redo the cbz

**To Reproduce**
1. .asurascans.com
2. The Dark Magician Transmigrates After 66666 Years and SSS-Class Gacha Hunter
3. It was tested with chapters from 1 to 10 and they all did the same (tested with both completely and does the same I will keep trying and adding but the problem seems to be general)

**HakuNeko 6.17]

### PR DESCRIPTION
**Pull request by 27136773**
Resolves #4042

### CODE REVIEW

File: src/web/mjs/connectors/TopToon.mjs [hunk 1]
```diff
@@ -15,39 +15,40 @@ export default class TopToon extends Connector {
...
             };
         });
     }
 
     async _getChapters(manga) {
         const request = new Request(new URL(manga.id, this.url), this.requestOptions);
-        const data = await this.fetchDOM(request, 'tr.episode_tr');
-        return data.map(ele => {
+        const data = await this.fetchDOM(request, 'div.episode_list ul a.episode-items');
+        return data.map(element => {
```
Comment (Sheepux) [inline src/web/mjs/connectors/TopToon.mjs:38]: Stay consistent, use "item" as line 27 (or the other way) :)

**Review by Sheepux — APPROVED** [review]
/LGTM

File: src/web/mjs/connectors/TopToon.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/connectors/TopToon.mjs:38]: Naming was by intention:
`element` => representing an HTML element from an HTML collection
`item` or `entry` => representing an object from a (json) array
