### PR TITLE
MangaSY : defeat WP Manga Protector

### LINKED ISSUE #5609: [Manga SY] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
None of the downloads seem to work.
The website is working.
I can retrieve a list of series, but downloading a chapter fails

**To Reproduce**
1. Manga SY
2. All manga have the same problem, but I'll pick the first as example, so select "7 Days Of Ecstatic Marriage"
3. Select "Chapter 1-Ecstatic"
4. Click the download button
  2 requests will be made:
  1 ?style=list
  2 chapter-1-ecstatic/
  It looks like something goes wrong here, it does not start downloading pictures
6. After a few seconds the download failed

**Screenshots**
These are the only errors I see in the console
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/5609

### CODE REVIEW

File: src/web/mjs/connectors/MangaSY.mjs [hunk 1]
```diff
@@ -11,4 +11,19 @@ export default class MangaSY extends WordPressMadara {
...
+
+    async _getPages(chapter) {
+        const url = new URL(chapter.id, this.url);
+        const request = new Request(url, this.requestOptions);
+        const script = `
+            new Promise((resolve, reject) => {
+                var imgdata = JSON.parse(CryptoJS.AES.decrypt(chapter_data, wpmangaprotectornonce, {
+                    format: CryptoJSAesJson
+                }).toString(CryptoJS.enc.Utf8));
+                resolve(imgdata);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaSY.mjs]: May perform `JSON.parse` inside the script itself, so the outer method can directly return the `FetchUI` invocation without awaiting the intermediate result.

**Review by 27136773 — APPROVED** [review]
