### PR TITLE
FIXES. Plenty of website fixes - Happy New Year

### LINKED ISSUE #4172: [Manhwas] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
They changed the property to show chapters on their website so when pasting a link the chapters are not displayed.
To solve the problem I change **queryChapters** and **queryPages**
solucion

**To Reproduce**
1. Name of connector - Manhwas

2. Name of manga (if connector update is working) - N/A
3. Name of chapter (if manga update is working) - N/A
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
error manhwasnet

**HakuNeko (please complete the following information):**
 - Version 6.1.7

### LINKED ISSUE #4268: https://skymanga.co/ site changed Chapter not downloading
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #4532: [Manga 347] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Titles and chapters not working. Refresh makes all titles disappear. I think site changed format.

**To Reproduce**
1. Name of connector - Manga 347
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) None.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
Screen Shot 2022-03-31 at 12 34 54 PM

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #4579: [boyslove] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector wont show manga list

**To Reproduce**
1. boyslove
2. "Didn't update"
4. "didn't update"
5. POST  https://boyslove.me/wp-admin/admin-ajax.php 502. (in the console)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@cf569b

### LINKED ISSUE #4652: [Hunterscan] Website URL changed
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No / yes [https://huntersscan.xyz/series/my-neighborhoods-female-teacher/]

**Describe the bug**
The webpage location changed... now it is https://huntersscan.xyz/

**To Reproduce**
1. Name of connecto
Hunterscan.

**HakuNeko (please complete the following information):**
 - Version [latest stable version of 06/05/22]

### LINKED ISSUE #4978: [earlymanga] Connector not working
Cant update manga list. Request get redirected many times until it lands on earlym.org

https://earlymanga.org/lazymore/manga-0  302 redirect into 
https://earlymangarelease.com/lazymore/manga-0  302 redirect into 
https://earlym.me/lazymore/manga-0  302 redirect into 
https://earlym.org/lazymore/manga-0 : JSON OUTPUT.

Maybe change the website url to earlym.org ? and check the json output

### LINKED ISSUE #4983: [mangaswat.co] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Hi, the domain of mangaswat.co has been changed to swatmanga.me. Please change the domain of the site in the program, thank you..

**To Reproduce**
1.  swatmanga.me
2. (https://swatmanga.me/manga/urban-fairy-king/)
3. [Name of chapter (if manga update is working)](https://swatmanga.me/1397691/%d8%a7%d9%84%d9%81%d8%b5%d9%84-167-urban-fairy-king/)
4. error no manga website.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #4994: [muctau] Website Url changed
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it works fine from the website/connectors list, but nothing happens after pasting the link

**To Reproduce**
1. Name of connector https://www.muctau.com/

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #5048: [https://reaperscans.com/] Connector not working/ Site is changed
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
They changed their website with the same domain name.

**To Reproduce**
1. Reaper Scans
2. Update connector (not working)

New Website Links:
Website: https://reaperscans.com/

Manga Section: https://reaperscans.com/comics
Manga Page: https://reaperscans.com/comics/5984-absolute-sword-sense
Manga Chapter: https://reaperscans.com/comics/5984-absolute-sword-sense/chapters/43757903-chapter-1

Novels Section: https://reaperscans.com/novels
Novel Page: https://reaperscans.com/novels/7019-21st-century-archmage
Novel Chapter: https://reaperscans.com/novels/7019-21st-century-archmage/chapters/51546995-chapter-190

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #5086: [kuaikanmanhua] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The last chapters published in kuaikanmanhua.com are not updated in HakuNeko, to avoid errors enter both in my browser and in the internal browser of HakuNeko and in both if the published chapters are seen, but when I put it to download, no update is displayed so I can not download it, and that applies to all series within kuaikanmanhua.com, I hope you can repair this error, I appreciate your attention and work.

**To Reproduce**
1. kuaikanmanhua
2. 从大树开始的进化
3. 15, 16
4. 

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**¿Ha leído [la guía de solución de problemas](https://hakuneko.download/docs/troubleshoot/)**
Sí

**¿Funciona bien la página web del conector / puedes ver el manga en tu navegador**?
Sí

**Describa el fallo
Los últimos capítulos publicados en kuaikanmanhua.com no se actualizan en HakuNeko, para evitar errores entra tanto en mi navegador como en el navegador interno de HakuNeko y en ambos si se ven los capítulos publicados, pero cuando lo pongo a descargar, no aparece ninguna actualización por lo que no puedo descargarlo, y eso se aplica a todas las series dentro de kuaikanmanhua.com, espero que puedan reparar este error, agradezco su atención y trabajo.

**Reproducir**
Pasos para reproducir el comportamiento:
1. kuaikanmanhua
2. 从大树开始的进化
3. 15, 16
4. 

**HakuNeko (por favor, complete la siguiente información):**
 - Versión [por ejemplo, 6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/4579, Fixes https://github.com/manga-download/hakuneko/issues/4978, Fixes https://github.com/manga-download/hakuneko/issues/5048, Fixes https://github.com/manga-download/hakuneko/issues/4268, Fixes https://github.com/manga-download/hakuneko/issues/4652, Fixes https://github.com/manga-download/hakuneko/issues/5181, Fixes https://github.com/manga-download/hakuneko/issues/5086, Fixes https://github.com/manga-download/hakuneko/issues/5153, Fixes https://github.com/manga-download/hakuneko/issues/5154, Fixes https://github.com/manga-download/hakuneko/issues/5151, Fixes https://github.com/manga-download/hakuneko/issues/4983 Fixes https://github.com/manga-download/hakuneko/issues/4532, Fixes https://github.com/manga-download/hakuneko/issues/4172, Fixes https://github.com/manga-download/hakuneko/issues/4994 , Fixes https://github.com/manga-download/hakuneko/issues/5191 Fixes https://github.com/manga-download/hakuneko/issues/5314

### CODE REVIEW

**Comment by Sheepux** [comment]
BlackSheep

**Comment by philipdistefano** [comment]
How do we use the updated mjs files?

**Comment by Sheepux** [comment]
you wait for the fix to be merged. And that's after i get time to review the PR.

**Comment by philipdistefano** [comment]
> you wait for the fix to be merged. And that's after i get time to review the PR.

Thank you for the reply!

File: src/web/mjs/connectors/KomikTap.mjs [hunk 1]
```diff
@@ -7,11 +7,11 @@ export default class KomikTap extends WordPressMangastream {
         super.id = 'komiktap';
         super.label = 'KomikTap';
         this.tags = [ 'manga', 'webtoon', 'hentai', 'indonesian' ];
-        this.url = 'https://komiktap.in';
+        this.url = 'https://92.87.6.124';
```
Comment (Sheepux) [inline src/web/mjs/connectors/KomikTap.mjs]: IP shouldn't be hardcoded, just initialize `this.url` in the contructor by checking the http redirect
Same for canHandleURI, should be able to dynamically include the url pattern with the IP found
The request class has some redirect features, not sure if it can help

File: src/web/mjs/connectors/PlotTwistNoFansub.mjs [hunk 2]
```diff
@@ -11,8 +9,47 @@ export default class PlotTwistNoFansub extends WordPressClarityMangaReader {
...
         };
-
         this.paths = [ '/proyectos-finalizados-new/', '/proyectos-activosss/' ];
         this.queryMangas = 'div.vc_gitem-zone a.vc_gitem-link';
     }
-}
\ No newline at end of file
+    async _getChapterList( manga, callback ) {
+        let uri = new URL( manga.id, this.url );
+        let request = new Request(uri.href, this.requestOptions );
```
Comment (Sheepux) [inline src/web/mjs/connectors/PlotTwistNoFansub.mjs]: strange mix of async & callback 
it should be async _getChapter (instead of list) and then just return

File: src/web/mjs/connectors/ReaperScans.mjs [hunk 3]
```diff
@@ -11,8 +10,142 @@ export default class ReaperScans extends WordPressMadara {
...
+                method: "gotoPage",
+                params: [
+                    2,
+                    "page"
+                ]
+            }
+        }
+        ];
+        return {
+            payload : wiredata, token :token, referrer : referrer};
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScans.mjs:134]: lint, missing new indented line before `}`

File: src/web/mjs/connectors/ReaperScans.mjs [hunk 4]
```diff
@@ -11,8 +10,142 @@ export default class ReaperScans extends WordPressMadara {
...
+            requestdata.payload.serverMemo.data.page = page;
+            requestdata.payload.serverMemo.data.paginators.page = page;
+            requestdata.payload.updates[0].payload.params[0] = page+1;
+            await this.wait(this.config.throttle.value);
+        }
+        return chapterList;
+    }
+    getChaptersFromDoc(doc) {
+        let chapterList = [];
+        //get chapters
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScans.mjs]: comment can be removed, function is self explained

File: src/web/mjs/connectors/ReaperScansBR.mjs [hunk 5]
```diff
@@ -1,15 +1,89 @@
...
+                title: element.querySelector('span.chapter-span.name').textContent.trim(),
+            };
+        });
+    }
+    async _getPages(chapter) {
+        let request = new Request(this.url + chapter.id, this.requestOptions);
+        let script = `
+        new Promise(resolve => {
+            let pages = __NEXT_DATA__;
+            resolve(pages);
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScansBR.mjs]: variable should be `const`, also the variable itself is not usefull here :)

File: src/web/mjs/connectors/kuaikanmanhua.mjs [hunk 6]
```diff
@@ -20,82 +20,70 @@ export default class Kuaikanmanhua extends Connector {
...
-            callback(null, chapterList);
-        } catch (error) {
-            console.error(error, manga);
-            callback(error, undefined);
+    async _getChapters(manga) {
+        let chapterList = await this.resolveChapterList(manga, 'comics');
+        if (chapterList.length < 1) {
+            chapterList = await this.resolveChapterList(manga, 'comicList');
         }
+        if (chapterList.length < 1) {
```
Comment (Sheepux) [inline src/web/mjs/connectors/kuaikanmanhua.mjs]: Duplicate if sequence, i'd push the  if within the other if (easier to read)
Also use an inline
`if (chapterList.length < 1) console.error('No chapters found !', this);`

File: src/web/mjs/connectors/kuaikanmanhua.mjs [hunk 7]
```diff
@@ -20,82 +20,70 @@ export default class Kuaikanmanhua extends Connector {
...
-                };
-            }).filter(chapter => chapter.id !== 'javascript:void(0);');
-            callback(null, chapterList);
-        } catch (error) {
-            console.error(error, manga);
-            callback(error, undefined);
+    async _getChapters(manga) {
+        let chapterList = await this.resolveChapterList(manga, 'comics');
+        if (chapterList.length < 1) {
+            chapterList = await this.resolveChapterList(manga, 'comicList');
```
Comment (Sheepux) [inline src/web/mjs/connectors/kuaikanmanhua.mjs]: I feel that those double calls should be done within a single call to resolveChapterList (in the fetchUI script . And then you can just write the call here)

File: src/web/mjs/connectors/kuaikanmanhua.mjs [hunk 8]
```diff
@@ -20,82 +20,70 @@ export default class Kuaikanmanhua extends Connector {
...
-        } catch (error) {
-            console.error(error, manga);
-            callback(error, undefined);
-        }
+            });
+            `;
+        let request = new Request(this.url + manga.id, this.requestOptions);
+        chapterList = await Engine.Request.fetchUI(request, script);
+
+        return chapterList;
```
Comment (Sheepux) [inline src/web/mjs/connectors/kuaikanmanhua.mjs]: unneeded variable `chapterList `? (the initial [] assignment is overwritten)
`return await Engine.Request.fetchUI(request, script);`

**Review by Sheepux — CHANGES_REQUESTED** [review]

File: src/web/mjs/connectors/PlotTwistNoFansub.mjs (hunk 2 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/PlotTwistNoFansub.mjs]: Its because the template is still old school code. Not sure something wont go wrong if i use new style.
Well, gotta rewrite it

File: src/web/mjs/connectors/ReaperScans.mjs (hunk 3 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/ReaperScans.mjs:134]: Lint processor (from the PR) says there is no pb.  Copied eslint rules from the repo and checked by myslef, and no pb on my end too.
I dont get it

File: src/web/mjs/connectors/PlotTwistNoFansub.mjs (hunk 2 above)
Comment (Sheepux) [reply src/web/mjs/connectors/PlotTwistNoFansub.mjs]: new style is just removing callback, add async in front, remove List from the function name  and using a return :)

File: src/web/mjs/connectors/ReaperScans.mjs (hunk 3 above)
Comment (Sheepux) [reply src/web/mjs/connectors/ReaperScans.mjs:134]: the closing bracket is not at the same level as the return, that's a code formating issue (lint), but it looks like it doesn't trigge rthe lint validator

Comment (Sheepux) [reply src/web/mjs/connectors/ReaperScans.mjs:134]:
```
        return {
            payload : wiredata, token :token, referrer : referrer};
```
to
```
        return {
            payload : wiredata, token :token, referrer : referrer
        };
```

File: src/web/mjs/connectors/KomikTap.mjs [hunk 9]
```diff
@@ -7,11 +7,19 @@ export default class KomikTap extends WordPressMangastream {
...
+    async _initializeConnector() {
+        const response = await fetch(this.url);
+        const newUrl = new URL(response.url);
+        this.url = newUrl.origin;
+        this.hostPattern = newUrl.host;
+        console.log(`Assigned URL '${this.url}' to ${this.label}`);
+    }
     canHandleURI(uri) {
-        return /komiktap\.in|194\.233\.66\.232|92\.87\.6\.124/.test(uri.hostname);
+        return new RegExp(this.hostPattern).test(uri.hostname);
```
Comment (Sheepux) [inline src/web/mjs/connectors/KomikTap.mjs]: host needs to be escaped before processing as a regexp as the dot is meaningfull :)
but ...
just use string.includes() without regexp.
Edit: ah the regexp was usefull for double domain matching ... using a double string.includes with an OR statement is probably the easier solution.

Comment (MikeZeDev) [reply src/web/mjs/connectors/KomikTap.mjs]: Using a string pattern, dots in ip or in host doesnt need to be escaped. 
Direct regex pattern (with /mypattern/) needs escaping.

I tested it before posting, but ill switch to includes. 
FYI, dual regexp 'komiktap\.in|194\.233\.66\.232' was recognised by clipboard but nothing worked with komiktap\.in urls in entered. Better just using only one host.

Comment (MikeZeDev) [reply src/web/mjs/connectors/KomikTap.mjs:23]: Hum, _initializeConnector isnt called before canHandleURI, so the host is not updated.
gotta have to do this

```
    canHandleURI(uri) {
        if (!this.initialized) super._initialize();
        return uri.href.includes(this.url);
    }
```

Comment (MikeZeDev) [reply src/web/mjs/connectors/KomikTap.mjs]: Used includes, and had to used async cause stuff is not always initializated before. Its better than calling initializate() and it works.

Comment (Sheepux) [reply src/web/mjs/connectors/KomikTap.mjs]: you cannot switch to async "just like that" :)
the connector code is using it as a synchronous call
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/system/ClipboardConnector.mjs#L51

Comment (MikeZeDev) [reply src/web/mjs/connectors/KomikTap.mjs]: You think it would be better to call initialize? fine then

Comment (Sheepux) [reply src/web/mjs/connectors/KomikTap.mjs]: lint error ;)

Comment (MikeZeDev) [reply src/web/mjs/connectors/KomikTap.mjs]: https://smallpetselect.com/wp-content/uploads/2016/06/bunniez.hubpages.com_.png

**Review by Sheepux — APPROVED** [review]
