### PR TITLE
FIx Toonkor : get domain from telegram

### LINKED ISSUE #6332: [<Toonkor>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

I noticed that Toonkor's URL is outdated. I was just wondering you guys could add the URL copy/paste, just like newtoki's. Thank you.

### To Reproduce

Currently, Toonkor is still active and I really wish to download the current new chapters and series that are there, thank you so much **_!_**

Toonkor is currently https://toonkor299.com

I would really like a feature like newtoki's where you can just copy/paste the URL.

Thanks _**!**_

### PR DESCRIPTION
**Pull request by MikeZeDev**
Avoid twitter shenanigans.

Fixes https://github.com/manga-download/hakuneko/issues/6332

### CODE REVIEW

File: src/web/mjs/connectors/Toonkor.mjs [hunk 1]
```diff
@@ -7,17 +7,32 @@ export default class Toonkor extends GnuBoard5BootstrapBasic2 {
...
-        let uri = new URL(await this._twitter.getProfileURL('1202224761771741184') || this.url);
-        let request = new Request(uri.href, this.requestOptions);
-        this.url = await Engine.Request.fetchUI(request, `window.location.origin`);
+        const script = `
+            new Promise((resolve, reject) => {
+                setTimeout(() => {
+                	  //fetch telegram messages with links, reverse it because last one is more recent one, and get the first matching our regex
+                    const tkLinks = [...document.querySelectorAll('section.tgme_channel_history div.tgme_widget_message_wrap .tgme_widget_message_text a ')].reverse();
+                    for (const link of tkLinks) {
+                        if ( ${this.hostRegexp}.test(link.href)) {
```
Comment (27136773) [inline src/web/mjs/connectors/Toonkor.mjs:25]: Interesting, wouldn't expect an RegExp to correctly work when interpolated inside a string

**Review by 27136773 — APPROVED** [review]
