### PR TITLE
Mangaz applyRealMime 

### LINKED ISSUE #3067: [LibraryZ (Mangaz)] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
https://www.mangaz.com/ work well when you want to grab last mangalist also preview just work well, but when you want to download chapters it grab bin files

### PR DESCRIPTION
**Pull request by Robonau**
resolves #3067

### CODE REVIEW

File: src/web/mjs/connectors/mangaz.mjs [hunk 1]
```diff
@@ -70,10 +70,12 @@ export default class Mangaz extends Connector {
         let decrypted = CryptoJS.AES.decrypt({ ciphertext: encrypted }, key, { iv: iv });
         decrypted = decrypted.toString(CryptoJS.enc.Utf8);
         decrypted = Uint8Array.from(atob(decrypted), char => char.charCodeAt(0));
-        return {
+        let data = {
```
Comment (27136773) [inline src/web/mjs/connectors/mangaz.mjs]: May re-use `decrypted` instead of introducing a new local variable `data`

**Review by 27136773 — APPROVED** [review]
Looks good
