### PR TITLE
Fix tapas.io connection

### LINKED ISSUE #7029: [Tapas.io] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

I'm unable to load the list of series from tapas. I've logged in through manual interaction (and it shows me as being logged in).

`Failed to update manga list for Tapas

Unexpected token < in JSON at position 0`

### To Reproduce

1. Tapas.io
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Connector.mjs:579 SyntaxError: Unexpected token < in JSON at position 0

### PR DESCRIPTION
**Pull request by Asriel2137**
Fixes #7029

### CODE REVIEW

**Comment by Asriel2137** [comment]
I didn't bother testing / updating the novel fetch, but I can if you want that too.

File: src/web/mjs/connectors/Tapas.mjs [hunk 1]
```diff
@@ -103,6 +76,7 @@ export default class Tapas extends Connector {
     }
 
     async _getPagesNovel(request) {
+        // Not updated since hakuneko doesn't support novels anyways.
```
Comment (MikeZeDev) [inline src/web/mjs/connectors/Tapas.mjs]: Novels are supported, otherwise this code wouldnt be here. People can copy paste novel url.

_getMangaFromURI (clipboard support) needs to be fixed so we can test that, even for manga only.

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
* Remove the "novels not supported" comment
* May want to fix clipboard support (_getMangaFromURI) too.

Suggested "how to" : https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/Tapas.ts#L53

Thanks anyway.

File: src/web/mjs/connectors/Tapas.mjs [hunk 2]
```diff
@@ -30,63 +31,35 @@ export default class Tapas extends Connector {
...
-                id: this.getRootRelativeOrAbsoluteLink(element.pathname, this.url),
-                title: element.dataset.tiaraEventMetaSeries.trim()
+                id: element.seriesId,
+                title: element.title
             };
         });
     }
 
     async _getChapters(manga) {
         let chapterList = [];
```
Comment (MikeZeDev) [inline src/web/mjs/connectors/Tapas.mjs]: remove unused variable

File: src/web/mjs/connectors/Tapas.mjs (hunk 1 above)
Comment (Asriel2137) [reply src/web/mjs/connectors/Tapas.mjs]: tested and it seems to work after implementing clipboard support

File: src/web/mjs/connectors/Tapas.mjs [hunk 3]
```diff
@@ -14,11 +14,16 @@ export default class Tapas extends Connector {
...
 
     async _getMangaFromURI(uri) {
-        let request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, 'div.info a.title');
-        let id = uri.pathname;
-        let title = data[0].textContent.trim();
-        return new Manga(this, id, title);
+        let spliced_url = (await this.fetchDOM(new Request(uri), 'meta[property="al:android:url"]'))[0].content.split('/')
+        // title can be in two formats: tapas/series/<series_name> or tapas/series/<series_name>/info
+        let seriesId = (spliced_url[spliced_url.length - 1] == 'info' ? spliced_url[spliced_url.length-2] : spliced_url.pop())
```
Comment (MikeZeDev) [inline src/web/mjs/connectors/Tapas.mjs]: are you sure the meta url can get the /info at the end?

**Review by MikeZeDev — APPROVED** [review]

File: src/web/mjs/connectors/Tapas.mjs (hunk 3 above)
Comment (Asriel2137) [reply src/web/mjs/connectors/Tapas.mjs]: Yes, I had the issue while testing.

Comment (MikeZeDev) [reply src/web/mjs/connectors/Tapas.mjs]: ok, ill have to fix that on my end too :D

No need for an intermediary variable btw.

`const seriesId = (await this.fetchDOM(new Request(uri), 'meta[property="al:android:url"]'))[0].content.replace(/\/info$/, '').split('/').pop();`

And perhaps there are some lint errors to fix 🤷

Comment (Asriel2137) [reply src/web/mjs/connectors/Tapas.mjs]: Did the first one, what kind of linter should I be using for ts?

Comment (MikeZeDev) [reply src/web/mjs/connectors/Tapas.mjs]: eslint. Integration should have displayed the errors but fixes are needed on CI. Gotta fix it myself if you cant anyway

**Comment by Sheepux** [comment]
Regression impact : bookmarks are not working anymore 
```
    "key": {
      "connector": "tapas",
      "manga": "/series/the-fantasie-of-a-stepmother"
    }

```
the key is now stroring an ID.

User issues storm are coming.

**Comment by MikeZeDev** [comment]
it cant be helped : Api dont give slugs anymore 
image

and manga list displays mangas as /series/ID now, not /series/slug so bookmarks would have been broken anyway.
