### PR TITLE
Fix TopToon : update CSS selectors

### LINKED ISSUE #6905: [TOPTOON] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

The chapter list is not imported.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6905

### CODE REVIEW

File: src/web/mjs/connectors/TopToon.mjs [hunk 1]
```diff
@@ -34,11 +34,11 @@ export default class TopToon extends Connector {
...
     async _getChapters(manga) {
         const request = new Request(new URL(manga.id, this.url), this.requestOptions);
-        const data = await this.fetchDOM(request, 'div.episode_list ul a.episode-items');
+        const data = await this.fetchDOM(request, 'div.eplist ul a.episode-items');
         return data.map(element => {
-            let title = element.querySelector('p.episode_title').textContent.trim();
-            const subtitle = element.querySelector('p.episode_stitle');
-            title += subtitle ? ' - ' + subtitle.textContent.trim() : '';
+            let title = element.querySelector('p.ep_title').textContent.trim();
+            const subtitle = element.querySelector('p.ep_stitle');
```
Comment (27136773) [inline src/web/mjs/connectors/TopToon.mjs:40]: Consider `element.querySelector('p.ep_stitle')?.textContent.trim()` to simplify the the following condition for ternary operator.

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/TopToon.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TopToon.mjs:40]: I am dumb, i cant get past the lint error

Comment (MikeZeDev) [reply src/web/mjs/connectors/TopToon.mjs:40]: I wont do that, because while nightly electron version support that syntax `element.querySelector('p.ep_stitle')?`, stable branch doesnt.  

The problem was first spotted on Tapytoon. Their login page use similar syntax, a user found people could login in nightly and not in stable branch because of that.
