### PR TITLE
[wordpress*] added / updated various template based websites

### LINKED ISSUE #2351: [KomikIndoWeb] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The chapter list is not displayed and maybe the download feature too(not work)

**To Reproduce**
1. Name of connector : KomikIndoWeb
2. Name of manga (if connector update is working) : 1 nen a gumi no monster
3. Name of chapter (doesn't work) 

**HakuNeko (please complete the following information):**
 - Version 8.3.4(nightly build with update of course)

### LINKED ISSUE #2352: [MangaKita] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't update the manga lists

**Screenshots**
mangakita

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2353: [kiryuu] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't show the chapter lists

**To Reproduce**
1. Name of connector : kiryuu
2. Name of manga (if connector update is working) : Jujutsu kaisen
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2354: [KomikAV] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't displayed chapter lists

**To Reproduce**
1. Name of connector : KomikAV
2. Name of manga (if connector update is working) : "4 cut hero"
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2355: [Ngomik] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't update the manga lists

**To Reproduce**
1. Name of connector : Ngomik
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
ngomik

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #2356: [Shea Manga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
1. I don't know if this will have an effect, but the site is seem changed url
from : "https://www.sheamanga.my.id" to "https://sheamanga.my.id
2. Can't update the manga list

**To Reproduce**
1. Name of connector : Shea Manga
2. Name of manga (if connector update is working) : Not working
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by 27136773**
References: dazedcat19/FMD2#113
References: fmd-project-team/FMD#1134

### CODE REVIEW

File: src/web/mjs/connectors/Kiryuu.mjs [hunk 1]
```diff
@@ -8,10 +8,11 @@ export default class Kiryuu extends WordPressMangastream {
         super.label = 'Kiryuu';
         this.tags = [ 'manga', 'indonesian' ];
         this.url = 'https://kiryuu.co';
-        this.path = '/manga/?list';
+        this.path = '/manga/list-mode/';
 
-        this.queryChapters = 'div.bxcl ul li span.lchx a';
-        this.queryPages = 'div#readerarea > :not(.kln) source[src]:not([src=""])';
+        this.querMangaTitleFromURI = 'div#content div.postbody article h1.entry-title';
```
Comment (XenonR) [inline src/web/mjs/connectors/Kiryuu.mjs]: Line seems redundant. The result is the same as `div#content div.postbody article h1` which is the templates default value.

File: src/web/mjs/connectors/templates/WordPressMangastream.mjs [hunk 2]
```diff
@@ -34,9 +35,10 @@ export default class WordPressMangastream extends Connector {
         let data = await this.fetchDOM(request, this.queryChapters);
         return data.map(element => {
             this.adLinkDecrypt(element);
+            const title = this.queryChaptersTitle ? element.querySelector(this.queryChaptersTitle).textContent : element.text;
             return {
                 id: this.getRootRelativeOrAbsoluteLink(element, request.url),
-                title: element.text.replace(manga.title, '').trim(),
+                title: title.replace(manga.title, '').trim(),
                 language: ''
```
Comment (XenonR) [inline src/web/mjs/connectors/templates/WordPressMangastream.mjs]: May remove unused attribute.

File: src/web/mjs/connectors/KomikAV.mjs [hunk 3]
```diff
@@ -1,21 +1,17 @@
...
         super();
         super.id = 'komikav';
         super.label = 'KomikAV';
         this.tags = [ 'manga', 'indonesian' ];
         this.url = 'https://komikav.com';
-        this.path = '/manga/?list';
+        this.path = '/manga/list-mode/';
 
-        this.queryChapters = 'div.bxcl ul li span.lchx a';
+        this.querMangaTitleFromURI = 'div#content div.postbody article h1.entry-title';
```
Comment (XenonR) [inline src/web/mjs/connectors/KomikAV.mjs]: Line seems redundant. The result is the same as `div#content div.postbody article h1` which is the templates default value.

File: src/web/mjs/connectors/KomikIndoWeb.mjs [hunk 4]
```diff
@@ -1,19 +1,39 @@
...
         super();
         super.id = 'komikindoweb';
         super.label = 'KomikIndoWeb';
         this.tags = [ 'manga', 'webtoon', 'indonesian' ];
-        this.url = 'https://www.komikindo.web.id';
-        this.path = '/daftar-komik/?list';
+        this.url = 'https://komikindo.web.id';
+        this.path = '/manga/?page=';
+
+        this.querMangaTitleFromURI = 'div#content div.postbody article h1.entry-title';
```
Comment (XenonR) [inline src/web/mjs/connectors/KomikIndoWeb.mjs]: Line seems redundant. The result is the same as `div#content div.postbody article h1` which is the templates default value.

File: src/web/mjs/connectors/SheaManga.mjs [hunk 5]
```diff
@@ -1,58 +1,17 @@
...
-                if(pages && pages.length) {
-                    resolve(pages);
-                } else {
-                    resolve([...document.querySelectorAll('div.entry-content div.separator img')].map(img => img.src));
-                }
-            });
-        `;
-        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
-        return await Engine.Request.fetchUI(request, script);
+        this.querMangaTitleFromURI = 'div#content div.postbody article h1.entry-title';
```
Comment (XenonR) [inline src/web/mjs/connectors/SheaManga.mjs]: Line seems redundant. The result is the same as `div#content div.postbody article h1` which is the templates default value.

File: src/web/mjs/engine/Connector.mjs [hunk 6]
```diff
@@ -419,6 +419,7 @@ export default class Connector {
         if( clearIframettributes ) {
             content = content.replace( /<iframe[^<]*?>/g, '<iframe>');
         }
+        content = content.replace(/<\/?noscript>/g, '');
```
Comment (XenonR) [inline src/web/mjs/engine/Connector.mjs:422]: I can see the removal of `noscript` tags, but why is it needed?

**Review by XenonR — APPROVED** [review]
Works very well. Minor redundancy's. Why the `noscript` removal?

File: src/web/mjs/engine/Connector.mjs (hunk 6 above)
Comment (27136773) [reply src/web/mjs/engine/Connector.mjs:422]: Any HTML tags inside the `noscript` tags are not parsed as DOM nodes, instead `noscript` is a text node containing the plain HTML code. In short one of the websites (Kiryuu) used this and to counter it the `noscript` wrapper is removed to expose the contained HTML text and parse it as DOM nodes.

File: src/web/mjs/connectors/Kiryuu.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/connectors/Kiryuu.mjs]: Template uses `h1` instead of `h1.entry-title`, not sure if it is safe to add `h1.entry-title` to template, but i guess the `.entry-title` class can be skipped anyway

File: src/web/mjs/connectors/KomikAV.mjs (hunk 3 above)
Comment (27136773) [reply src/web/mjs/connectors/KomikAV.mjs]: Removed

File: src/web/mjs/connectors/SheaManga.mjs (hunk 5 above)
Comment (27136773) [reply src/web/mjs/connectors/SheaManga.mjs]: Removed

File: src/web/mjs/connectors/KomikIndoWeb.mjs (hunk 4 above)
Comment (27136773) [reply src/web/mjs/connectors/KomikIndoWeb.mjs]: Removed

File: src/web/mjs/connectors/templates/WordPressMangastream.mjs (hunk 2 above)
Comment (27136773) [reply src/web/mjs/connectors/templates/WordPressMangastream.mjs]: Removed
