### PR TITLE
ComicFUZ : fix decryption

### LINKED ISSUE #5502: [COMIC FUZ] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't download manga on this site even episode 1 is free.

**To Reproduce**
1. Select COMIC FUZ
2. Select some manga (ex. 魔女は満月に咲く https://comic-fuz.com/manga/3226)
3. Select some free episode
4. Download failed and appear (failed) net::ERR_NOT_IMPLEMENTED at dev tool

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version master@23fcb9

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Replaced crypto.subtle (unsupported in our engine version) by CryptoJS equivalent.
* Fixed mime type for unencrypted pictures (so we dont download .bin files)
* Fixes https://github.com/manga-download/hakuneko/issues/5502

### CODE REVIEW

File: src/web/mjs/connectors/ComicFuz.mjs [hunk 1]
```diff
@@ -114,4 +126,20 @@ export default class ComicFuz extends Connector {
         const request = await this._createPROTORequest(uri, requestType, payload);
         return this.fetchPROTO(request, this.protoTypes, responseType);
     }
-}
\ No newline at end of file
+
+    convertWordArrayToUint8Array (wordArray) {
+        var len = wordArray.words.length,
```
Comment (27136773) [inline src/web/mjs/connectors/ComicFuz.mjs:131]: Is it possible to just change the `ArrayView` of the underlying byte buffer?
`return new Uint8Array(new Uint32Array(wordArray.words).buffer);`

Comment (27136773) [reply src/web/mjs/connectors/ComicFuz.mjs:131]: nvm. just tried it in browser and it seems the endianess does not match the words in CryptoJS (bytes for each word are reversed)

**Review by 27136773 — APPROVED** [review]
