### PR TITLE
Add Tenshi.moe & DDoss-Guard fix

### LINKED ISSUE #5347: [Site Request] Tenshi.moe
**Name of the website**
(https://tenshi.moe/)

**Website urls (examples below)**
- Site: https://tenshi.moe/
- Manga List: https://tenshi.moe/anime
- Manga example: https://tenshi.moe/anime/dcrer4o9
- Chapter online viewer example: https://tenshi.moe/anime/dcrer4o9/1

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Nice alternative to 9anime with self hosted videos, nothing complicated.
* Had to handle DdoSS Guard, not a big deal.
* Fixes https://github.com/manga-download/hakuneko/issues/5347

### CODE REVIEW

**Comment by 27136773** [comment]
Icon is too large, should not exceed ~16KB

File: src/web/mjs/connectors/TenshiMoe.mjs [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+        this.config = {
+            format: {
+                label: 'Language Settings',
+                description: 'Choose between Subbed or Dubbed anime. If your choice is not available the other is used as fallback',
+                input: 'select',
+                options: [
+                    { value: 'SUB', name: 'Subbed' },
+                    { value: 'DUB', name: 'Dubbed' }
+                ],
+                value: ''
```
Comment (27136773) [inline src/web/mjs/connectors/TenshiMoe.mjs]: Shouldn't the value be one of the available options?

File: src/web/mjs/connectors/TenshiMoe.mjs [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+                    { value: '720', name: '720p' },
+                    { value: '1080', name: '1080p' }
+                ],
+                value: ''
+            }
+        };
+
+    }
+    async _initializeConnector() {
+        //bypass DdoSS Guard
```
Comment (27136773) [inline src/web/mjs/connectors/TenshiMoe.mjs]: Probably better to update [Request.mjs](https://github.com/manga-download/hakuneko/blob/1e5953e4d189ded736a50d8bf9b96520aa4c3d6b/src/web/mjs/engine/Request.mjs#L138-L142) so it works for all websites

File: src/web/mjs/connectors/TenshiMoe.mjs [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+        const request = new Request(this.url, this.requestOptions);
+        const script = `
+        new Promise((resolve, reject) => {
+            setTimeout(() => {
+                    resolve();
+            },7000); //wait to let DG set its cookies
+        });
+        `;
+        await Engine.Request.fetchUI(request, script, 300000, true); //need image support, DG script loads a fake image
```
Comment (27136773) [inline src/web/mjs/connectors/TenshiMoe.mjs]: Is `300000` by intention or a typo? 5 Minutes is quite the long timeout.

File: src/web/mjs/connectors/TenshiMoe.mjs [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+
+    async _getPages(chapter) {
+        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, 'ul.dropdown-menu a');
+        let sourceUrl = '';
+        if (data.length == 1) {
+            sourceUrl = data;
+        } else {
+            sourceUrl = this.findPreferedLanguage(data);
+            if(!sourceUrl) sourceUrl = data[0];
```
Comment (27136773) [inline src/web/mjs/connectors/TenshiMoe.mjs]: Considere ternary operator `sourceUrl = sourceUrl ? sourceUrl : data[0];`
Doesn't `findPreferedLanguage` already return `data[0]` as default anyway?

File: src/web/mjs/connectors/TenshiMoe.mjs [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+        }
+
+        let uri = new URL(sourceUrl);
+        const videoid = uri.searchParams.get('v');
+        uri = new URL('/embed', this.url);
+        uri.searchParams.set('v', videoid);
+        request = new Request(uri, this.requestOptions);
+        data = await this.fetchDOM(request, 'video source');
+        let video = data.find(element => element.getAttribute('size') == this.config.resolution.value);
+        if (!video) video = data [0];
```
Comment (27136773) [inline src/web/mjs/connectors/TenshiMoe.mjs]: Consider ternary operator

File: src/web/mjs/connectors/TenshiMoe.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TenshiMoe.mjs]: I merely did like other connectors and It seems this doesnt pose a problem as i make sure to return something you are right.

File: src/web/mjs/connectors/TenshiMoe.mjs (hunk 2 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TenshiMoe.mjs]: Exactly, i was wondering where to make the change tbh. 
The thing is the default initialization call fetchui with no image support and i am pretty sure its necessary.

From Connector.mjs
```
    async _initializeConnector() {
        let uri = new URL(this.url);
        let request = new Request(uri.href, this.requestOptions);
        return Engine.Request.fetchUI(request, '');
    }
```
There is nothing we can do at request level if we dont fix that. Should this fetchui call have a image = true ? (and a default timeout because of parameters numbers)? 

Edit : Yeah, without pics support, infinite loop 
image

File: src/web/mjs/connectors/TenshiMoe.mjs (hunk 3 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TenshiMoe.mjs]: typo

File: src/web/mjs/connectors/TenshiMoe.mjs (hunk 4 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TenshiMoe.mjs]: Yeah, turn out i am extra cautious for nothing.

File: src/web/mjs/connectors/TenshiMoe.mjs (hunk 2 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/TenshiMoe.mjs]: Done.

**Review by 27136773 — APPROVED** [review]

**Comment by 27136773** [comment]
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27tenshimoe%27&type=code)
