### PR TITLE
[WorldRomanceTranslation] Fix connector

### LINKED ISSUE #3578: [WorldRomanceTranslation] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
A clear and concise description of what the bug is the chapter didn't appear from hakuneko

**To Reproduce**
1. Name of connector --> https://wrt.my.id/
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Kappamalone**
Fix #3578. The website slightly changed the html structure used in the WordPressMangastream template, causing it to break.

### CODE REVIEW

File: src/web/mjs/connectors/WorldRomanceTranslation.mjs [hunk 1]
```diff
@@ -1,13 +1,26 @@
...
         super.label = 'World Romance Translation';
-        this.tags = [ 'manga', 'indonesian' ];
+        this.tags = ['manga', 'indonesian'];
         this.url = 'https://wrt.my.id';
         this.path = '/manga/list-mode/';
+
+        this.queryChapters = 'div#chapterlist ul li div.eph-num';
+    }
+
+    async _getChapters(manga) {
```
Comment (27136773) [inline src/web/mjs/connectors/WorldRomanceTranslation.mjs]: Is it possible to define a chapter query that does not require to overwriting the method?
e.g.
```javascript
this.queryChapters = 'div#chapterlist ul li div.eph-num a:last-of-type';
```

Comment (Kappamalone) [reply src/web/mjs/connectors/WorldRomanceTranslation.mjs]: I wasn't really familiar with pseudo selectors so I didn't think of this. Your solution works like a charm, so I'll keep it in mind for future fixes.

**Review by 27136773 — APPROVED** [review]
Looks good
