### PR TITLE
website maintenance

### LINKED ISSUE #3334: [Site Request] Mangahua
**Name of the website**
MangaHua

**Website urls (examples below)**
- Site: https://mangahua.com/
- Manga List: (maybe) https://mangahua.com/genres
- Manga example: https://mangahua.com/manga/parallel-paradise-raw-22718
- Chapter online viewer example: https://mangahua.com/manga/parallel-paradise-raw/chapter-151/879473
- 
**Languages**
The site is in English

**Website relationship*
No known

**Additional details**
No known

### LINKED ISSUE #3335: [Site Request] Land Webtoons
**Name of the website**
Land Webtoons

**Website urls**
- Site: https://landwebtoons.site/
- Manga List: https://landwebtoons.site/manga/
- Manga example: https://landwebtoons.site/manga/dreams/
- Chapter online viewer example: https://landwebtoons.site/manga/dreams/capitulo-1/

**Languages**
Portuguese

**Template**
WordPressMadara

### LINKED ISSUE #3336: [MangaKawaii](french) Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector is not working, List of mangas appears but chapters doesn't appear in the list, the connector seems to be dead.
Original website : https://www.mangakawaii.com/
see more in screenshots.

**To Reproduce**
1. MangaKawaii
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
No error message.

**Screenshots**
https://zupimages.net/viewer.php?id=21/15/2m6o.jpg
https://zupimages.net/viewer.php?id=21/15/u2u0.jpg

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 - My HakuNeko version : 2021 HakuNeko rev 6.1.7@845bf9

### LINKED ISSUE #3337: [mangapark] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
finds the manga but the chapters aren't showing up. the chapter list stays empty only for manga from this site

**To Reproduce**
1. Name of connector - mangapark.net
2. Name of manga (if connector update is working) -any/all
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
- HakuNeko version : 2021 HakuNeko rev 6.1.7@845bf9

### PR DESCRIPTION
**Pull request by 27136773**

### CODE REVIEW

File: src/web/mjs/connectors/MangaParkEN.mjs [hunk 1]
```diff
@@ -45,16 +45,38 @@ export default class MangaParkEN extends Connector {
...
+            .filter(folder => folder.iid)
+            .reduce(async (accumulator, folder) => {
+                const req = new Request(this.url + '/ajax.reader.subject.episodes.folder', {
+                    method: 'POST',
+                    body: `{"iid":${folder.iid}}`,
+                    headers: {
+                        'Content-Type': 'application/json;charset=UTF-8'
+                    }
+                });
+                const foo = await this.fetchJSON(req);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaParkEN.mjs]: Variable name is not expressive

**Review by Sheepux — APPROVED** [review]
