### PR TITLE
[9ekor] Connector not working #2451

### LINKED ISSUE #2451: [9ekor] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't update the manga lists. maybe chapters list & download feature not work too

**To Reproduce**
1. Name of connector = 9ekor
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)

### PR DESCRIPTION
**Pull request by Robonau**
resolves #2451

### CODE REVIEW

File: src/web/mjs/connectors/NineEkor.mjs [hunk 1]
```diff
@@ -13,15 +13,15 @@ export default class NineEkor extends Connector {
 
     async _getMangaFromURI(uri) {
         let request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, 'div.page-head h1.page-title');
-        let id = uri.pathname.split('page/')[0];
+        let data = await this.fetchDOM(request, 'main.site-main header.page-header h1.entry-title');
+        let id = uri;
```
Comment (27136773) [inline src/web/mjs/connectors/NineEkor.mjs]: Do not use absolute URL, except the website uses cross-domain links
`uri.pathname`

File: src/web/mjs/connectors/NineEkor.mjs [hunk 2]
```diff
@@ -31,20 +31,8 @@ export default class NineEkor extends Connector {
...
-        let data = await this.fetchDOM(request, 'div.pagination > a.last');
-        let pageCount = data.length === 0 ? 1 : parseInt(data[0].href.match(/page\/(\d+)\//)[1]);
-        for(let page = 1; page <= pageCount; page++) {
-            let chapters = await this._getChaptersFromPage(manga, page);
-            chapterList.push(...chapters);
-        }
-        return chapterList;
-    }
-
-    async _getChaptersFromPage(manga, page) {
```
Comment (27136773) [inline src/web/mjs/connectors/NineEkor.mjs:45]: Seems they really dropped chapter pagination, but now tons of chapters are missing on the website (e.g. https://9ekor.com/berserk/).
Guess it cannot be helped, so removing pagination is probably the correct decision.

File: src/web/mjs/connectors/NineEkor.mjs [hunk 3]
```diff
@@ -56,7 +44,8 @@ export default class NineEkor extends Connector {
 
     async _getPages(chapter) {
         let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
-        let data = await this.fetchDOM(request, 'div#all source');
+        let data = await this.fetchDOM(request, 'main.site-main div.page-content p source');
+        console.log(data)
```
Comment (27136773) [inline src/web/mjs/connectors/NineEkor.mjs]: Do not log data in production

**Review by 27136773 — APPROVED** [review]
Looks good
