### PR TITLE
FIX AllHentai: change domain and some CSS

### LINKED ISSUE #6303: [AllHentai] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

AllHentai changed the address to https://24.allhen.online/

### To Reproduce

1. Name of connector: AllHentai
2. -
3. -
4. -
Version Nightly

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6303

Also added delay because i got clearly timeouted while getting manga pages

### CODE REVIEW

File: src/web/mjs/connectors/AllHentai.mjs [hunk 1]
```diff
@@ -8,9 +8,19 @@ export default class AllHentai extends Connector {
...
-        this.url = 'https://2023.allhen.online';
+        this.url = 'https://24.allhen.online';
         this.links = {
-            login: 'https://2023.allhen.online/internal/auth'
+            login: 'https://24.allhen.online/internal/auth'
+        };
+        this.config = {
+            throttle: {
+                label: 'Throttle Requests [ms]',
+                description: 'Enter the timespan in [ms] to delay consecuitive HTTP requests.\nThe website may block you for to many consecuitive requests.',
```
Comment (27136773) [inline src/web/mjs/connectors/AllHentai.mjs]: Typo `consecutive `

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/AllHentai.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/AllHentai.mjs]: Bloody copypaste :D
