### PR TITLE
Komiku : better updating for manga list

### LINKED ISSUE #5197: [Komiku] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Cant find some comic

**To Reproduce**
1. Komiku
2. Martial Peak 2 (https://komiku.id/manga/martial-peak-part-2/)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
image
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 8.3.4]

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Using the genres list because the full list isnt really full
* Fixes https://github.com/manga-download/hakuneko/issues/5197
* Also, first test as using a branch from here :D

### CODE REVIEW

File: src/web/mjs/connectors/Komiku.mjs [hunk 1]
```diff
@@ -20,15 +19,20 @@ export default class Komiku extends Connector {
...
-        const data = await this.fetchDOM(request, 'div.ls4 div.ls4j h4 a');
-        return data.map(element => {
-            return {
-                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
-                title: element.text.trim()
-            };
-        });
+        //using the genres list because the full list isnt really full
+        let mangaList = [];
+        for (let i = 0; i < this.paths.length; i++) {
```
Comment (Sheepux) [inline src/web/mjs/connectors/Komiku.mjs]: I'd rather use `this.paths.foreach()` if you don't need the index

**Review by Sheepux — APPROVED** [review]
LGTM
possible improvement in loop used

File: src/web/mjs/connectors/Komiku.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/Komiku.mjs]: Iirc you cant use await in a foreach loop :) . That said, a  for (const element of elements) may work
