### PR TITLE
Fix Mangadex connector: change key from 'results' to 'data'

### LINKED ISSUE #3959: [Mangadex] manga can't be fetched from connector
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot fetch any manga from mangadex. I can see the request in the developper tools but nothings is adding up in my list. I tried with kissmanga, and it works.

**To Reproduce**
1. MangaDex
4. There is no error in the console

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Druzai**
It seems that in provided json when requesting mangas, chapters and scanlation groups they changed key 'results' to 'data'.

### CODE REVIEW

File: src/web/mjs/connectors/MangaDex.mjs [hunk 1]
```diff
@@ -94,11 +94,11 @@ export default class MangaDex extends Connector {
         uri.searchParams.append('contentRating[]', 'pornographic');
         const request = new Request(uri, this.requestOptions);
         const data = await this.fetchJSON(request, 3);
```
Comment (Pierre-Monier) [inline src/web/mjs/connectors/MangaDex.mjs]: You can deconstruct the result as follows `const {data} = await this.fetchJSON(request, 3);`, it's better, but it looks like it's working :)

Comment (Druzai) [reply src/web/mjs/connectors/MangaDex.mjs]: Thanks for the info! I didn't know about this. Then I'll rewrite as you suggested.

**Review by 27136773 — APPROVED** [review]
Haven't tested it, but technically looks good
