### PR TITLE
FIX - CocoManhua : fix getting pages

### LINKED ISSUE #4725: [CocoManhua] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Cannot Download and when klik preview error base64 is not identified

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
Capture

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Fixes https://github.com/manga-download/hakuneko/issues/4725
* page number is AES_decrypt(enc_code1 )
* Pictures are encrypted
* Picture decryption key (imgKey) is encrypted itself
* Author might want to change keys but its a waste of time.

### CODE REVIEW

File: src/web/mjs/connectors/CocoManHua.mjs [hunk 1]
```diff
@@ -35,22 +25,109 @@ export default class CocoManHua extends ZYMK {
...
         const request = new Request(payload.url, this.requestOptions);
-        request.headers.set('x-referer', payload.referer);
+        request.headers.set('x-referer', this.url);
+        request.headers.set('x-origin', this.url);
         const response = await fetch(request);
-        let data = await response.blob();
-        data = await this._blobToBuffer(data);
-        this._applyRealMime(data);
-        return data;
+        let buffer = '';
```
Comment (27136773) [inline src/web/mjs/connectors/CocoManHua.mjs]: May set buffer to `undefined`, otherwise a developer may infer it is explicitly intended to be a string.

**Review by 27136773 — APPROVED** [review]
