### PR TITLE
UnionMangas : change url

### LINKED ISSUE #5642: UnionMangas not working
it's opening on https://orchidcommerce.com ----> the correct is https://unionleitor.top

### PR DESCRIPTION
**Pull request by MikeZeDev**
with url change comes additional fixes
Fixes https://github.com/manga-download/hakuneko/issues/5642

### CODE REVIEW

File: src/web/mjs/connectors/UnionMangas.mjs [hunk 1]
```diff
@@ -44,11 +53,12 @@ export default class UnionMangas extends Connector {
                 title: element.text.trim()
             };
         });
-    }
 
+    }
     async _getPages(chapter) {
         const uri = new URL(chapter.id, this.url);
         const request = new Request(uri, this.requestOptions);
+        request.headers.set('x-cookie', `modoLeitura=2; path=${manga.id}` ); //in case cookie is needed to get all pictures
```
Comment (Druzai) [inline src/web/mjs/connectors/UnionMangas.mjs]:
```suggestion
        request.headers.set('x-cookie', `modoLeitura=2; path=${chapter.manga.id}` ); //in case cookie is needed to get all pictures
```

Comment (MikeZeDev) [reply src/web/mjs/connectors/UnionMangas.mjs]: oops !

**Review by 27136773 — APPROVED** [review]
