### PR TITLE
FIX : NetTruyen - made domain changeable

### LINKED ISSUE #5905: [NetTruyen] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The site has changed its URL from [nettruyenplus](https://www.nettruyenplus.com/) to [nettruyenio](https://www.nettruyenio.com/)

New website URLs

Site: https://www.nettruyenio.com/
Manga list: https://www.nettruyenio.com/tim-truyen
Manga example: https://www.nettruyenio.com/truyen-tranh/gto-shonan-14-days-23860
Chapter online viewer example: https://www.nettruyenio.com/truyen-tranh/gto-great-teacher-onizuka/chap-199/495772
Languages
Vietnamese

**HakuNeko (please complete the following information):**
 - Version [6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
VN websites keep changing url so often that its painful. Fixes https://github.com/manga-download/hakuneko/issues/5905

### CODE REVIEW

File: src/web/mjs/connectors/NetTruyen.mjs [hunk 1]
```diff
@@ -7,9 +7,32 @@ export default class NetTruyen extends MojoPortalComic {
...
         this.links = {
             login: this.url + '/Secure/Login.aspx'
         };
+
+    }
+    get url() {
+        return this.config.url.value;
+    }
+
+    set url(value) {
```
Comment (27136773) [inline src/web/mjs/connectors/NetTruyen.mjs:27]: IIRC, last time you requested to remove the setter, it was not working. I am gonna test without, if not keep it

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/NetTruyen.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/NetTruyen.mjs:27]: image

Connector does not load without setter :/
