### PR TITLE
FIX GourmetScans: domain change & tweak script

### LINKED ISSUE #6530: [<GourmetScans.mjs>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

URL Changed to "https://gourmetsupremacy.com"
If I manually fix the URL I get "CryptoJS is not defined" If I try to preview any chapter.

### To Reproduce

1. GourmetScans.mjs (with URL manually fixed "https://gourmetscans.net" -> "https://gourmetsupremacy.com")
2. Any manga
3. Any chapter
4. "CryptoJS is not defined"

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6530

### CODE REVIEW

File: src/web/mjs/connectors/GourmetScans.mjs [hunk 1]
```diff
@@ -7,21 +7,28 @@ export default class GourmetScans extends WordPressMadara {
...
         const url = new URL(chapter.id, this.url);
         const request = new Request(url, this.requestOptions);
         const script = `
             new Promise((resolve, reject) => {
-                var imgdata = JSON.parse(CryptoJS.AES.decrypt(chapter_data, wpmangaprotectornonce, {
-                    format: CryptoJSAesJson
-                }).toString(CryptoJS.enc.Utf8));
-                resolve(JSON.parse(imgdata));
+                try {
+                    let t = new RocketLazyLoadScripts;
```
Comment (Sheepux) [inline src/web/mjs/connectors/GourmetScans.mjs]: Use a more explicit variable name even if temporary (serves as self documentation)

**Review by Sheepux — APPROVED** [review]
