### PR TITLE
Websites support & Fixes

### LINKED ISSUE #3704: [NameOfConnector] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Site changed url from .net to .com. Manga list appears, but not the chapters.

**To Reproduce**
1. Neox Scanlator
2. any manga
3. chapter no appears
4. Failed to load resource: the server responded with a status of 403 ()

**Screenshots**

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Slowftw**

### CODE REVIEW

File: src/web/mjs/connectors/MangaHost.mjs [hunk 1]
```diff
@@ -49,7 +49,11 @@ export default class MangaHost extends Connector {
     }
 
     _getChapterList(manga, callback) {
-        this.fetchDOM(this.url + manga.id, 'div.chapters div.card.pop div.pop-title span')
+        this.fetchDOM(
+            // https://regex101.com/r/2gZjlK/1
+            manga.id.match(/(https?:)?(\/\/|\/\\\\)/) ?
```
Comment (27136773) [inline src/web/mjs/connectors/MangaHost.mjs]: Looks complicated, can `const url = new URL(manga.id, this.url).href` not be used instead?

Comment (Slowftw) [reply src/web/mjs/connectors/MangaHost.mjs]: ya but according to dodieboy's comment https://github.com/manga-download/hakuneko/issues/3362#issuecomment-823093119
if the domain isn't the same, the URL constructor will return an exception...
I didn't just change the domain because the domain changes constantly

The only problem is that the clipboard will only work with the domain of this.url

Comment (27136773) [reply src/web/mjs/connectors/MangaHost.mjs]: The URL constructor will automatically take care of it by providing a base URL
```javascript
new URL('/manga/one-piece', 'https://connector.domain').href;
// => 'https://connector.domain/manga/one-piece'
new URL('https://foreign.domain/manga/one-piece', 'https://connector.domain').href;
// => 'https://foreign.domain/manga/one-piece'
```

Comment (27136773) [reply src/web/mjs/connectors/MangaHost.mjs]: For regularly changing domains, simply apply the new domain during initialization, e.g. as in [HeavenManga](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/HeavenManga.mjs#L20-L21)

Comment (27136773) [reply src/web/mjs/connectors/MangaHost.mjs]: To support multi-domain copy & paste, overwrite the [canHandleURI()](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/HeavenManga.mjs#L13-L15) method with a corresponding pattern matching

Comment (Slowftw) [reply src/web/mjs/connectors/MangaHost.mjs]: o✌️ 
I didn't know about multi-domain 👀

**Review by 27136773 — APPROVED** [review]
Looks good
