### PR TITLE
FIX PixivComics : unscramble pictures

### LINKED ISSUE #6268: [<Comic Pixiv>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

When clicked on "download button", the button instantly turned to red warning exclamation sign. Also. an error window appeared when clicked on "preview chapter button".
image

### To Reproduce

1. Comic Pixiv
2. 戦場の聖女〜妹の代わりに公爵騎士に嫁ぐことになりましたが、今は幸せです〜 (https://comic.pixiv.net/works/9683)
3. Chapter 3.2 (第3話② 契約結婚？② 更新日: 2023年9月27日)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
```
Connector.mjs:460 GET https://comic.pixiv.net/api/app/episodes/152407/read 404
fetchJSON @ Connector.mjs:460
_getPages @ PixivComics.mjs:85
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:111
Promise.then (async)
getPages @ Chapter.mjs:109
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49

Connector.mjs:618 Error: Failed to receive content from "https://comic.pixiv.net/api/app/episodes/152407/read" (status: 404) - 
    at Connector.mjs:469
    at async PixivComics._getPages (PixivComics.mjs:85)
    at async PixivComics._getPageList (Connector.mjs:615) EventTarget {manga: EventTarget, id: 152407, title: "第3話① - 契約結婚？①", file: {…}, language: "", …}manga: EventTarget {connector: PixivComics, id: 9683, title: "戦場の聖女〜妹の代わりに公爵騎士に嫁ぐことになりましたが、今は幸せです〜", status: "available", chapterCache: Array(9), …}connector: PixivComics {id: "pixivcomics", label: "pixivコミック", tags: Array(2), isLocked: false, initialized: true, …}id: 9683title: "戦場の聖女〜妹の代わりに公爵騎士に嫁ぐことになりましたが、今は幸せです〜"status: "available"chapterCache: (9) [EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget, EventTarget]existingChapters: []__proto__: EventTargetid: 152407title: "第3話① - 契約結婚？①"file: {name: "第3話① - 契約結婚？①", extension: "", full: "第3話① - 契約結婚？①"}language: ""status: "failed"pageProcess: falsepageCache: []__proto__: EventTarget
_getPageList @ Connector.mjs:618
async function (async)
_getPageList @ Connector.mjs:615
(anonymous) @ Chapter.mjs:111
Promise.then (async)
getPages @ Chapter.mjs:109
downloadPages @ DownloadJob.mjs:72
processQueue @ DownloadManager.mjs:49
```

Screenshots:
image

### PR DESCRIPTION
**Pull request by MikeZeDev**
* getPages ditched MD5 for SHA256
* getPages  url endpoint is different 
* fetching image need a request header containing scrambling key
* Images are scrambled

Fixes https://github.com/manga-download/hakuneko/issues/6268

### CODE REVIEW

File: src/web/mjs/connectors/PixivComics.mjs [hunk 1]
```diff
@@ -76,13 +76,141 @@ export default class PixivComics extends Connector {
...
+
+        ctx.drawImage(image, 0, 0);
+        const i = ctx.getImageData(0, 0, payload.width, payload.height);
+        const l = await this.descrambleData(i.data, 4, payload.width, payload.height, payload.gridsize, payload.gridsize, '4wXCKprMMoxnyJ3PocJFs4CYbfnbazNe', payload.key, true );
+        const o = new ImageData(l, payload.width, payload.height);
+        ctx.putImageData(o, 0, 0);
+        return canvas;
+    }
+
+    async descrambleData(e, t, i, r, n, s, a, l, o) {
```
Comment (27136773) [inline src/web/mjs/connectors/PixivComics.mjs]: This code seems copy & pasted from the website, may move this code outside of this class (near `PixivShuffler` class declaration)

**Review by 27136773 — APPROVED** [review]
