### PR TITLE
MyAnimeList (manga)  fixes

### LINKED ISSUE #5464: [myanimelistmanga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The Scraper is broken. I buyed a few mangas from the site any i read a few on the site, but the scraper can't detect even the individual volumes even when i point the page to the series or the volume

**To Reproduce**
1. myanimelistmanga, open the site inside hakuneko to log in
2. reload the connector (nothing happens)
3. open the site in hakuneko again, but this time to username -> bookshelf and copy the url
4. now one "manga" appears: "<username>'s Bookshelf - MyAnimeList.net"
Step 3+4 has the same effect if you choose the all manga page

**HakuNeko (please complete the following information):**
 6.1.7

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Fixes https://github.com/manga-download/hakuneko/issues/5464
* Get Mangas from store
* Handle preview and download of free and paid volumes (paid was tested)
* Does not support light novels. They use a modified Publus with path an sizes thats all i can say. Attempts to add it ended up in successful unscrambling but many errors 500 (junk pages? )

### CODE REVIEW

File: src/web/mjs/connectors/MyAnimeListManga.mjs [hunk 1]
```diff
@@ -20,30 +33,51 @@ export default class MyAnimeListManga extends Connector {
...
+                    language: ''
+                };
+            });
+    }
+
     async _getPages(chapter) {
-        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
+        //TODO : add support for light novels  : its modified Publus reader
+        if (chapter.id.includes('novel_viewer')) {
+            throw new Error('Light Novels are not supported :/');
```
Comment (27136773) [inline src/web/mjs/connectors/MyAnimeListManga.mjs]: May return an empty array instead of throwing an error, or filter the chapter list in advance to exclude anything containing `novel_viewer`

**Review by 27136773 — APPROVED** [review]
