### PR TITLE
NitroScans: update domain

### LINKED ISSUE #7905: [<NitroScans>] Connector not working
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [x] I read it but nothing seems related

### Is the website of the connector working properly ?

- [x] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [x] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

the link Changed
website link: https://nitroscans.net/
manga list link: https://nitroscans.net/all-series/
manga link: https://nitroscans.net/series/i-can-extract-attributes/
chapter link: https://nitroscans.net/series/i-can-extract-attributes/chapter-2/

relation to other connectors if you look for mangabaz website it is now nitroscans the link redirects to it

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Closes https://github.com/manga-download/hakuneko/issues/7905

### CODE REVIEW

File: src/web/mjs/connectors/NitroScans.mjs [hunk 1]
```diff
@@ -7,6 +7,10 @@ export default class NitroScans extends WordPressMadara {
         super.id = 'nitroscans';
         super.label = 'Nitro Manga';
         this.tags = [ 'webtoon', 'english' ];
-        this.url = 'https://nitromanga.com';
+        this.url = 'https://nitroscans.net';
+    }
+
+    async _initializeConnector() {
+        // do nothing on purpose
```
Comment (27136773) [inline src/web/mjs/connectors/NitroScans.mjs:14]: What is the purpose?

Comment (MikeZeDev) [reply src/web/mjs/connectors/NitroScans.mjs:14]: We do that in case website javascript "new" prevent our old electron to load mainpage. 
Its a shame ,since the rest of the code works

**Review by 27136773 — APPROVED** [review]
