### PR TITLE
fix(connectors/ikifeng): switch to WordPressMadara

### LINKED ISSUE #4112: [Ikifang ] Connector changed website to ikifeng.com
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/

**Describe the bug**
Connector changed website to ikifeng.com
**To Reproduce**
1. Name of connector Ikifang
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Pierre-Monier**
Ikifeng now use WordpressMadara instead of WordPressMangastream

### CODE REVIEW

File: src/web/mjs/connectors/Ikifeng.mjs [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import WordPressMadara from './templates/WordPressMadara.mjs';
+
+export default class Ikifeng extends WordPressMadara {
+    constructor() {
+        super();
+        super.id = "ikifeng";
+        super.label = "Ikifeng";
+        this.tags = ["manga", "webtoon", "hentai", "spanish"];
+        this.url = "https://ikifeng.com/";
```
Comment (27136773) [inline src/web/mjs/connectors/Ikifeng.mjs]: May remove trailing slash

**Review by 27136773 — APPROVED** [review]
Looks good, minor imrovments possible

File: src/web/mjs/connectors/Ikifeng.mjs (hunk 1 above)
Comment (Pierre-Monier) [reply src/web/mjs/connectors/Ikifeng.mjs]: done
