### PR TITLE
[MangaReader.to] Fixed connector

### LINKED ISSUE #4636: [mangareader.to] Scrambled Page Content
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Basically, the manga “Kotaro Lives Alone” pages content is scrambled.

**To Reproduce**
1. Go to mangareader.to connector 
2. Click on Kotaro Lives Alone
3. Scroll down to Chapters 26-Ongoing
and look through any of those chapters 
4. You’ll then see the scrambled panels/content on every page in each chapter 

**Expected behavior**
I expected the pages to be normal, and not disoriented and scrambled.

**Screenshots**

E02BB1A9-593E-4747-A7D7-6DD0B696A15F

**Context (please complete the following information):**
 - OS: Windows 10
 - HakuNeko Version 6.17

**Additional context**
Only chapters 26-present are affected, the chapters before 26 are all normal.

### PR DESCRIPTION
**Pull request by Druzai**
Resolves #4636

### CODE REVIEW

File: src/web/mjs/connectors/MangaReaderTo.mjs [hunk 1]
```diff
@@ -83,12 +83,16 @@ export default class MangaReaderTo extends Connector {
 
         const dom = this.createDOM(data.html);
         const imagesArr = Array.from(dom.querySelectorAll('.iv-card'));
+        const shuffled = imagesArr.length > 0 ? imagesArr[0].className.includes('shuffled') : false;
+
+        if (!shuffled)
```
Comment (27136773) [inline src/web/mjs/connectors/MangaReaderTo.mjs]: May be simplified to remove intermediate variable `shuffled`

```javascript
if(!imagesArr.length || !imagesArr[0].className.includes('shuffled')) {
    // ...
}
```

Comment (Druzai) [reply src/web/mjs/connectors/MangaReaderTo.mjs]: Fixed

**Review by 27136773 — APPROVED** [review]
