### PR TITLE
[reperscans] changed template to wordpressmadara

### LINKED ISSUE #3697: Reaper Scans
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

The site just merged with another site, so the problem is most likely tied to the site reformatting. Refreshing the connector empties out existing titles so zero titles and chapters. The site, itself works properly.

**To Reproduce**
1. Name of connector.   Reaper Scan
2. Name of manga (if connector update is working).   All
3. Name of chapter (if manga update is working).       All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

Screen Shot 2021-07-12 at 12 30 52 PM

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by 27136773**

### CODE REVIEW

**Review by Sheepux — APPROVED** [review]

File: src/web/mjs/connectors/ReaperScansFR.mjs [hunk 1]
```diff
@@ -7,7 +7,6 @@ export default class ReaperScansFR extends WordPressMangastream {
         super.id = 'reaperscansfr';
         super.label = 'Reaper Scans FR';
         this.tags = ['webtoon', 'english'];
```
Comment (Sheepux) [inline src/web/mjs/connectors/ReaperScansFR.mjs]: note: tags should be french

Comment (27136773) [reply src/web/mjs/connectors/ReaperScansFR.mjs]: Fixed
