### PR TITLE
Option for sequential downloads

### LINKED ISSUE #3814: [LineWebtoon] Chapter download Failed (English)
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
I tried to download a manga in webtoon but the download is fail.

**To Reproduce**
1. https://www.webtoons.com/ 
2. I have tried some mangas - all with the same error

**Screenshots**
ERROR

**HakuNeko (please complete the following information):**
 - Version [ 6.1.7]

### LINKED ISSUE #4072: [1stkiss Manga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
download chapter error

**To Reproduce**
1. 1stkiss Manga
2. 101 Ways to Win Her Heart
3. chapter 37
4. err_spdy_protocol_error

**HakuNeko (please complete the following information):**
 - Version 6.17

### PR DESCRIPTION
**Pull request by 27136773**
Adds a new option to perform sequential downloads instead of concurrent downloads.
This is targeting users reporting problems of failed downloads due to network errors or slow internet connections.

----

Screen Shot 2021-10-23 at 4 36 23 PM

### CODE REVIEW

File: src/web/mjs/engine/DownloadJob.mjs [hunk 1]
```diff
@@ -212,31 +215,36 @@ export default class DownloadJob extends EventTarget {
...
+                    const response = await fetch(request);
+                    if(response.status !== 200) {
+                        throw new Error(`Packet "${packet.link}" returned status: '${response.status}' - '${response.statusText}`);
+                    }
+                    const data = await response.arrayBuffer();
+                    await Engine.Storage.saveChapterFileM3U8(this.chapter, { name: packet.target, data: new Uint8Array(data) });
+                    this.setProgress(this.progress + 100/packets.length);
+                };
+
+                if(Engine.Settings.useSequentialMediaDownloads.value ) {
```
Comment (Sheepux) [inline src/web/mjs/engine/DownloadJob.mjs:234]: could use pqueue https://github.com/sindresorhus/p-queue with/without concurrent mode to manage the promises queuing/throttling.
This is what i plan to use for haruneko

**Review by Sheepux — APPROVED** [review]
/LGTM
I do believe pqueue would solve a lot of promise-queuing handling.

File: src/web/mjs/engine/DownloadJob.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/engine/DownloadJob.mjs:234]: I agree, but i think it's not worth the effort right now to drag in new dependencies.
Also `p-limit` seems to be more appropriate in this certain case since each result is related and they need to be saved/combined after completion.

Comment (Sheepux) [reply src/web/mjs/engine/DownloadJob.mjs:234]: i'd go with `p-queue` because of the `option` you can set (only in p-queue) on the queue that allows some advanced scenarii.
The main option i've seen is `intervalCap + interval "The max number of runs in the given interval of time."`
It would help for site that have quota/min
