### PR TITLE
FIX - Comico new API

### LINKED ISSUE #5263: [Comico (コミコ)] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot update and synchronize local manga list with online list from Comico (コミコ)

**To Reproduce**
1. Name of connector: Comico.jp
2. Name of manga: Any
3. Name of chapter: Any 
4. Copy any relevant error message that appears in a popup: Unexpected token < in JSON at position 0

**Screenshots**

haku

**HakuNeko (please complete the following information):**
 - Version [6.17]

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Fixes https://github.com/manga-download/hakuneko/issues/5263

Probably will need more fixes to know if all accessible chapters are displayed.

### CODE REVIEW

File: src/web/mjs/connectors/Comico.mjs [hunk 1]
```diff
@@ -9,80 +9,96 @@ export default class Comico extends Connector {
...
         }
         return mangaList;
     }
 
-    async _getMangasFromPage(day, page) {
-        let endpoint = day ? '/official' : '/challenge';
-        let data = await this._fetchPOST(endpoint + '/updateList.nhn', { day, page });
-        return !data.result ? [] : data.result.list.map(manga => {
+    async _getMangasFromPage(page) {
+        let data = await this._fetchPOST('/all_comic/new_release?pageNo='+page +'&pageSize=10');
```
Comment (Sheepux) [inline src/web/mjs/connectors/Comico.mjs]: can the page size be increased to reduce the calls amount ?

**Review by Sheepux — APPROVED** [review]
