### PR TITLE
[MangaHost] dom selector change

### LINKED ISSUE #2066: [MangaHost] Connector not working
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when getting the list it does not return the list (no error)

**To Reproduce**
1. MangaHost
2. refresh list 
3.no error and no list
yes i have done the captcha(if not u get errors that don't say anything about a captcha)

**HakuNeko (please complete the following information):**
 - Version [master]

### PR DESCRIPTION
**Pull request by Sheepux**
Fixes #2066

### CODE REVIEW

File: src/web/mjs/connectors/MangaHost.mjs [hunk 1]
```diff
@@ -49,12 +49,12 @@ export default class MangaHost extends Connector {
...
 
     _getChapterList( manga, callback ) {
-        this.fetchDOM( this.url + manga.id, 'ul.list_chapters li a[data-original-title]' )
+        this.fetchDOM( this.url + manga.id, 'div.chapters div.card.pop div.pop-title span' )
             .then( data => {
                 let chapterList = data.map( element => {
                     return {
-                        id: [manga.id, element.id].join('/'),
-                        title: element.dataset.originalTitle.replace( manga.title, '' ).replace( /\s+-\s*$/, '' ).trim(),
+                        id: [manga.id, element.textContent].join('/'),
```
Comment (27136773) [inline src/web/mjs/connectors/MangaHost.mjs:56]: Looks weird that the ID is the title (requires to be USVString), but i guess it has been tested with various chapter titles and works...

**Review by 27136773 — APPROVED** [review]
Seems good

File: src/web/mjs/connectors/MangaHost.mjs (hunk 1 above)
Comment (Sheepux) [reply src/web/mjs/connectors/MangaHost.mjs:56]: There is no chapter title available on the page :\
https://mangahost2.com/manga/hack-g-u-mh35138
the only element i was able to find is the span that is mostly the chapter number, but sometimes EXTRA-01
