### PR TITLE
[team1x1] introduce url auto-update and fix manga list extraction

### LINKED ISSUE #3857: [team1x1] Connector not working
I noticed that Team X link is wrong and I want to correct it from https://tqneplus.com to https://team1x1.com/ that is correct link 
you can go and check the website. 

Uncaught Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
callbacks-registry.ts:46 Uncaught (in promise) Error: ERR_CONNECTION_CLOSED (-100) loading 'https://tqneplus.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:6126)
    at WebContents.failListener (electron/js2c/browser_init.js:6136)
    at WebContents.emit (events.js:215)
Request.mjs:377 Uncaught (in promise) Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
remote.js:224 Uncaught Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
callbacks-registry.ts:46 Uncaught (in promise) Error: ERR_CONNECTION_CLOSED (-100) loading 'https://tqneplus.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:6126)
    at WebContents.failListener (electron/js2c/browser_init.js:6136)
    at WebContents.emit (events.js:215)
Request.mjs:377 Uncaught (in promise) Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)

### PR DESCRIPTION
**Pull request by 27136773**

### CODE REVIEW

File: src/web/mjs/connectors/Team1x1.mjs [hunk 1]
```diff
@@ -30,30 +49,25 @@ export default class Team1x1 extends Connector {
...
 
-    async _getMangaListFromPages(mangaPageLinks, index) {
-        index = index || 0;
-        const request = new Request(mangaPageLinks[index], this.requestOptions);
-        const data = await this.fetchDOM(request, 'div#page-manga div.container div.last-post-manga div.thumb div.info h3 a', 5);
-        let mangaList = data.map(element => {
+    async _getMangas() {
+        let mangaList = [];
+        for (let page = 1, run = true; run; page++) {
+            const mangas = await this._getMangasFromPage(page);
```
Comment (Sheepux) [inline src/web/mjs/connectors/Team1x1.mjs:55]: How about an alert in case getMAngasFromPage (the fetch) fails and throws an exception.
Message could be something like "The request failed, please check if the domain in the settings is still ok".

**Review by Sheepux — APPROVED** [review]
/LGTM, user feedback improvement possible
