### PR TITLE
[tapas] fix fetching mangas

### LINKED ISSUE #1508: Tapas manga list not updating
It doesn't seem to recognize Tapas URLs? Tried updating manga list, it finished and got nothing, no error message either.

### PR DESCRIPTION
**Pull request by XenonR**
Fixes #1508

### CODE REVIEW

File: src/web/mjs/connectors/Tapas.mjs [hunk 1]
```diff
@@ -32,14 +32,15 @@ export default class Tapas extends Connector {
...
         //uri.searchParams.set('pageSize', 20);
         let request = new Request(uri, this.requestOptions);
-        let data = await this.fetchDOM(request, 'div.section__body ul.content__list li.list__item a.item__title');
+        let data = await this.fetchDOM(request, 'div.section__body ul.content__list li.list__item a.thumb');
         return data.map(element => {
             return {
-                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
-                title: element.text.trim()
+                id: this.getRootRelativeOrAbsoluteLink(element.pathname, this.url),
+                title: element.querySelector('source').attributes.getNamedItem('alt').value.trim()
```
Comment (27136773) [inline src/web/mjs/connectors/Tapas.mjs:43]: May use `getAttribute('alt')` which is a little bit more compact

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/Tapas.mjs (hunk 1 above)
Comment (XenonR) [reply src/web/mjs/connectors/Tapas.mjs:43]: the more you know :)
