### PR TITLE
Fix AzoraWorld/AzoraManga : domain, getpages etc.

### LINKED ISSUE #6488: AzoraWorld
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

AzoraWorld is new source https://azoramoon.com/

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
* change domain
* fix getpages
* AzoraManga is now a dummy connector telling use to use AzoraWorld (website are the same domain)
Fixes https://github.com/manga-download/hakuneko/issues/6488

### CODE REVIEW

File: src/web/mjs/connectors/AzoraManga.mjs [hunk 1]
```diff
@@ -1,6 +1,6 @@
-import WordPressMadara from './templates/WordPressMadara.mjs';
+import Connector from '../engine/Connector.mjs';
 
-export default class AzoraManga extends WordPressMadara {
+export default class AzoraManga extends Connector {
```
Comment (27136773) [inline src/web/mjs/connectors/AzoraManga.mjs]: Extending `AzoraWorld` may be another solution, which may not break bookmarks (in case of compatibility).

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/AzoraManga.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/AzoraManga.mjs]: Done
