### PR TITLE
FIX ComicEarthStar : switch to CoreView

### LINKED ISSUE #6536: [Comic Earth Star] website change
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Earth Star Ent. has renewal their site and change viewer to CoreView.

### To Reproduce

1. Name of connector: Comic Earth Star
2. Name of manga: All
3. Name of chapter: All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Got this error on Devtool.

```
Request.mjs:388 Uncaught (in promise) Error: Object has been destroyed
    at electron/js2c/browser_init.js:6863
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6706)
    at IpcMainImpl.emit (events.js:210)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3930)
    at WebContents.emit (events.js:210)
```

### PR DESCRIPTION
**Pull request by MikeZeDev**
Bye bye Publus, welcome Coreview and GraphQL

Fixes https://github.com/manga-download/hakuneko/issues/6536

### CODE REVIEW

File: src/web/mjs/connectors/ComicEarthStar.mjs [hunk 1]
```diff
@@ -1,71 +1,94 @@
...
-                } );
-                let mangaList = ongoingList.concat( completedList );
-                callback( null, mangaList );
-            } )
-            .catch( error => {
-                console.error( error, this );
-                callback( error, undefined );
-            } );
-    }
+        let operationName = 'Earthstar_Oneshot';
```
Comment (Sheepux) [inline src/web/mjs/connectors/ComicEarthStar.mjs:17]: I wouldn't use `let` because this variable is not stricly related to the next stage
I'd use an object as i believe it serves as self documentation (but perhaps that's personal taste)
```
const oneShotsRequest = {
    operationName = '',
    query= ''
}
```

**Review by Sheepux — APPROVED** [review]

File: src/web/mjs/connectors/ComicEarthStar.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/ComicEarthStar.mjs:17]: Graphql is pretty much straightforwarded tho :
A query string
A string for operation name
An object with "variables"

Separating them may prevent dev errors when it comes to serialization and integrity after, especially because the third argument of FetchgraphQL is an object with only variables, not the whole thing.
