### PR TITLE
Websites updates

### LINKED ISSUE #3740: [MangaMX] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
**Yes**/~No~

**Is the website of the connector working properly / are you able to see the manga within your browser**
**Yes**/~No~

**Describe the bug**
The connector MangaMX is showing an error message when trying to update manga list.

**To Reproduce**
**MangaMX**

TypeError: Cannot read property 'href' of undefined
    at MangaMx._getMangaList (MangaMx.mjs:27) MangaMxexistingManga: [### Descargadores: true, ### Lectores: true, #### Comics: true, Ajin: true, Aka Ihon: true, …]existingMangas: []id: "mangamx"initialized: trueisLocked: falseisUpdating: falselabel: "MangaMx"mangaCache: undefinedrequestOptions: {method: "GET", mode: "cors", redirect: "follow", credentials: "same-origin", headers: Headers}tags: (2) ["manga", "spanish"]url: "https://manga-mx.com"icon: (...)__proto__: Connectorconstructor: class MangaMxicon: (...)_createChapterRequest: ƒ _createChapterRequest(manga)_getChapterList: async _getChapterList(manga, callback) {         try {             let request = this._createChapterRequest(manga);             let data = await this.fetchJSON(request);             let baseURL = data.shift();             let chapterList = data.map(item => {…}_getMangaFromURI: ƒ async _getMangaFromURI(uri)_getMangaList: async _getMangaList(callback) {         try {             const path = '/directorio/';             let request = new Request(this.url + path, this.requestOptions);             let data = await this.fetchDOM(request, 'div#content nav#paginacion a:last-of-type');             let pageCount = parseInt(data[0].href.match(/p=(\d+)$/)[1]);             let mangaList = [];             for(let page of new Array(pageCount).keys()) {                 //await this.wait(this.config.throttle.value);                 let request = new Request(this.url + path + '?p=' + (page + 1), this.requestOptions);                 let data = await this.fetchDOM(request, 'div#content article#item a h2');                 let mangas = data.map(element => {…}_getPageList: async _getPageList(manga, chapter, callback) {         try {             let script = `                 new Promise(resolve => {…}__proto__: Object
_getMangaList @ MangaMx.mjs:43

**Screenshot**

**HakuNeko:**
 - Version 6.1.7

### LINKED ISSUE #3756: [Mangafast] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No. They seems to have borked their update i cant list mangas, even by genre. Tried on FF, FF nightly, and even HN internal browser. But maybe its just me.

**Describe the bug**
* I cant update manga list because HN get a 404 error for https://mangafast.net/list-manga/page/1 . 
* Tried to paste the first manga on their webpage : https://mangafast.net/read/dont-flirt-me-lord-angel doesnt work

Since i have no MF bookmark and i cant add one i cant test more to see if we are able to get chapters and files :/
On my browser i am able to see and read manga from the front page properly but thats all.

**To Reproduce**
Trying to update manga list. Doesnt work
Pasting https://mangafast.net/read/dont-flirt-me-lord-angel doesnt recognize the manga.

**Screenshots**
no need.

**HakuNeko (please complete the following information):**
 - Nightly

### LINKED ISSUE #3758: [Bug] MangaJar
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
https://mangajar.com/manga/clover-hirakawa-tetsuhiro

the website has from chapter 1 to 400 but you have to scroll down so you got full chapters from 400 to 1
but in the app it won't load full chapter and it's only has 352 to 400

**Context (please complete the following information):**
 - OS: W10
 - HakuNeko Version [6.17]

### LINKED ISSUE #3765: [TonariNoYoungJump] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Refresh to synchronize manga is not working so no manga list show up, HN console show error 404 for https://tonarinoyj.jp

**To Reproduce**
1. となりのヤングジャンプ (Tonari No Young Jump)
2. Click on refresh/synchronize
3. It dont synchronize so no manga list is even shown

**Screenshots**
here is a gif https://i.imgur.com/IAwOHp1.gif

**HakuNeko (please complete the following information):**
 - Version [6.1.7@cad181]

### LINKED ISSUE #3780: xcalibrscans.com
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Everything works except downloads usually timeout
**To Reproduce**
1. Name of connector -  https://xcalibrscans.com
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working)- All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - Download Failed

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

Screen Shot 2021-08-04 at 11 32 08 AM

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Sheepux**
fixes MangaMX #3740
mangareader domain change
fixes MangaFast #3756
fixes MangaJar #3758
fixes TonariNoYoungJump #3765
fixes xcalibrscans #3780

### CODE REVIEW

File: src/web/mjs/connectors/MangaJar.mjs [hunk 1]
```diff
@@ -21,40 +21,48 @@ export default class MangaJar extends Connector {
...
-        let data = await this.fetchDOM(request, 'ul.list-group li.chapter-item a');
-        return data.map(element => {
-            return {
-                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
-                title: element.innerText.trim(),
-                language: ''
-            };
-        });
+        let pages = await this.fetchDOM(request, 'div.chapters-infinite-pagination ul.pagination a:last-of-type');
+        let pageCount = pages.length > 0 ? parseInt(pages[pages.length - 2].href.match(/p=(\d+)$/)[1]) : 1;
```
Comment (27136773) [inline src/web/mjs/connectors/MangaJar.mjs]: May use `pages.slice(-2)[0].href.math(...)`

File: src/web/mjs/connectors/MangaJar.mjs [hunk 2]
```diff
@@ -21,40 +21,48 @@ export default class MangaJar extends Connector {
...
+        let chapterList = [];
+        for (let page of new Array(pageCount).keys()) {
+            let request = new Request(new URL(this.url + manga.id.replace(/\/$/, '') + '/chaptersList' + '?page=' + (page + 1)), this.requestOptions);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaJar.mjs]: May declare the url outside of the loop and inside the loop just set the page, e.g.
```javascript
const uri = new URL(manga.id + '/chapterlist', this.url)
for let page ... {
    uri.searchParams.set('page', page + 1)
    const request = new Request(uri, ...)
```

```

File: src/web/mjs/connectors/MangaJar.mjs [hunk 3]
```diff
@@ -21,40 +21,48 @@ export default class MangaJar extends Connector {
...
+            let data = await this.fetchDOM(request, 'ul.list-group li.chapter-item a');
+            let mangas = data.map(element => {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaJar.mjs]: May rename `mangas` to `chapters`

File: src/web/mjs/connectors/MangaMx.mjs [hunk 4]
```diff
@@ -19,77 +19,54 @@ export default class MangaMx extends Connector {
...
-            let chapterList = data.map(item => {
+    async _getMangas() {
+        const path = '/directorio?adulto=false&orden=asc';
+        let request = new Request(this.url + path, this.requestOptions);
+        let data = await this.fetchDOM(request, 'div#content ul.pagination a:last-of-type');
+        let pageCount = parseInt(data[data.length - 2].href.match(/p=(\d+)$/)[1]);
+        let mangaList = [];
+        for (let page of new Array(pageCount).keys()) {
+            //await this.wait(this.config.throttle.value);
+            let request = new Request(this.url + path + '?p=' + (page + 1), this.requestOptions);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaMx.mjs]: May declare uri outside of loop as stated in other comment

**Review by 27136773 — APPROVED** [review]
Looks good, minor adjustments possible
