### PR TITLE
ScanTrad

### LINKED ISSUE #3394: [SCANTRAD.NET] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
AFter website update (22/04), connector doesn't work anymore, can't list or update manga and it seems #3380 that download doesn't work either 

**To Reproduce**
1. Scantrad
2. Sakamoto Days
3. 20
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.17@845bf9

### PR DESCRIPTION
**Pull request by dodieboy**
FIX #3394

### CODE REVIEW

File: src/web/mjs/connectors/ScanTrad.mjs [hunk 1]
```diff
@@ -13,36 +14,51 @@ export default class ScanTrad extends Connector {
...
-                return {
-                    id: this.getRootRelativeOrAbsoluteLink(link, request.url),
-                    title: number + ' - ' + title,
-                    language: ''
-                };
-            });
+        let data = await this.fetchDOM(request, 'div.chapitre a.ch-left');
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element, request.url),
```
Comment (27136773) [inline src/web/mjs/connectors/ScanTrad.mjs]: May prefer `this.url` instead of `request.url`

File: src/web/mjs/connectors/ScanTrad.mjs [hunk 2]
```diff
@@ -13,36 +14,51 @@ export default class ScanTrad extends Connector {
...
+                title: element.querySelector('div.chl-titre span.chl-num').textContent.trim()
+            };
+        });
     }
 
     async _getPages(chapter) {
+        let referer = new URL(chapter.id, this.url).href;
         let request = new Request(this.url + chapter.id, this.requestOptions);
```
Comment (27136773) [inline src/web/mjs/connectors/ScanTrad.mjs:45]: May use `referer` instead of `this.url + chapter.id`

File: src/web/mjs/connectors/ScanTrad.mjs [hunk 3]
```diff
@@ -13,36 +14,51 @@ export default class ScanTrad extends Connector {
...
         let data = await this.fetchDOM(request, 'div.main_img div.sc-lel > source');
-        return data.map(element => this.getAbsolutePath(element.dataset.src || element, 'https://scan-trad.fr')).filter(link => !link.includes('/images/'));
+        return data.map(element => this.createConnectorURI({
+            url:this.getAbsolutePath(element.dataset.src || element, 'https://scan-trad.fr'),
```
Comment (27136773) [inline src/web/mjs/connectors/ScanTrad.mjs]: Missing space after `:` (maybe we should add this rule to lint config)

File: src/web/mjs/connectors/ScanTrad.mjs [hunk 4]
```diff
@@ -13,36 +14,51 @@ export default class ScanTrad extends Connector {
...
+            referer: referer
+        })).filter(link => !link.includes('/images/'));
```
Comment (27136773) [inline src/web/mjs/connectors/ScanTrad.mjs]: Is this filter intentional?
I don't think this will work at this point since `createConnectorURI ` will produce something like `connector://scantrad/?payload=BASE64_DATA`

File: src/web/mjs/connectors/ScanTrad.mjs [hunk 5]
```diff
@@ -13,36 +14,51 @@ export default class ScanTrad extends Connector {
...
     }
 
     async _getPages(chapter) {
+        let referer = new URL(chapter.id, this.url).href;
         let request = new Request(this.url + chapter.id, this.requestOptions);
         let data = await this.fetchDOM(request, 'div.main_img div.sc-lel > source');
-        return data.map(element => this.getAbsolutePath(element.dataset.src || element, 'https://scan-trad.fr')).filter(link => !link.includes('/images/'));
+        return data.map(element => this.createConnectorURI({
+            url:this.getAbsolutePath(element.dataset.src || element, 'https://scan-trad.fr'),
+            referer: referer
```
Comment (27136773) [inline src/web/mjs/connectors/ScanTrad.mjs]: May use `request.url` instead of `referer`

File: src/web/mjs/connectors/ScanTrad.mjs (hunk 4 above)
Comment (dodieboy) [reply src/web/mjs/connectors/ScanTrad.mjs]: The filter is part of the old code, i will play with the website later to see if needed

**Review by 27136773 — APPROVED** [review]
Looks good now

**Comment by 27136773** [comment]
Make sure to resolve the conflict, so it can be merged into master branch

**Comment by dodieboy** [comment]
> Make sure to resolve the conflict, so it can be merged into master branch

Noted, resolve the conflict alr

**Comment by Ben93160** [comment]
Hello,

Any news ? I relauch regularly my client hakuneko but it doesn't seems to work better :-)

Regards,

Benoit.

**Comment by 27136773** [comment]
> Hello,
> 
> Any news ? I relauch regularly my client hakuneko but it doesn't seems to work better :-)
> 
> Regards,
> 
> Benoit.

Use nightly build or wait for fix to be merged into 6.1.7
