### PR TITLE
FIX ComicK domain & mangalist

### LINKED ISSUE #6516: [<Comick>] Missing mangas in list
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

I've noticed that the connector is functioning properly, and it successfully refreshes. However, I've encountered an issue where some titles and mangas are missing from the connector but can still be found on the original website.

### To Reproduce

1. Name of connector- Comick
2. Name of manga (if connector update is working)- I Am Really Not A Child Of Luck
3. Name of chapter (if manga update is working)- I Am Really Not A Child Of Luck
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12): not found

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6516

### CODE REVIEW

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/ComicK.mjs [hunk 1]
```diff
@@ -40,7 +40,7 @@ export default class ComicK extends Connector {
 
     async _getMangasFromPage(page) {
         try {
-            const uri = new URL('/v1.0/search?page=' + page, this.apiurl);
+            const uri = new URL('/v1.0/search?limit=49&page=' + page, this.apiurl); //if we keep the limit to 49 we can fetch all 25 pages
```
Comment (27136773) [inline src/web/mjs/connectors/ComicK.mjs]: This comment is not appropriate for source code, changes can be traced by developer in commit history for the the reason this was changed
