### PR TITLE
Websites Maintenance

### LINKED ISSUE #3449: [MangaHost] Outdated domain
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
```diff
- mangahosted.com
+ mangahostz.com
```

**HakuNeko (please complete the following information):**
 - Version Nightly

### LINKED ISSUE #3451: [Toonkor] Domain changed so connector not working
Did you read (https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within Haku-Neko browser
No

**Describe the bug**
Toonkor has changed it's domain to a new one and the existing conenctor is unable to switch from domain fit to domain zone

**To Reproduce**
Try to update the connector or open it on a new internal browser
1. Toonkor - New domain is https://tkor.zone/ (might change). Existing domain on Haku Neko is https://tkor.fit/
2. All series
3. All chapters
4. Unable to update filter

Screenshots

### LINKED ISSUE #3452: [Copytoon] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
The connector is unable to connect to the site and update the series list

**To Reproduce**
Steps to reproduce the behavior: Try to update filter on the site. Copytoon 142 seems to be the new site https://copytoon142.com/웹툰
1. Name of connector Copytoon
2. NA
3. NA
4. Unable to connect , err_name_resolution - unable to resolve domain dns i believe

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3454: TMOHentai
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
In the TMOHentai connector, when I try to update the connector I immediately get this message: "FAILED TO UPDATE MANGA LIST FOR TMOHENTAI
CANNOT READ PROPERTY "TEXT" OF UNDEFINED"

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version 6.1.7

### PR DESCRIPTION
**Pull request by Sheepux**

### CODE REVIEW

File: src/web/mjs/connectors/TuMangaOnlineHentai.mjs [hunk 1]
```diff
@@ -22,81 +22,38 @@ export default class TuMangaOnlineHentai extends Connector {
...
-                        .then( mangas => mangaList.concat( mangas ) );
-                } else {
-                    return Promise.resolve( mangaList );
-                }
-            } );
+    async _getMangas() {
+        let mangaList = [];
+        let hasNext = true;
+        let page = 1;
+        while (hasNext) {
```
Comment (27136773) [inline src/web/mjs/connectors/TuMangaOnlineHentai.mjs]: May use [for loop](https://github.com/manga-download/hakuneko/blob/d0452f8047446166f68220c9f656e6b6adfc1c14/src/web/mjs/connectors/templates/%40Samples.mjs#L50) `for(let page = 1, hasNext = true; hasNext; page++)`

File: src/web/mjs/connectors/TuMangaOnlineHentai.mjs [hunk 2]
```diff
@@ -22,81 +22,38 @@ export default class TuMangaOnlineHentai extends Connector {
...
+            const body = (await this.fetchDOM(request, 'body'))[0];
+            let data = [...body.querySelectorAll('div.panel-body table.table tbody tr td.text-left a')];
+            let mangas = data.map(element => {
+                return {
+                    id: this.getRootRelativeOrAbsoluteLink(element, this.url).replace('/contents/', ''),
+                    title: element.text.trim()
+                };
+            });
+            mangaList = [...mangaList, ...mangas];
+            hasNext = !body.querySelectorAll('ul.pagination li')[1].className.includes("disabled");
```
Comment (27136773) [inline src/web/mjs/connectors/TuMangaOnlineHentai.mjs]: Maybe use `!body.querySelector('ul.pagination li[class*="disabled"]')` to find only the disabled element

File: src/web/mjs/connectors/TuMangaOnlineHentai.mjs [hunk 3]
```diff
@@ -22,81 +22,38 @@ export default class TuMangaOnlineHentai extends Connector {
...
+            let request = new Request(this.url + '/section/all?view=list&order=alphabetic&page=' + page, this.requestOptions);
+            const body = (await this.fetchDOM(request, 'body'))[0];
+            let data = [...body.querySelectorAll('div.panel-body table.table tbody tr td.text-left a')];
+            let mangas = data.map(element => {
+                return {
+                    id: this.getRootRelativeOrAbsoluteLink(element, this.url).replace('/contents/', ''),
+                    title: element.text.trim()
+                };
+            });
+            mangaList = [...mangaList, ...mangas];
```
Comment (27136773) [inline src/web/mjs/connectors/TuMangaOnlineHentai.mjs]: May use `mangaList.push(...mangas)`

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/TuMangaOnlineHentai.mjs (hunk 2 above)
Comment (Sheepux) [reply src/web/mjs/connectors/TuMangaOnlineHentai.mjs]: Changing to make sure i check the second li (the "next" one)  !document.querySelector('ul.pagination li:first-child + li[class*="disabled"]')
Thanks for that review

File: src/web/mjs/connectors/TuMangaOnlineHentai.mjs (hunk 3 above)
Comment (Sheepux) [reply src/web/mjs/connectors/TuMangaOnlineHentai.mjs]: I didn't know that push would merge the array. I though it would insert an single item of type array.
Edit: oh ! It's probably the combination of push & the spread operator !
