### PR TITLE
[DoujinDesu] update website

### LINKED ISSUE #4272: [doujindesu] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
domain changed (doujindesu.xxx)

**To Reproduce**
1. doujindesu
2. https://doujindesu.xxx/manga/h-a-life/
3. https://doujindesu.xxx/2022/01/03/h-a-life/
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by manh21**
Note: `/komik-list/?list` empty

Resolved #4272

### CODE REVIEW

File: src/web/mjs/connectors/DoujinDesu.mjs [hunk 1]
```diff
@@ -7,13 +7,38 @@ export default class DoujinDesu extends WordPressMangastream {
...
     }
+
+    // NOTE: Fallback to pagination since '/komik-list/?list' empty
+    async _getMangas() {
+        let mangaList = [];
+        let path;
+        for(let page = 1, run = true; run; page++) {
+            path = this.path;
+            if(page == 1) path = '/komik-list/';
+            let mangas = await this._getMangasFromPage(path, page);
```
Comment (27136773) [inline src/web/mjs/connectors/DoujinDesu.mjs:25]: Consider using ternary operator
`this._getMangasFromPage(page > 1 ? this.path : '/komik-list/', page)`

File: src/web/mjs/connectors/DoujinDesu.mjs [hunk 2]
```diff
@@ -7,13 +7,38 @@ export default class DoujinDesu extends WordPressMangastream {
...
+        this.queryMangas = '#main .relat .animepost .animposx a';
         this.queryChapters = 'div#chapter_list div.epsleft span.lchx a';
         this.queryChaptersTitle = undefined;
         this.queryPages = 'div.reader-area img[src]:not([src=""])';
     }
+
+    // NOTE: Fallback to pagination since '/komik-list/?list' empty
+    async _getMangas() {
+        let mangaList = [];
+        let path;
```
Comment (27136773) [inline src/web/mjs/connectors/DoujinDesu.mjs]: May remove local variable in case of inlining condition with ternary operator

**Review by 27136773 — APPROVED** [review]
Looks good
