### PR TITLE
mangadex improve getManga

### LINKED ISSUE #4161: [MangaDex] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When pressing the refresh button for website MangaDex, I get the error "Failed to upload manga list for MangaDex. Failed to receive content from ...://api.mangadex.org/manga?limit=100&offset=2900&publicationDemographic%5B%5D=... (Status: 404) - 

**To Reproduce**
1. Name of connector - MangaDex
2. Name of manga (if connector update is working) Update not working

**HakuNeko (please complete the following information):**
 - Version 6.1.7@9436d8

### PR DESCRIPTION
**Pull request by Robonau**
this is just #3784 but better

this should be as good as it gets
all manga
minimum requests
(totalManga + floor(totalManga/10000))/100 requests

it would be nice to get rid of the floor(totalManga/10000) (this is currently 5) but dealing with them is easier than possibly missing one by changing the times

it works now fixed the captcha issue (and 503)
resolves #4161

### CODE REVIEW

File: src/web/mjs/connectors/MangaDex.mjs [hunk 1]
```diff
@@ -47,66 +47,59 @@ export default class MangaDex extends Connector {
...
-        await this.wait(this.throttleGlobal);
-        const uri = new URL('/manga', this.api);
-        uri.searchParams.set('limit', 100);
-        uri.searchParams.set('offset', 100 * page);
-        uri.searchParams.set('publicationDemographic[]', query.publicationDemographic);
-        uri.searchParams.set('order[createdAt]', query.order);
-        uri.searchParams.append('contentRating[]', 'safe');
-        uri.searchParams.append('contentRating[]', 'suggestive');
-        uri.searchParams.append('contentRating[]', 'erotica');
-        uri.searchParams.append('contentRating[]', 'pornographic');
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs:94]: Removing this content rating will lead to missing more then 9000 mangas in the list
https://api.mangadex.org/manga?contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic

File: src/web/mjs/connectors/MangaDex.mjs [hunk 2]
```diff
@@ -47,66 +47,59 @@ export default class MangaDex extends Connector {
         const regexGUID = /[a-fA-F0-9]{8}-([a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12}/;
         const id = (uri.pathname.match(regexGUID) || uri.hash.match(regexGUID))[0].toLowerCase();
         const request = new Request(new URL('/manga/' + id, this.api), this.requestOptions);
-        const {data} = await this.fetchJSON(request);
+        const { data } = await this.fetchJSON(request);
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: Use more expressive variable names, or re-use (re-assign) the same variable to prevent confusion within the same scope.
Names such as `data`, `data1`, `data2`, `data3` may be confusing for other contributors.

File: src/web/mjs/connectors/MangaDex.mjs [hunk 3]
```diff
@@ -47,66 +47,59 @@ export default class MangaDex extends Connector {
...
+            const uri = new URL('/manga', this.api);
+            uri.searchParams.set('limit', 100);
+            uri.searchParams.set('offset', 100 * page);
+            uri.searchParams.set('order[createdAt]', 'asc');
+            if (nextAt) uri.searchParams.set('createdAtSince', nextAt);
+            const request = new Request(uri);
+            let data3 = await this.fetchJSON(request, 3);
+            await this.wait(this.throttleGlobal);
+            tmp = [...tmp, ...data3.data];
+            if (page == pages) {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: Condition is redundant, it is expected that `page == pages` is always the case after the `for` loop

File: src/web/mjs/connectors/MangaDex.mjs [hunk 4]
```diff
@@ -47,66 +47,59 @@ export default class MangaDex extends Connector {
...
+                return {
+                    data: tmp,
+                    nextAt: data3.data[data3.data.length - 1].attributes.createdAt.match(/^\d{4}-[0-1]\d-([0-2]\d|3[0-1])T([0-1]\d|2[0-3]):[0-5]\d:[0-5]\d/)[0],
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: Is the regex match required, or isn't `createdAt` always following this exact format?

Comment (27136773) [reply src/web/mjs/connectors/MangaDex.mjs]: Term `data3.data[data3.data.length - 1].attributes` may be simplified to `data3.data.pop().attributes`

File: src/web/mjs/connectors/MangaDex.mjs [hunk 5]
```diff
@@ -231,4 +224,26 @@ export default class MangaDex extends Connector {
...
+    fetchJSON( request, retries ) {
+        retries = retries || 0;
+        if( typeof request === 'string' ) {
+            request = new Request( request, this.requestOptions );
+        }
+        // TODO: check if this will affect (replace) the input parameter?
+        if( request instanceof URL ) {
+            request = new Request( request.href, this.requestOptions );
+        }
+        return fetch( request )
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: Use async/await pattern instead

File: src/web/mjs/connectors/MangaDex.mjs [hunk 6]
```diff
@@ -47,66 +47,59 @@ export default class MangaDex extends Connector {
...
+                    total: data3.total
+                };
+            }
+        }
+    }
+
     async _getChapters(manga) {
         let chapterList = [];
-        for(let page = 0, run = true; run; page++) {
+        for (let page = 0, run = true; run; page++) {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: There are many auto-format changes probably done by the editing software which are not related to this PR, i suggest to make format changes in a separate PR if really necessary

File: src/web/mjs/connectors/MangaDex.mjs [hunk 7]
```diff
@@ -231,4 +224,26 @@ export default class MangaDex extends Connector {
         });
         return range.join('-');
     }
+
+    fetchJSON( request, retries ) {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: Maybe use `fetchJSON(uri, retries)` instead, and always composing the `Request` object from the given `uri` parameter within the function itself, this saves many `new Request()` instantiations before calling `fetchJSON()`

File: src/web/mjs/connectors/MangaDex.mjs [hunk 8]
```diff
@@ -231,4 +224,26 @@ export default class MangaDex extends Connector {
...
+        if( typeof request === 'string' ) {
+            request = new Request( request, this.requestOptions );
+        }
+        // TODO: check if this will affect (replace) the input parameter?
+        if( request instanceof URL ) {
+            request = new Request( request.href, this.requestOptions );
+        }
+        return fetch( request )
+            .then( response => {
+                if( (response.status >= 500 || response.status == 404) && retries > 0 ) {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: From a technical point of view retrying on `404 - not found` makes no sense (the page does not exist, so why retry), maybe check something like `/captcha.js$/.test(response.url)` instead?

File: src/web/mjs/connectors/MangaDex.mjs (hunk 4 above)
Comment (Robonau) [reply src/web/mjs/connectors/MangaDex.mjs]: createdAt has some extra stuff at the end, removing it might be possible without regex (or a much simpler regex)

File: src/web/mjs/connectors/MangaDex.mjs (hunk 6 above)
Comment (Robonau) [reply src/web/mjs/connectors/MangaDex.mjs]: they aren't necessary, my editor does it
undoing all of the changes is quite a bit of work

**Comment by Robonau** [comment]
the mix of 503 errors and captcha-v3 is stopping me from completing a test

**Comment by Robonau** [comment]
i know its an insane amount of retries, but i error-ed out with 20
ideally the 503 and captcha-v3 404 errors should be fixed removing the need for the excess retries
they are not present in browser but after poking around i couldn't find the cause

**Comment by Sheepux** [comment]
Possibly trotting detection.

**Comment by Robonau** [comment]
> Possibly trotting detection.

its not a throttling issue, as i said it is not present in browser (with the same delays)

**Comment by Sheepux** [comment]
Well then ... have fun investigating ... 
but as soon as i set a 5s throttling i get ZERO issues while i'm able to reproduce the issue quite easily with the 200ms throttling.

**Comment by Robonau** [comment]
> Well then ... have fun investigating ... but as soon as i set a 5s throttling i get ZERO issues while i'm able to reproduce the issue quite easily with the 200ms throttling.

it just takes a while for the issue to come up when every request takes 25x longer
note:neither of these issues exist in browser (errors start happening below 200ms)
and the captcha-v3 issue shouldn't exist at all, mangadex(a dev) has said so themselves

the current PR works, and is significantly faster than setting throttle to 5 seconds
im not looking in to how to stop the captcha and 503 issues because i think they are electron related

**Comment by Sheepux** [comment]
Connector cannot be left/merged "as it" as bruteforcing is not acceptable.

This rate limiting is called "throttling". No it doesn't just take longuer, i'm able to get much more list before getting 404.
From what i could test they probably have a throttling/min and possibly a smaller span, or multiple rules as 404 and 503 are probably 2 different DDOS mechanism.

Further testing seems to show 30/min. So global throttling of 2100 was OK  (no 404 or 503 in 10 mins)
This value should be tested further.

+ better management of retries:
```javascript
    async fetchJSON(uri, retries) {
        const request = new Request(uri, this.requestOptions);
        let response = await fetch(request);
        for (retries = retries || 0; retries >= 0; retries--) {
            if (response.status === 404) await this.wait(15000);
            if (response.status >= 500 || /captcha-v3$/.test(response.url)) await this.wait(15000);
            if (response.status === 200) return response.json();
        }
        throw new Error(`Failed to receive content from "${request.url}" (status: ${response.status}) - ${response.statusText}`);
    }
```

> note: using recursive function is increasing memory for no value in this case. Use loops (while/for) instead

now we can reduce the amount of retries to 2 or 3 ```data100 = await this.fetchJSON(uri, 2);```
as we get a big "pause" (should set 1 min?) if we're reaching the DDOS trigger 

Seeing Ronny's comment: yes 404 is an actual throttling error. We're reducing the strain by now limiting the retries to 2 (a real 404 will persists)

**Comment by 27136773** [comment]
I suggest to add a user configurable throttling for scraping the manga list, with a safe default value.

**Comment by Robonau** [comment]
i cant test it, but if what you say is true then this should work

**Comment by Robonau** [comment]
though as i have said a throttle this large should not be necessary 
as https://api.mangadex.org/docs.html#section/Rate-limits says
the endpoint we are fetching has a 5 a second (200ms) rate limit, nothing else
this is what is seen on browser, a delay of 200 ms works fine, not a single issue at all
there is no "30/min" present in browser

```js
while (true){
    fetch("https://api.mangadex.org/manga?limit=100&offset=1200&order%5BcreatedAt%5D=asc&contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic&createdAtSince=2019-04-02T22%3A24%3A22");
    await new Promise(r => setTimeout(r, 200));
}
```  
will run indefinatly

**Comment by Robonau** [comment]
the issue is now actually fixed, at 200 ms throttle

**Comment by Robonau** [comment]
ping me on discord when review done

File: src/web/mjs/connectors/MangaDex.mjs [hunk 9]
```diff
@@ -11,7 +11,17 @@ export default class MangaDex extends Connector {
         this.url = 'https://mangadex.org';
         this.api = 'https://api.mangadex.org';
         this.requestOptions.headers.set('x-referer', this.url);
-        this.throttleGlobal = 100;
+        this.requestOptions.headers.set('x-sec-ch-ua', '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"');
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs:14]: What is the purpose of this header? It is very unlikely that any `sec-*` headers have an impact on requests.

File: src/web/mjs/connectors/MangaDex.mjs [hunk 10]
```diff
@@ -11,7 +11,17 @@ export default class MangaDex extends Connector {
...
+        this.config = {
+            throttle: {
```
Comment (27136773) [inline src/web/mjs/connectors/MangaDex.mjs]: `throttle` is a magic key which will be used when as delay when downloading images. Should be renamed to something else.

File: src/web/mjs/connectors/MangaDex.mjs (hunk 9 above)
Comment (Robonau) [reply src/web/mjs/connectors/MangaDex.mjs:14]: that is the header that stops the captcha-v3 404 error and the 503 errors

i went through every header different from a chrome request and HN request this was the one that bade the differance

File: src/web/mjs/connectors/MangaDex.mjs (hunk 10 above)
Comment (Robonau) [reply src/web/mjs/connectors/MangaDex.mjs]: i mean this should apply to downloads no?

Comment (Robonau) [reply src/web/mjs/connectors/MangaDex.mjs]: nvm downloading dosnt actually do any requests to the api

**Comment by Robonau** [comment]
can you ping me in discord when review done

**Review by 27136773 — APPROVED** [review]
Looks good
