### PR TITLE
[MangaHub] Fixed MangaHub connector

### LINKED ISSUE #4867: [MangaHub] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
HakuNeko cann't connect to MangaHub anymore. MangaHub fully works across multiple browsers.

**To Reproduce**
1. Name of connector: MangaHub
2. Name of manga:
Tensei Shitara Slime Datta Ken
Release That Witch
3. Name of chapter (if manga update is working): All of them
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### cache-1659044661757.log

> index.html:46** Loading Engine: HakuNeko
> hakuneko://plugins/:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
> Connectors.mjs:49 Failed to load connector "hakuneko://cache/mjs/connectors/Comikey.mjs" TypeError: Cannot read property 'isDevToolsOpened' of null
>     at Comikey.mjs:4
>     at Comikey.mjs:4
>     at Comikey.mjs:4
>     at Comikey.mjs:4
> register @ Connectors.mjs:49
> index.html:61 Loading Frontend: frontend@classic-dark
> index.html:76 [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
> loadClassicPolymer @ index.html:76
> VRV.mjs:305 VRV (Crunchyroll) login failed! Error: No login credentials provided!
>     at Promise.then.oauthRequest.method (VRV.mjs:407)
>     at new Promise (<anonymous>)
>     at VRVCrunchyroll._login (VRV.mjs:399)
>     at VRVCrunchyroll._onSettingsChanged (VRV.mjs:303)
>     at EventTarget.load (Settings.mjs:340)
>     at async loadEngine (index.html:54)
>     at async main (index.html:87)
> (anonymous) @ VRV.mjs:305
> VRV.mjs:305 VRV (HiDive) login failed! Error: No login credentials provided!
>     at Promise.then.oauthRequest.method (VRV.mjs:407)
>     at new Promise (<anonymous>)
>     at VRVHiDive._login (VRV.mjs:399)
>     at VRVHiDive._onSettingsChanged (VRV.mjs:303)
>     at EventTarget.load (Settings.mjs:340)
>     at async loadEngine (index.html:54)
>     at async main (index.html:87)
> (anonymous) @ VRV.mjs:305
> VRV.mjs:305 VRV (Rooster Teeth) login failed! Error: No login credentials provided!
>     at Promise.then.oauthRequest.method (VRV.mjs:407)
>     at new Promise (<anonymous>)
>     at VRVRoosterteeth._login (VRV.mjs:399)
>     at VRVRoosterteeth._onSettingsChanged (VRV.mjs:303)
>     at EventTarget.load (Settings.mjs:340)
>     at async loadEngine (index.html:54)
>     at async main (index.html:87)
> (anonymous) @ VRV.mjs:305
> DevTools failed to parse SourceMap: hakuneko://cache/js/protobuf.min.js.map
> DevTools failed to parse SourceMap: hakuneko://cache/js/hls.light.min.js.map
> DevTools failed to parse SourceMap: hakuneko://cache/sm/4f4f84956292156efc04b79e1131dc7c3a51794b7b3d62b43ed5eaca1b36d71e.map
> Connector.mjs:460 POST https://api.mghubcdn.com/graphql 404
> fetchJSON @ Connector.mjs:460
> fetchGraphQL @ Connector.mjs:489
> _getChapters @ MangaHub.mjs:51
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Connector.mjs:598 Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595) EventTarget {connector: MangaHub, id: "gate-jietai-kare-no-chi-nite-kaku-tatakeri", title: "Gate - Jietai Kare no Chi nite, Kaku Tatakeri", status: "completed", chapterCache: Array(0), …}
> _getChapterList @ Connector.mjs:598
> async function (async)
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595)
> (anonymous) @ Manga.mjs:153
> Connector.mjs:460 POST https://api.mghubcdn.com/graphql 404
> fetchJSON @ Connector.mjs:460
> fetchGraphQL @ Connector.mjs:489
> _getChapters @ MangaHub.mjs:51
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Connector.mjs:598 Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595) EventTarget {connector: MangaHub, id: "tensei-shitara-slime-datta-ken_102", title: "Tensei Shitara Slime Datta Ken", status: "completed", chapterCache: Array(0), …}
> _getChapterList @ Connector.mjs:598
> async function (async)
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595)
> (anonymous) @ Manga.mjs:153
> Promise.catch (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:151
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Connector.mjs:460 POST https://api.mghubcdn.com/graphql 404
> fetchJSON @ Connector.mjs:460
> fetchGraphQL @ Connector.mjs:489
> _getChapters @ MangaHub.mjs:51
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Connector.mjs:598 Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595) EventTarget {connector: MangaHub, id: "tensei-shitara-dai-nana-ouji-dattanode-kimamani-majutsu-o-kiwamemasu", title: "Tensei Shitara dai Nana Ouji dattanode, Kimamani Majutsu o Kiwamemasu", status: "available", chapterCache: Array(0), …}
> _getChapterList @ Connector.mjs:598
> async function (async)
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595)
> (anonymous) @ Manga.mjs:153
> Promise.catch (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:151
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Connector.mjs:460 POST https://api.mghubcdn.com/graphql 404
> fetchJSON @ Connector.mjs:460
> fetchGraphQL @ Connector.mjs:489
> _getChapters @ MangaHub.mjs:51
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Connector.mjs:598 Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595) EventTarget {connector: MangaHub, id: "tensei-shitara-slime-datta-ken_102", title: "Tensei Shitara Slime Datta Ken", status: "completed", chapterCache: Array(102), …}
> _getChapterList @ Connector.mjs:598
> async function (async)
> _getChapterList @ Connector.mjs:595
> (anonymous) @ Manga.mjs:134
> (anonymous) @ Manga.mjs:133
> Promise.then (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:132
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149
> Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://api.mghubcdn.com/graphql" (status: 404) - 
>     at Connector.mjs:469
>     at async MangaHub._getChapters (MangaHub.mjs:51)
>     at async MangaHub._getChapterList (Connector.mjs:595)
> (anonymous) @ Manga.mjs:153
> Promise.catch (async)
> _getUpdatedChaptersFromWebsite @ Manga.mjs:151
> (anonymous) @ Manga.mjs:98
> Promise.then (async)
> getChapters @ Manga.mjs:94
> onSelectedMangaChanged @ chapters.html:244
> runObserverEffect @ property-effects.html:217
> runEffectsForProperty @ property-effects.html:162
> runEffects @ property-effects.html:128
> _propertiesChanged @ property-effects.html:1662
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> __enableOrFlushClients @ property-effects.html:1555
> _flushClients @ property-effects.html:1530
> _propertiesChanged @ property-effects.html:1658
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> runNotifyEffects @ property-effects.html:261
> _propertiesChanged @ property-effects.html:1665
> _flushProperties @ properties-changed.html:341
> _flushProperties @ property-effects.html:1510
> _invalidateProperties @ property-effects.html:1482
> set @ property-effects.html:1817
> onMangaClicked @ mangas.html:263
> handler @ template-stamp.html:96
> (anonymous) @ templatize.html:149

**HakuNeko (please complete the following information):**
 - Version [8.3.4] or [2022 HakuNeko rev. master@81f06c]

### PR DESCRIPTION
**Pull request by Druzai**
Resolves #4867

### CODE REVIEW

File: src/web/mjs/engine/Connector.mjs [hunk 1]
```diff
@@ -475,7 +475,7 @@ export default class Connector {
             request = new URL(request);
         }
 
-        const requestOptions = JSON.parse(JSON.stringify(this.requestOptions));
+        const requestOptions = { ...this.requestOptions };
```
Comment (Druzai) [inline src/web/mjs/engine/Connector.mjs]: I know this is not a good way to deep copy an object, but clonning via `JSON.parse(JSON.stringify(this.requestOptions))` loses all headers.

I checked if the `content-type` header changes in both the original and the copied object, and it turns out that only the header from the copy has changed, so I guess it's safe to use a shallow copy.
```js
const requestOptions = { ...this.requestOptions };
const graphQLRequest = new Request(request.href ? request.href : request.url, Object.assign(requestOptions, {
	method: 'POST',
	body: JSON.stringify({
		operationName,
		query,
		variables,
	})
}));
graphQLRequest.headers.set('content-type', 'application/json');
console.log(this.requestOptions.headers.get('content-type')); // null
console.log(graphQLRequest.headers.get('content-type')); // application/json
```

**Comment by Zovog1977** [comment]
I tested this on windows and it works quite well. thanks !!

**Review by manikkuge-saumyadasa — APPROVED** [review]
I tested these changes on windows 10 OS . It worked quite well .

**Review by manikkuge-saumyadasa — APPROVED** [review]

File: src/web/mjs/engine/Connector.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/engine/Connector.mjs]: JSON was used to ensure `this.requestOptions` was not accidentaly changed.
Since this is no longer the case, i propose to remove the local variable `requestOptions` completely, to avoid the ability that `this.requestOptions` can be modified through `requestOptions`.

e.g., by directly embed the suggested object spreading:
```javascript
const graphQLRequest = new Request(request.href ? request.href : request.url, {
    ...this.requestOptions,
    method: 'POST',
    body: JSON.stringify({
        operationName,
        query,
        variables,
    })
));
```
NOTE: For duplicate properties in object spreading (e.g. `method`), the last assigned will be used

**Review by 27136773 — COMMENTED** [review]
Looks god, but would suggest to remove the intermediate local variable

File: src/web/mjs/engine/Connector.mjs (hunk 1 above)
Comment (Druzai) [reply src/web/mjs/engine/Connector.mjs]: Thanks for the explanations, fixed

**Review by 27136773 — APPROVED** [review]

**Comment by EnforcerRidley** [comment]
Thank you! It's working now.
