### PR TITLE
[SoftKomik] updates API (#3879)

### LINKED ISSUE #3879: [SoftKomik] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
cannot load chapter list

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by dodieboy**
fix #3879

### CODE REVIEW

**Review by black0888 — APPROVED** [review]

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 1]
```diff
@@ -27,16 +27,16 @@ export default class SoftKomik extends Connector {
         let mangaList = [];
         for (let page = 1, run = true; run; page++) {
             const mangas = await this._getMangasFromPage(page);
-            mangas.length > 0 ? mangaList.push(...mangas) : run = false;
+            mangas.length > 27 ? mangaList.push(...mangas) : run = false;
```
Comment (Sheepux) [inline src/web/mjs/connectors/SoftKomik.mjs]: That means that if there are 26 titles on the page they won't get retrieved. I think there's an issue here :)

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs]: My bad, fix the issue alr

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs]: My bad, fix the issue alr

Comment (Sheepux) [reply src/web/mjs/connectors/SoftKomik.mjs]: why did you remove the ternary operator (if/else) ?
If the list length is 0 (when reaching the last page and the preview page was full with 26 items) it would push the undefined result into the array.
+
lint error ;)

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs]: The api will keep giving the same result when it reach the last page. For example the last page have 26 data, last page +1 will also have 26 and not 0

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs]: Will this be a better way to write the code? Not very good in ternary operator, that why i change it to if else operator

```
for (let page = 1, run = true; run; page++) {
            const mangas = await this._getMangasFromPage(page);
            mangas.length > 27 ? mangaList.push(...mangas) : run = false;
}
mangaList.push(..mangas)
```

Comment (Sheepux) [reply src/web/mjs/connectors/SoftKomik.mjs]: I think we need to compare the last results to find if they're equals and then get out of the loop.

Comment (Sheepux) [reply src/web/mjs/connectors/SoftKomik.mjs]: I think we can leave it like that (your last code in comments). If someone requests a few missing titles we'll take a look for an alternative as we're not able to unit test  of what happens when the last page has 28 titles.
Edit: ah, it could loop infinitely in such case :\ So comparing the last results would be the actual solution i guess

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs]: I feel that this code will be better, as the previous code in the comment will cause a loop if the last page have 27 data.
```    async _getMangas() {
        let mangaList = [];
        for (let page = 1, run = true; run; page++) {
            const mangas = await this._getMangasFromPage(page);
            if(mangas.length == 0){
                run = false;
            }
            else if (mangaList.length == 0 || mangas[mangas.length - 1].id !== mangaList[mangaList.length - 1].id){
                mangaList.push(...mangas);
            }
            else{
                run = false;
            }
        }
        return mangaList;
    }
```

**Comment by 27136773** [comment]
There are still some `lint` errors that needs to be resolved

**Comment by dodieboy** [comment]
> There are still some `lint` errors that needs to be resolved

image
Hey, will like to check why im have this lint error 
Closing curly brace does not appear on the same line as the subsequent block  brace-style

**Comment by 27136773** [comment]
`} else {`

File: src/web/mjs/connectors/SoftKomik.mjs [hunk 2]
```diff
@@ -27,16 +27,22 @@ export default class SoftKomik extends Connector {
         let mangaList = [];
         for (let page = 1, run = true; run; page++) {
             const mangas = await this._getMangasFromPage(page);
-            mangas.length > 0 ? mangaList.push(...mangas) : run = false;
+            if(mangas.length == 0) {
```
Comment (27136773) [inline src/web/mjs/connectors/SoftKomik.mjs:30]: Is it possible to include this check into `_getMangasFromPage` and return an empty manga list instead a duplicate of the last page list (e.g. by checking the page exceeds the max. number of pages or something)

Comment (dodieboy) [reply src/web/mjs/connectors/SoftKomik.mjs:30]: Dont think so, when the api reach the last page, it will repeat the last page. Even the website itself do not have a max page number and will repeat the last managa list as seen in the img below. The only way is to check for duplicate.
image

**Review by 27136773 — APPROVED** [review]
Looks good now
