### PR TITLE
[comicextra] update website

### LINKED ISSUE #3247: [ComicExtra] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes
**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes
**Describe the bug**
the  comicextra extension fails to update manga list
Capture

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by x4nk1t**
Resolves #3247

### CODE REVIEW

File: src/web/mjs/connectors/ComicExtra.mjs [hunk 1]
```diff
@@ -1,28 +1,45 @@
...
-    /**
-     *
-     */
     constructor() {
         super();
         super.id = 'comicextra';
         super.label = 'ComicExtra';
-        this.tags = [];
+        this.tags = ['comic', 'english'];
         this.url = 'http://www.comicextra.com';
```
Comment (27136773) [inline src/web/mjs/connectors/ComicExtra.mjs]: Prefer `https`

File: src/web/mjs/connectors/ComicExtra.mjs [hunk 2]
```diff
@@ -1,28 +1,45 @@
...
     }
 
-    _getMangaList( callback ) {
-        callback( new Error( 'Please report this broken website on HakuNeko\'s GitHub project page.' ), undefined );
+    _getMangas() {
+        let msg = 'This website provides a manga list that is to large to scrape, please copy and paste the URL containing the images directly from your browser into HakuNeko.';
```
Comment (27136773) [inline src/web/mjs/connectors/ComicExtra.mjs]: May parse comics from
https://www.comicextra.com/comic-list/others
https://www.comicextra.com/comic-list/a
...
https://www.comicextra.com/comic-list/z

File: src/web/mjs/connectors/ComicExtra.mjs [hunk 3]
```diff
@@ -1,28 +1,45 @@
...
+        return new Manga(this, id, title);
+    }
+
+    async _getChapters(manga) {
+        const uri = new URL(manga.id, this.url);
+        const request = new Request(uri, this.requestOptions);
+        const data = await this.fetchDOM(request, '#list tr td a');
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element, request.url),
```
Comment (27136773) [inline src/web/mjs/connectors/ComicExtra.mjs]: Prefer `this.url` over `request.url`

File: src/web/mjs/connectors/ComicExtra.mjs [hunk 4]
```diff
@@ -1,28 +1,45 @@
...
+            };
+        });
     }
-    _getPageList( manga, chapter, callback ) {
-        callback( new Error( 'Please report this broken website on HakuNeko\'s GitHub project page.' ), undefined );
+
+    async _getPages(chapter) {
+        const request = new Request(this.url + chapter.id + '/full', this.requestOptions);
+        const data = await this.fetchDOM(request, '.chapter_img');
+        return data.map(element => element.src);
```
Comment (27136773) [inline src/web/mjs/connectors/ComicExtra.mjs]: May map to `element => this.getAbsolutePath(element, request.url)`

**Review by 27136773 — COMMENTED** [review]
Looks good, minor improvements possible

**Review by 27136773 — APPROVED** [review]
Looks good
