### PR TITLE
[maid] update queries and chapter list extraction

### LINKED ISSUE #2060: [MAID] Connector not working
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Can't update manga list. and maybe download feature is not work too.

**To Reproduce**
1. Name of connector : MAID
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
maid-haku-1

**HakuNeko (please complete the following information):**
 - Version 8.3.4(nightly build)

### PR DESCRIPTION
**Pull request by 27136773**
Resolves #2060

### CODE REVIEW

File: src/web/mjs/connectors/MaID.mjs [hunk 1]
```diff
@@ -16,8 +10,20 @@ export default class MaID extends WordPressEManga {
...
+    }
+
+    async _getChapters(manga) {
+        let request = new Request(new URL(manga.id, this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, this.queryChapters);
+        return data.map(element => {
+            return {
+                id: this.getRootRelativeOrAbsoluteLink(element, this.url),
+                title: element.title.replace(manga.title, '').trim(),
+                language: ''
```
Comment (XenonR) [inline src/web/mjs/connectors/MaID.mjs:25]: May remove unused var.

**Review by XenonR — APPROVED** [review]
Looking good. May remove unused var.

File: src/web/mjs/connectors/MaID.mjs (hunk 1 above)
Comment (27136773) [reply src/web/mjs/connectors/MaID.mjs:25]: Will be kept for semantically correctness
