### PR TITLE
Hiperdex : url as setting

### LINKED ISSUE #5409: [Hiperdex] Connector not working
Hiperdex is now changed to following address:
https://1sthiperdex.com/ [New address]
https://hiperdex.com/ [Old address]

**To Reproduce**
1. Connect to Hiperdex
2. Search any manga
3. Select any chapter
4. Nothing will load

 - Version 6.1.7

### PR DESCRIPTION
**Pull request by MikeZeDev**
They change between 2 url too frequently and when they do that one of the two may be unreachable.
Fixes : https://github.com/manga-download/hakuneko/issues/5409

### CODE REVIEW

File: src/web/mjs/connectors/Hiperdex.mjs [hunk 1]
```diff
@@ -7,6 +7,29 @@ export default class Hiperdex extends WordPressMadara {
...
+                value: 'https://1sthiperdex.com'
+            }
+        };
     }
+
+    get url() {
+        return this.config.url.value;
+    }
+
+    set url(value) {
```
Comment (27136773) [inline src/web/mjs/connectors/Hiperdex.mjs:29]: Is this setter used?
If not, may be removed...

File: src/web/mjs/connectors/Hiperdex.mjs [hunk 2]
```diff
@@ -7,6 +7,29 @@ export default class Hiperdex extends WordPressMadara {
         super.id = 'hiperdex';
         super.label = 'Hiperdex';
         this.tags = [ 'hentai', 'webtoon', 'english' ];
-        this.url = 'https://hiperdex.com';
+        this.config = {
```
Comment (27136773) [inline src/web/mjs/connectors/Hiperdex.mjs:10]: Seems to me once pushed to the user, the URL can no longer be automatically be updated by the developers, the user must always manually update the URL.
Is this by intention?

Comment (MikeZeDev) [reply src/web/mjs/connectors/Hiperdex.mjs:10]: Its like this for connectors where url is in settings afaik. Like i've said i would have detected the url  in initialize instead of putting a setting but Hiperdex also sometimes fire Cloudflare and one of the two domains may be unreachable (unrelated to CF)

I can ofc change to usual domain detection but there is no "master domain".

Comment (27136773) [reply src/web/mjs/connectors/Hiperdex.mjs:10]: Maybe use a `'select'` [type setting](https://github.com/manga-download/hakuneko/blob/20c5e61c46b71de379a4635a21018f406d32c42b/src/web/mjs/engine/Settings.mjs#L135-L141) with pre-defined mirrors instead of a `'text'` type to make it more suitable for users?

**Review by 27136773 — APPROVED** [review]
