### PR TITLE
fix Kol Novel

### LINKED ISSUE #2532: [kol novel] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list 

**To Reproduce**
1. Name of connector kol novel
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to update manga list for kol novel
Failed to receive content from " https//kolnovel.com/wp-admin/admin-ajax.php"(status:400)-

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
IMG_20201028_205206_213

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Robonau**
it seems to have moved to WordPressMangastream but novel
resolves #2532

### CODE REVIEW

File: src/web/mjs/connectors/KolNovel.mjs [hunk 1]
```diff
@@ -9,6 +9,58 @@ export default class KolNovel extends WordPressMadaraNovel {
...
+        this.novelWidth = '56em'; // parseInt(1200 / window.devicePixelRatio) + 'px';
+        this.novelPadding = '1.5em';
+    }
+
+    async _getChapters(manga) {
+        let request = new Request(new URL(manga.id, this.url), this.requestOptions);
+        let data = await this.fetchDOM(request, this.queryChapters);
+        return data.map(element => {
+            this.adLinkDecrypt(element);
+            const title = this.queryChaptersTitle ? [...element.querySelectorAll(this.queryChaptersTitle)].map(ele => ele.textContent).join(' ') : element.text;
```
Comment (Robonau) [inline src/web/mjs/connectors/KolNovel.mjs:28]: this might be able to be put in the template, depends if all the connectors using WordPressMangastream template only have one result with `this.queryChaptersTitle`

Comment (Robonau) [reply src/web/mjs/connectors/KolNovel.mjs:28]: or should i just make a WordPressMangastreamNovel template (same way as madaraNovel)

Comment (27136773) [reply src/web/mjs/connectors/KolNovel.mjs:28]: If you think the query is common and works for all websites then it needs to be confirmed by checking all websites with it. When successful it can be moved to the template.

Comment (27136773) [reply src/web/mjs/connectors/KolNovel.mjs:28]: If you expect there will be more websites which may use the template, then create a separate template.
If you think the website just customized the WorpressMangaStream template, then don't create a separate template.

**Review by 27136773 — APPROVED** [review]
Looks good

File: src/web/mjs/connectors/KolNovel.mjs (hunk 1 above)
Comment (Robonau) [reply src/web/mjs/connectors/KolNovel.mjs:28]: il just leave it for now, as there are alot of WordPressMangastream connectors 
il leave the comment about WordPressMangastreamNovel encase it is a template that is reused in the future (wpthemedetector cant see kolnovel fsr)
