### PR TITLE
Fix SmackJeeves

### LINKED ISSUE #1964: Smack Jeeves is not working
> **From:** HakuNeko User

**Version:** [6.1.7@d8c08b](https://github.com/manga-download/hakuneko/commits/d8c08b)

When selecting Smack Jeeves as a connector it errors out on an update list. Using the Clipboard and downloading a single URL also fails.

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

### PR DESCRIPTION
**Pull request by XenonR**
~~Adds node_module [he](https://github.com/mathiasbynens/he) for DOM independent html entity decoding.~~
Closes #1964

### CODE REVIEW

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 1]
```diff
@@ -1,130 +1,99 @@
...
-     *
-     */
     constructor() {
         super();
         super.id = 'smackjeeves';
         super.label = 'Smack Jeeves';
         this.tags = [ 'webtoon', 'english' ];
-        this.url = 'http://www.smackjeeves.com';
+        this.url = 'https://www.smackjeeves.com';
+        this.he = require('he');
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: `he` should be available as global (on window), if `require` is used something seems not to be as intended.
`require` is only for installed electron packages.

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 2]
```diff
@@ -1,130 +1,99 @@
...
+                } catch(error) {
+                    reject(error);
                 }
-            } );
+            });
+        `;
+        const request = new Request(new URL(url), this.requestOptions);
+        const data = await Engine.Request.fetchUI(request, script);
+
+        return data.navigation.items;
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: May use `data.navigation.items.map(item => item.val)`, since the val is the only thing that is used later on

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 3]
```diff
@@ -1,130 +1,99 @@
...
-                callback( error, undefined );
-            } );
+    async _getMangas() {
+        const categories = await this._getCategories( new URL('/discover?type=genre', this.url));
+
+        let manga_list = [];
+        for (const category of categories) {
+            let url = new URL('/api/getTitleListByGenreDiscover', this.url);
+            url.searchParams.set('genre', category.val);
+            url.searchParams.set('order', 'newarriva');
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: Could this be a typo newarriva`l`, or mistake on website

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 4]
```diff
@@ -1,130 +1,99 @@
...
+
+            let pages = 1;
```
Comment (ronny1982) [inline src/web/mjs/connectors/SmackJeeves.mjs:39]: Each category only has a single page? This would make the following for loop obsolete.

File: src/web/index.html [hunk 5]
```diff
@@ -14,6 +14,7 @@
     <script src="./js/ass.min.js" defer></script>
     <script src="./js/sql.min.js" defer></script>
     <script src="./js/exif-js.min.js" defer></script>
+    <script src="./js/he.min.js" defer></script>
```
Comment (27136773) [inline src/web/index.html]: No need for this dependency, HakuNeko can utilize the underlying Browser to do that with 3 lines of code:
https://github.com/manga-download/hakuneko/blob/a361183c2e96075650f8d83f7861bb3c81a96ad3/src/web/mjs/connectors/MangaLife.mjs#L26

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 6]
```diff
@@ -1,130 +1,99 @@
...
+            for (let page = 1; page <= pages; page++) {
+                url.searchParams.set('page', page);
+                const data = await this._fetchPOST(url);
+                pages = data.result.totalPageCnt;
+
+                manga_list.push(...data.result.list.map(element => {
+                    return {
+                        id: this.getRootRelativeOrAbsoluteLink(element.titleUrl, this.url),
+                        title: this.he.decode( element.title ).trim()
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: Don't use `he` as described above

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 7]
```diff
@@ -1,130 +1,99 @@
...
-                callback( null, chapterList );
-            } )
-            .catch( error => {
-                console.error( error, manga );
-                callback( error, undefined );
-            } );
+        return data.result.list.map(element => {
+            return {
+                id: element.articleUrl,
+                title: this.he.decode( element.articleTitle ).trim()
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: Same here, drop `he` and use a small local method to replace HTML entities

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 8]
```diff
@@ -1,130 +1,99 @@
...
+            url.searchParams.set('genre', category.val);
+            url.searchParams.set('order', 'newarriva');
+
+            let pages = 1;
+            for (let page = 1; page <= pages; page++) {
+                url.searchParams.set('page', page);
+                const data = await this._fetchPOST(url);
+                pages = data.result.totalPageCnt;
+
+                manga_list.push(...data.result.list.map(element => {
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: May use e.g. `item` instead of `element`, since the latter may make developers believe this is an HTML element (which wouldn't require to deal with HTML entities)

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 9]
```diff
@@ -1,130 +1,99 @@
...
+        const data = await this._fetchPOST(url);
 
-                }
-                callback( null, chapterList );
-            } )
-            .catch( error => {
-                console.error( error, manga );
-                callback( error, undefined );
-            } );
+        return data.result.list.map(element => {
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: May use e.g. `item` instead of `element`

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 10]
```diff
@@ -1,130 +1,99 @@
...
-                let pageLinks = data.map( element => this.createConnectorURI( this.getAbsolutePath( element.value, request.url ) ) );
-                callback( null, pageLinks );
-            } )
-            .catch( error => {
-                console.error( error, chapter );
-                callback( error, undefined );
-            } );
+    async _getPages(chapter) {
+        const script = `
+            new Promise((resolve, reject) => {
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: Can be simplified to `new Promise(resolve => resolve(cmnDate.comicData));`
A promise will reject exceptions automatically (as long as they are not within an async scope, e.g. setTimeout)

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 11]
```diff
@@ -1,130 +1,99 @@
...
+                    resolve(cmnData.comicData);
+                } catch(error) {
+                    reject(error);
+                }
+            });
+        `;
+        const request = new Request(new URL(chapter.id, this.url), this.requestOptions);
+        const data = await Engine.Request.fetchUI(request, script);
+
+        return data.map(element => {
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: May embed the `map` into the injected script and return `fetchUI` directly

File: src/web/mjs/connectors/SmackJeeves.mjs [hunk 12]
```diff
@@ -1,130 +1,99 @@
...
-        /*
-         * TODO: only perform requests when from download manager
-         * or when from browser for preview and selected chapter matches
-         */
-        return this.fetchDOM( request, 'source#comic_image' )
-            .then( data => super._handleConnectorURI( this.getAbsolutePath( data[0], request.url ) ) );
+    async _fetchPOST( uri) {
+        const request = new Request(new URL(uri.pathname, this.url), {
+            method: 'POST',
+            body: uri.searchParams.toString(),
```
Comment (27136773) [inline src/web/mjs/connectors/SmackJeeves.mjs]: Placing the form data into the GET parameters of the URL is misleading, i would suggest to separate parameter concerns (what if you have to fetch an URL that actually has some required GET parameters?):

```javascript
async _fetchPOST(uri, form) {
    fetch(uri, {
        body: form.toString()
    });
}

async foobar() {
    let uri = new URL('http://foo.bar?genre=bla')
    let form = new URLSearchParams();
    form.set('token', 123);
    form.set('page', 123);
    let data = await this._fetchPOST(uri, form);
    // ...
```

**Review by 27136773 — COMMENTED** [review]
The `he` dependency should be removed, then it is ready to go

File: src/web/mjs/connectors/SmackJeeves.mjs (hunk 3 above)
Comment (XenonR) [reply src/web/mjs/connectors/SmackJeeves.mjs]: If it is, it was the websites programmers typo 😂

File: src/web/mjs/connectors/SmackJeeves.mjs (hunk 8 above)
Comment (XenonR) [reply src/web/mjs/connectors/SmackJeeves.mjs]: What's the idea here? Is it better practice or easier readable for others?

File: src/web/mjs/connectors/SmackJeeves.mjs (hunk 2 above)
Comment (XenonR) [reply src/web/mjs/connectors/SmackJeeves.mjs]: I like that. `.map()` is still a thing where i learn something everytime i use it.

File: src/web/mjs/connectors/SmackJeeves.mjs (hunk 12 above)
Comment (XenonR) [reply src/web/mjs/connectors/SmackJeeves.mjs]: You're right. Can be misleading. Modified.

File: src/web/mjs/connectors/SmackJeeves.mjs (hunk 8 above)
Comment (ronny1982) [reply src/web/mjs/connectors/SmackJeeves.mjs:45]: Readability, i was confused at first because the loop seemed to run only once and then noted that the `pages` variable in the condition of the for loop got changed dynamically

Comment (27136773) [reply src/web/mjs/connectors/SmackJeeves.mjs]: Readability:
```javascript
let bike = new Car();
let car = new Car();
```

**Review by 27136773 — APPROVED** [review]
Really sleepy right now, but i would still dare to say it is ready for merge
