### PR TITLE
[ComicPunch] Connector not working #2387

### LINKED ISSUE #2387: [ComicPunch] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No chapter from all title comic from ComicPunch
im using Windows 8 64 bit

**To Reproduce**
Screenshot (10)

1. Name of connector : ComicPunch
2. Name of manga (if connector update is working) : All of Tittle
3. Name of chapter (if manga update is working) 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] : 6.17@5365bd

### PR DESCRIPTION
**Pull request by Robonau**
resolves #2387

### CODE REVIEW

File: src/web/mjs/connectors/ReadComicBooksOnline.mjs [hunk 1]
```diff
@@ -61,20 +61,11 @@ export default class ReadComicBooksOnline extends Connector {
...
-                } ) );
-                callback( null, pageList );
-            } )
-            .catch( error => {
-                console.error( error, chapter );
-                callback( error, undefined );
-            } );
+    async _getPages(chapter) {
+        let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
+        let data = await this.fetchRegex(request, /messages\s*=\s*(\[.*\])\s*;/g);
```
Comment (27136773) [inline src/web/mjs/connectors/ReadComicBooksOnline.mjs]: I would change the regex to be either non-greedy or consume all characters except `]` in the capture group, otherwise it may include all `]` up to the last closing `]` which is probably not desired
`/messages\s*=\s*(\[[^\]]+\])\s*;/g`
See: https://regex101.com/r/M7ZepM/1

**Review by 27136773 — APPROVED** [review]
Looks good
