### PR TITLE
Bilibili : handle differents image token servers

### LINKED ISSUE #4673: [Bilibili] Comics manhua chapters show first & last page only
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When viewing any latest chapter on bilibili comics, it shows the first and last page ONLY.

**To Reproduce**
1. Go to 'Bilibili comics'
2. Click on 'any manhua'
3. Click on the latest chapters
4. See error showing first and last page ONLY.

**Expected behavior**
Show all the pages of the chapter

**Screenshots**
Latest Chapters showing first and last page.
Screenshot (56)

previous chapters showing all the pages.
Screenshot (57)

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

### LINKED ISSUE #4698: [Bilibili ] Unlocked Chapters through wait-time cannot be downloaded
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Bilibili comics time-gated chapters that have been unlocked remained un-downloadable.

**To Reproduce**
Logged in as usual through the web-reader. Full Chapter can be viewed from web-reader, going back to hakuneko, it's locked.

**Expected behavior**
Should be able to download if chapter is already unlocked on reader, regardless of whether it's paid or time-unlocked.

image

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.1.7 @cf569b

### LINKED ISSUE #5013: [bilibili] Not downloading all pages
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Whenever I try to download updates on Bilibili comics, the lastest chapters won't have the full images. It only downloads  two pages of the chapters.

**To Reproduce**

**Expected behavior**

**Screenshots**

adfdff

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

### PR DESCRIPTION
**Pull request by MikeZeDev**
When Login, you get an area code. This area define the server used to get the tokens for pictures : us-user or sg-user. So now we get area code too and switch server.

Fixes  https://github.com/manga-download/hakuneko/issues/5013
Fixes https://github.com/manga-download/hakuneko/issues/4698
Fixes https://github.com/manga-download/hakuneko/issues/4673

### CODE REVIEW

File: src/web/mjs/connectors/BilibiliManhua.mjs [hunk 1]
```diff
@@ -13,7 +13,11 @@ export default class BilibiliManhua extends Connector {
         this.auth = {
             accessToken : '',
             refreshToken : '',
+            area : 1
```
Comment (27136773) [inline src/web/mjs/connectors/BilibiliManhua.mjs:16]: Maybe use `area` variable as string `area: this.areacode[1];`

**Review by 27136773 — APPROVED** [review]

File: src/web/mjs/connectors/BilibiliManhua.mjs (hunk 1 above)
Comment (MikeZeDev) [reply src/web/mjs/connectors/BilibiliManhua.mjs:16]: > Maybe use `area` variable as string `area: this.areacode[1];`

Good idea, but its saved as a number in cookies so i'd rather keep the same data type. It may make further fixes easier.
