### PR TITLE
[HatsukiManga] Fix image not downloading

### LINKED ISSUE #3391: [Hatsukimanga.com] not downloading
The series do appear to download but when you click to start an error appears.

### PR DESCRIPTION
**Pull request by dodieboy**
fix #3391

### CODE REVIEW

File: src/web/mjs/connectors/HatsukiManga.mjs [hunk 1]
```diff
@@ -57,6 +57,6 @@ export default class HatsukiManga extends Connector {
     async _getPages(chapter) {
         let request = new Request(new URL(chapter.id, this.url), this.requestOptions);
         let data = await this.fetchDOM(request, 'ul.lista-de-paginas li.li-pagina source.imagen-pagina');
-        return data.map(element => this.getAbsolutePath(element, request.url)).filter(link => /(.jpg|.png|.webp)$/.test(link));
+        return data.map(element => this.getAbsolutePath(element.getAttribute('data-src') || element, request.url)).filter(link => /(.jpg|.png|.webp)$/.test(link));
```
Comment (27136773) [inline src/web/mjs/connectors/HatsukiManga.mjs:60]: May use `element.dataset.src` instead

**Review by 27136773 — APPROVED** [review]
Looks good, optional minor improvements possible

File: src/web/mjs/connectors/HatsukiManga.mjs (hunk 1 above)
Comment (dodieboy) [reply src/web/mjs/connectors/HatsukiManga.mjs:60]: On my side, src is empty, only data-src have link
